// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/capture_defense/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgRecordVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	RoundId       string                 `protobuf:"bytes,3,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Validators    []string               `protobuf:"bytes,4,rep,name=validators,proto3" json:"validators,omitempty"`
	Verdicts      []bool                 `protobuf:"varint,5,rep,packed,name=verdicts,proto3" json:"verdicts,omitempty"`
	SubmitBlocks  []uint64               `protobuf:"varint,6,rep,packed,name=submit_blocks,json=submitBlocks,proto3" json:"submit_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRecordVerification) Reset() {
	*x = MsgRecordVerification{}
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRecordVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRecordVerification) ProtoMessage() {}

func (x *MsgRecordVerification) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRecordVerification.ProtoReflect.Descriptor instead.
func (*MsgRecordVerification) Descriptor() ([]byte, []int) {
	return file_zerone_capture_defense_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgRecordVerification) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRecordVerification) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MsgRecordVerification) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *MsgRecordVerification) GetValidators() []string {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *MsgRecordVerification) GetVerdicts() []bool {
	if x != nil {
		return x.Verdicts
	}
	return nil
}

func (x *MsgRecordVerification) GetSubmitBlocks() []uint64 {
	if x != nil {
		return x.SubmitBlocks
	}
	return nil
}

type MsgRecordVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRecordVerificationResponse) Reset() {
	*x = MsgRecordVerificationResponse{}
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRecordVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRecordVerificationResponse) ProtoMessage() {}

func (x *MsgRecordVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRecordVerificationResponse.ProtoReflect.Descriptor instead.
func (*MsgRecordVerificationResponse) Descriptor() ([]byte, []int) {
	return file_zerone_capture_defense_v1_tx_proto_rawDescGZIP(), []int{1}
}

type MsgAnalyzeDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAnalyzeDomain) Reset() {
	*x = MsgAnalyzeDomain{}
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAnalyzeDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAnalyzeDomain) ProtoMessage() {}

func (x *MsgAnalyzeDomain) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAnalyzeDomain.ProtoReflect.Descriptor instead.
func (*MsgAnalyzeDomain) Descriptor() ([]byte, []int) {
	return file_zerone_capture_defense_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgAnalyzeDomain) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgAnalyzeDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type MsgAnalyzeDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiskScore     uint64                 `protobuf:"varint,1,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Flagged       bool                   `protobuf:"varint,2,opt,name=flagged,proto3" json:"flagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAnalyzeDomainResponse) Reset() {
	*x = MsgAnalyzeDomainResponse{}
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAnalyzeDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAnalyzeDomainResponse) ProtoMessage() {}

func (x *MsgAnalyzeDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAnalyzeDomainResponse.ProtoReflect.Descriptor instead.
func (*MsgAnalyzeDomainResponse) Descriptor() ([]byte, []int) {
	return file_zerone_capture_defense_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgAnalyzeDomainResponse) GetRiskScore() uint64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *MsgAnalyzeDomainResponse) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_zerone_capture_defense_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_capture_defense_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_capture_defense_v1_tx_proto_rawDescGZIP(), []int{5}
}

var File_zerone_capture_defense_v1_tx_proto protoreflect.FileDescriptor

const file_zerone_capture_defense_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\"zerone/capture_defense/v1/tx.proto\x12\x19zerone.capture_defense.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a'zerone/capture_defense/v1/genesis.proto\"\xd9\x01\n" +
	"\x15MsgRecordVerification\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x19\n" +
	"\bround_id\x18\x03 \x01(\tR\aroundId\x12\x1e\n" +
	"\n" +
	"validators\x18\x04 \x03(\tR\n" +
	"validators\x12\x1a\n" +
	"\bverdicts\x18\x05 \x03(\bR\bverdicts\x12#\n" +
	"\rsubmit_blocks\x18\x06 \x03(\x04R\fsubmitBlocks:\x0e\x82\xe7\xb0*\tauthority\"\x1f\n" +
	"\x1dMsgRecordVerificationResponse\"O\n" +
	"\x10MsgAnalyzeDomain\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain:\v\x82\xe7\xb0*\x06sender\"S\n" +
	"\x18MsgAnalyzeDomainResponse\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x01 \x01(\x04R\triskScore\x12\x18\n" +
	"\aflagged\x18\x02 \x01(\bR\aflagged\"z\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x129\n" +
	"\x06params\x18\x02 \x01(\v2!.zerone.capture_defense.v1.ParamsR\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\xf2\x02\n" +
	"\x03Msg\x12\x80\x01\n" +
	"\x12RecordVerification\x120.zerone.capture_defense.v1.MsgRecordVerification\x1a8.zerone.capture_defense.v1.MsgRecordVerificationResponse\x12q\n" +
	"\rAnalyzeDomain\x12+.zerone.capture_defense.v1.MsgAnalyzeDomain\x1a3.zerone.capture_defense.v1.MsgAnalyzeDomainResponse\x12n\n" +
	"\fUpdateParams\x12*.zerone.capture_defense.v1.MsgUpdateParams\x1a2.zerone.capture_defense.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B8Z6github.com/zerone-chain/zerone/x/capture_defense/typesb\x06proto3"

var (
	file_zerone_capture_defense_v1_tx_proto_rawDescOnce sync.Once
	file_zerone_capture_defense_v1_tx_proto_rawDescData []byte
)

func file_zerone_capture_defense_v1_tx_proto_rawDescGZIP() []byte {
	file_zerone_capture_defense_v1_tx_proto_rawDescOnce.Do(func() {
		file_zerone_capture_defense_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_capture_defense_v1_tx_proto_rawDesc), len(file_zerone_capture_defense_v1_tx_proto_rawDesc)))
	})
	return file_zerone_capture_defense_v1_tx_proto_rawDescData
}

var file_zerone_capture_defense_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zerone_capture_defense_v1_tx_proto_goTypes = []any{
	(*MsgRecordVerification)(nil),         // 0: zerone.capture_defense.v1.MsgRecordVerification
	(*MsgRecordVerificationResponse)(nil), // 1: zerone.capture_defense.v1.MsgRecordVerificationResponse
	(*MsgAnalyzeDomain)(nil),              // 2: zerone.capture_defense.v1.MsgAnalyzeDomain
	(*MsgAnalyzeDomainResponse)(nil),      // 3: zerone.capture_defense.v1.MsgAnalyzeDomainResponse
	(*MsgUpdateParams)(nil),               // 4: zerone.capture_defense.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),       // 5: zerone.capture_defense.v1.MsgUpdateParamsResponse
	(*Params)(nil),                        // 6: zerone.capture_defense.v1.Params
}
var file_zerone_capture_defense_v1_tx_proto_depIdxs = []int32{
	6, // 0: zerone.capture_defense.v1.MsgUpdateParams.params:type_name -> zerone.capture_defense.v1.Params
	0, // 1: zerone.capture_defense.v1.Msg.RecordVerification:input_type -> zerone.capture_defense.v1.MsgRecordVerification
	2, // 2: zerone.capture_defense.v1.Msg.AnalyzeDomain:input_type -> zerone.capture_defense.v1.MsgAnalyzeDomain
	4, // 3: zerone.capture_defense.v1.Msg.UpdateParams:input_type -> zerone.capture_defense.v1.MsgUpdateParams
	1, // 4: zerone.capture_defense.v1.Msg.RecordVerification:output_type -> zerone.capture_defense.v1.MsgRecordVerificationResponse
	3, // 5: zerone.capture_defense.v1.Msg.AnalyzeDomain:output_type -> zerone.capture_defense.v1.MsgAnalyzeDomainResponse
	5, // 6: zerone.capture_defense.v1.Msg.UpdateParams:output_type -> zerone.capture_defense.v1.MsgUpdateParamsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zerone_capture_defense_v1_tx_proto_init() }
func file_zerone_capture_defense_v1_tx_proto_init() {
	if File_zerone_capture_defense_v1_tx_proto != nil {
		return
	}
	file_zerone_capture_defense_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_capture_defense_v1_tx_proto_rawDesc), len(file_zerone_capture_defense_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_capture_defense_v1_tx_proto_goTypes,
		DependencyIndexes: file_zerone_capture_defense_v1_tx_proto_depIdxs,
		MessageInfos:      file_zerone_capture_defense_v1_tx_proto_msgTypes,
	}.Build()
	File_zerone_capture_defense_v1_tx_proto = out.File
	file_zerone_capture_defense_v1_tx_proto_goTypes = nil
	file_zerone_capture_defense_v1_tx_proto_depIdxs = nil
}
