// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/creed/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgAnchorPin struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Authority string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// The new pinned creed. version MUST equal currentPin.version+1.
	// canonical_hash MUST be non-empty. commitments MUST satisfy:
	//   - all numbers unique
	//   - numbers are 1..N for some N (no gaps unless the missing
	//     number's prior entry is archived in this same version)
	//   - introduced_at_height ≤ block_height for all entries
	Pin *PinnedCreed `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	// The LIP id this pin came from. Required when params.
	// direct_anchor_enabled is false. Empty allowed only for
	// genesis-equivalent pre-launch pins.
	SourceLip     string `protobuf:"bytes,3,opt,name=source_lip,json=sourceLip,proto3" json:"source_lip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAnchorPin) Reset() {
	*x = MsgAnchorPin{}
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAnchorPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAnchorPin) ProtoMessage() {}

func (x *MsgAnchorPin) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAnchorPin.ProtoReflect.Descriptor instead.
func (*MsgAnchorPin) Descriptor() ([]byte, []int) {
	return file_zerone_creed_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgAnchorPin) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgAnchorPin) GetPin() *PinnedCreed {
	if x != nil {
		return x.Pin
	}
	return nil
}

func (x *MsgAnchorPin) GetSourceLip() string {
	if x != nil {
		return x.SourceLip
	}
	return ""
}

type MsgAnchorPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewVersion    uint32                 `protobuf:"varint,1,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAnchorPinResponse) Reset() {
	*x = MsgAnchorPinResponse{}
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAnchorPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAnchorPinResponse) ProtoMessage() {}

func (x *MsgAnchorPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAnchorPinResponse.ProtoReflect.Descriptor instead.
func (*MsgAnchorPinResponse) Descriptor() ([]byte, []int) {
	return file_zerone_creed_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgAnchorPinResponse) GetNewVersion() uint32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_zerone_creed_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_creed_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_creed_v1_tx_proto_rawDescGZIP(), []int{3}
}

var File_zerone_creed_v1_tx_proto protoreflect.FileDescriptor

const file_zerone_creed_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x18zerone/creed/v1/tx.proto\x12\x0fzerone.creed.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x1bzerone/creed/v1/types.proto\x1a\x1dzerone/creed/v1/genesis.proto\"\x8b\x01\n" +
	"\fMsgAnchorPin\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12.\n" +
	"\x03pin\x18\x02 \x01(\v2\x1c.zerone.creed.v1.PinnedCreedR\x03pin\x12\x1d\n" +
	"\n" +
	"source_lip\x18\x03 \x01(\tR\tsourceLip:\x0e\x82\xe7\xb0*\tauthority\"7\n" +
	"\x14MsgAnchorPinResponse\x12\x1f\n" +
	"\vnew_version\x18\x01 \x01(\rR\n" +
	"newVersion\"p\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.zerone.creed.v1.ParamsR\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\xbb\x01\n" +
	"\x03Msg\x12Q\n" +
	"\tAnchorPin\x12\x1d.zerone.creed.v1.MsgAnchorPin\x1a%.zerone.creed.v1.MsgAnchorPinResponse\x12Z\n" +
	"\fUpdateParams\x12 .zerone.creed.v1.MsgUpdateParams\x1a(.zerone.creed.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B.Z,github.com/zerone-chain/zerone/x/creed/typesb\x06proto3"

var (
	file_zerone_creed_v1_tx_proto_rawDescOnce sync.Once
	file_zerone_creed_v1_tx_proto_rawDescData []byte
)

func file_zerone_creed_v1_tx_proto_rawDescGZIP() []byte {
	file_zerone_creed_v1_tx_proto_rawDescOnce.Do(func() {
		file_zerone_creed_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_creed_v1_tx_proto_rawDesc), len(file_zerone_creed_v1_tx_proto_rawDesc)))
	})
	return file_zerone_creed_v1_tx_proto_rawDescData
}

var file_zerone_creed_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zerone_creed_v1_tx_proto_goTypes = []any{
	(*MsgAnchorPin)(nil),            // 0: zerone.creed.v1.MsgAnchorPin
	(*MsgAnchorPinResponse)(nil),    // 1: zerone.creed.v1.MsgAnchorPinResponse
	(*MsgUpdateParams)(nil),         // 2: zerone.creed.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil), // 3: zerone.creed.v1.MsgUpdateParamsResponse
	(*PinnedCreed)(nil),             // 4: zerone.creed.v1.PinnedCreed
	(*Params)(nil),                  // 5: zerone.creed.v1.Params
}
var file_zerone_creed_v1_tx_proto_depIdxs = []int32{
	4, // 0: zerone.creed.v1.MsgAnchorPin.pin:type_name -> zerone.creed.v1.PinnedCreed
	5, // 1: zerone.creed.v1.MsgUpdateParams.params:type_name -> zerone.creed.v1.Params
	0, // 2: zerone.creed.v1.Msg.AnchorPin:input_type -> zerone.creed.v1.MsgAnchorPin
	2, // 3: zerone.creed.v1.Msg.UpdateParams:input_type -> zerone.creed.v1.MsgUpdateParams
	1, // 4: zerone.creed.v1.Msg.AnchorPin:output_type -> zerone.creed.v1.MsgAnchorPinResponse
	3, // 5: zerone.creed.v1.Msg.UpdateParams:output_type -> zerone.creed.v1.MsgUpdateParamsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zerone_creed_v1_tx_proto_init() }
func file_zerone_creed_v1_tx_proto_init() {
	if File_zerone_creed_v1_tx_proto != nil {
		return
	}
	file_zerone_creed_v1_types_proto_init()
	file_zerone_creed_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_creed_v1_tx_proto_rawDesc), len(file_zerone_creed_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_creed_v1_tx_proto_goTypes,
		DependencyIndexes: file_zerone_creed_v1_tx_proto_depIdxs,
		MessageInfos:      file_zerone_creed_v1_tx_proto_msgTypes,
	}.Build()
	File_zerone_creed_v1_tx_proto = out.File
	file_zerone_creed_v1_tx_proto_goTypes = nil
	file_zerone_creed_v1_tx_proto_depIdxs = nil
}
