// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/ontology/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryStratumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stratum       uint32                 `protobuf:"varint,1,opt,name=stratum,proto3" json:"stratum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStratumRequest) Reset() {
	*x = QueryStratumRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStratumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStratumRequest) ProtoMessage() {}

func (x *QueryStratumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStratumRequest.ProtoReflect.Descriptor instead.
func (*QueryStratumRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStratumRequest) GetStratum() uint32 {
	if x != nil {
		return x.Stratum
	}
	return 0
}

type QueryStratumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    *StratumProperties     `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStratumResponse) Reset() {
	*x = QueryStratumResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStratumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStratumResponse) ProtoMessage() {}

func (x *QueryStratumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStratumResponse.ProtoReflect.Descriptor instead.
func (*QueryStratumResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryStratumResponse) GetProperties() *StratumProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type QueryAllStrataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllStrataRequest) Reset() {
	*x = QueryAllStrataRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllStrataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllStrataRequest) ProtoMessage() {}

func (x *QueryAllStrataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllStrataRequest.ProtoReflect.Descriptor instead.
func (*QueryAllStrataRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{4}
}

type QueryAllStrataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strata        []*StratumProperties   `protobuf:"bytes,1,rep,name=strata,proto3" json:"strata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllStrataResponse) Reset() {
	*x = QueryAllStrataResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllStrataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllStrataResponse) ProtoMessage() {}

func (x *QueryAllStrataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllStrataResponse.ProtoReflect.Descriptor instead.
func (*QueryAllStrataResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryAllStrataResponse) GetStrata() []*StratumProperties {
	if x != nil {
		return x.Strata
	}
	return nil
}

type QueryDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDomainRequest) Reset() {
	*x = QueryDomainRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDomainRequest) ProtoMessage() {}

func (x *QueryDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDomainRequest.ProtoReflect.Descriptor instead.
func (*QueryDomainRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *Domain                `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDomainResponse) Reset() {
	*x = QueryDomainResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDomainResponse) ProtoMessage() {}

func (x *QueryDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDomainResponse.ProtoReflect.Descriptor instead.
func (*QueryDomainResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryDomainResponse) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type QueryDomainsByStratumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stratum       uint32                 `protobuf:"varint,1,opt,name=stratum,proto3" json:"stratum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDomainsByStratumRequest) Reset() {
	*x = QueryDomainsByStratumRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDomainsByStratumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDomainsByStratumRequest) ProtoMessage() {}

func (x *QueryDomainsByStratumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDomainsByStratumRequest.ProtoReflect.Descriptor instead.
func (*QueryDomainsByStratumRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryDomainsByStratumRequest) GetStratum() uint32 {
	if x != nil {
		return x.Stratum
	}
	return 0
}

type QueryDomainsByStratumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*Domain              `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDomainsByStratumResponse) Reset() {
	*x = QueryDomainsByStratumResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDomainsByStratumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDomainsByStratumResponse) ProtoMessage() {}

func (x *QueryDomainsByStratumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDomainsByStratumResponse.ProtoReflect.Descriptor instead.
func (*QueryDomainsByStratumResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryDomainsByStratumResponse) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type QueryAllDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllDomainsRequest) Reset() {
	*x = QueryAllDomainsRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllDomainsRequest) ProtoMessage() {}

func (x *QueryAllDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllDomainsRequest.ProtoReflect.Descriptor instead.
func (*QueryAllDomainsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{10}
}

type QueryAllDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*Domain              `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllDomainsResponse) Reset() {
	*x = QueryAllDomainsResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllDomainsResponse) ProtoMessage() {}

func (x *QueryAllDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllDomainsResponse.ProtoReflect.Descriptor instead.
func (*QueryAllDomainsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryAllDomainsResponse) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type QueryProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProposalRequest) Reset() {
	*x = QueryProposalRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProposalRequest) ProtoMessage() {}

func (x *QueryProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProposalRequest.ProtoReflect.Descriptor instead.
func (*QueryProposalRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryProposalRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

type QueryProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *DomainProposal        `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProposalResponse) Reset() {
	*x = QueryProposalResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProposalResponse) ProtoMessage() {}

func (x *QueryProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProposalResponse.ProtoReflect.Descriptor instead.
func (*QueryProposalResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryProposalResponse) GetProposal() *DomainProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type QueryConfidenceCeilingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainName    string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConfidenceCeilingRequest) Reset() {
	*x = QueryConfidenceCeilingRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConfidenceCeilingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConfidenceCeilingRequest) ProtoMessage() {}

func (x *QueryConfidenceCeilingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConfidenceCeilingRequest.ProtoReflect.Descriptor instead.
func (*QueryConfidenceCeilingRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QueryConfidenceCeilingRequest) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

type QueryConfidenceCeilingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxConfidence uint64                 `protobuf:"varint,1,opt,name=max_confidence,json=maxConfidence,proto3" json:"max_confidence,omitempty"`
	DecayRate     uint64                 `protobuf:"varint,2,opt,name=decay_rate,json=decayRate,proto3" json:"decay_rate,omitempty"`
	DomainName    string                 `protobuf:"bytes,3,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	StratumName   string                 `protobuf:"bytes,4,opt,name=stratum_name,json=stratumName,proto3" json:"stratum_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConfidenceCeilingResponse) Reset() {
	*x = QueryConfidenceCeilingResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConfidenceCeilingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConfidenceCeilingResponse) ProtoMessage() {}

func (x *QueryConfidenceCeilingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConfidenceCeilingResponse.ProtoReflect.Descriptor instead.
func (*QueryConfidenceCeilingResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *QueryConfidenceCeilingResponse) GetMaxConfidence() uint64 {
	if x != nil {
		return x.MaxConfidence
	}
	return 0
}

func (x *QueryConfidenceCeilingResponse) GetDecayRate() uint64 {
	if x != nil {
		return x.DecayRate
	}
	return 0
}

func (x *QueryConfidenceCeilingResponse) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *QueryConfidenceCeilingResponse) GetStratumName() string {
	if x != nil {
		return x.StratumName
	}
	return ""
}

type QueryLogicZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogicZoneRequest) Reset() {
	*x = QueryLogicZoneRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogicZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogicZoneRequest) ProtoMessage() {}

func (x *QueryLogicZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogicZoneRequest.ProtoReflect.Descriptor instead.
func (*QueryLogicZoneRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryLogicZoneRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type QueryLogicZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    *LogicZoneProperties   `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogicZoneResponse) Reset() {
	*x = QueryLogicZoneResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogicZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogicZoneResponse) ProtoMessage() {}

func (x *QueryLogicZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogicZoneResponse.ProtoReflect.Descriptor instead.
func (*QueryLogicZoneResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryLogicZoneResponse) GetProperties() *LogicZoneProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type QueryAllLogicZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllLogicZonesRequest) Reset() {
	*x = QueryAllLogicZonesRequest{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllLogicZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllLogicZonesRequest) ProtoMessage() {}

func (x *QueryAllLogicZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllLogicZonesRequest.ProtoReflect.Descriptor instead.
func (*QueryAllLogicZonesRequest) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{18}
}

type QueryAllLogicZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*LogicZoneProperties `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllLogicZonesResponse) Reset() {
	*x = QueryAllLogicZonesResponse{}
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllLogicZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllLogicZonesResponse) ProtoMessage() {}

func (x *QueryAllLogicZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllLogicZonesResponse.ProtoReflect.Descriptor instead.
func (*QueryAllLogicZonesResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_query_proto_rawDescGZIP(), []int{19}
}

func (x *QueryAllLogicZonesResponse) GetZones() []*LogicZoneProperties {
	if x != nil {
		return x.Zones
	}
	return nil
}

var File_zerone_ontology_v1_query_proto protoreflect.FileDescriptor

const file_zerone_ontology_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1ezerone/ontology/v1/query.proto\x12\x12zerone.ontology.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1ezerone/ontology/v1/state.proto\x1a zerone/ontology/v1/genesis.proto\"\x14\n" +
	"\x12QueryParamsRequest\"I\n" +
	"\x13QueryParamsResponse\x122\n" +
	"\x06params\x18\x01 \x01(\v2\x1a.zerone.ontology.v1.ParamsR\x06params\"/\n" +
	"\x13QueryStratumRequest\x12\x18\n" +
	"\astratum\x18\x01 \x01(\rR\astratum\"]\n" +
	"\x14QueryStratumResponse\x12E\n" +
	"\n" +
	"properties\x18\x01 \x01(\v2%.zerone.ontology.v1.StratumPropertiesR\n" +
	"properties\"\x17\n" +
	"\x15QueryAllStrataRequest\"W\n" +
	"\x16QueryAllStrataResponse\x12=\n" +
	"\x06strata\x18\x01 \x03(\v2%.zerone.ontology.v1.StratumPropertiesR\x06strata\"(\n" +
	"\x12QueryDomainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x13QueryDomainResponse\x122\n" +
	"\x06domain\x18\x01 \x01(\v2\x1a.zerone.ontology.v1.DomainR\x06domain\"8\n" +
	"\x1cQueryDomainsByStratumRequest\x12\x18\n" +
	"\astratum\x18\x01 \x01(\rR\astratum\"U\n" +
	"\x1dQueryDomainsByStratumResponse\x124\n" +
	"\adomains\x18\x01 \x03(\v2\x1a.zerone.ontology.v1.DomainR\adomains\"\x18\n" +
	"\x16QueryAllDomainsRequest\"O\n" +
	"\x17QueryAllDomainsResponse\x124\n" +
	"\adomains\x18\x01 \x03(\v2\x1a.zerone.ontology.v1.DomainR\adomains\"7\n" +
	"\x14QueryProposalRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\"W\n" +
	"\x15QueryProposalResponse\x12>\n" +
	"\bproposal\x18\x01 \x01(\v2\".zerone.ontology.v1.DomainProposalR\bproposal\"@\n" +
	"\x1dQueryConfidenceCeilingRequest\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\"\xaa\x01\n" +
	"\x1eQueryConfidenceCeilingResponse\x12%\n" +
	"\x0emax_confidence\x18\x01 \x01(\x04R\rmaxConfidence\x12\x1d\n" +
	"\n" +
	"decay_rate\x18\x02 \x01(\x04R\tdecayRate\x12\x1f\n" +
	"\vdomain_name\x18\x03 \x01(\tR\n" +
	"domainName\x12!\n" +
	"\fstratum_name\x18\x04 \x01(\tR\vstratumName\"+\n" +
	"\x15QueryLogicZoneRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\"a\n" +
	"\x16QueryLogicZoneResponse\x12G\n" +
	"\n" +
	"properties\x18\x01 \x01(\v2'.zerone.ontology.v1.LogicZonePropertiesR\n" +
	"properties\"\x1b\n" +
	"\x19QueryAllLogicZonesRequest\"[\n" +
	"\x1aQueryAllLogicZonesResponse\x12=\n" +
	"\x05zones\x18\x01 \x03(\v2'.zerone.ontology.v1.LogicZonePropertiesR\x05zones2\xe1\v\n" +
	"\x05Query\x12}\n" +
	"\x06Params\x12&.zerone.ontology.v1.QueryParamsRequest\x1a'.zerone.ontology.v1.QueryParamsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/zerone/ontology/v1/params\x12\x8b\x01\n" +
	"\aStratum\x12'.zerone.ontology.v1.QueryStratumRequest\x1a(.zerone.ontology.v1.QueryStratumResponse\"-\x82\xd3\xe4\x93\x02'\x12%/zerone/ontology/v1/stratum/{stratum}\x12\x86\x01\n" +
	"\tAllStrata\x12).zerone.ontology.v1.QueryAllStrataRequest\x1a*.zerone.ontology.v1.QueryAllStrataResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/zerone/ontology/v1/strata\x12\x84\x01\n" +
	"\x06Domain\x12&.zerone.ontology.v1.QueryDomainRequest\x1a'.zerone.ontology.v1.QueryDomainResponse\")\x82\xd3\xe4\x93\x02#\x12!/zerone/ontology/v1/domain/{name}\x12\xae\x01\n" +
	"\x10DomainsByStratum\x120.zerone.ontology.v1.QueryDomainsByStratumRequest\x1a1.zerone.ontology.v1.QueryDomainsByStratumResponse\"5\x82\xd3\xe4\x93\x02/\x12-/zerone/ontology/v1/domains/stratum/{stratum}\x12\x8a\x01\n" +
	"\n" +
	"AllDomains\x12*.zerone.ontology.v1.QueryAllDomainsRequest\x1a+.zerone.ontology.v1.QueryAllDomainsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/zerone/ontology/v1/domains\x12\x93\x01\n" +
	"\bProposal\x12(.zerone.ontology.v1.QueryProposalRequest\x1a).zerone.ontology.v1.QueryProposalResponse\"2\x82\xd3\xe4\x93\x02,\x12*/zerone/ontology/v1/proposal/{proposal_id}\x12\xb8\x01\n" +
	"\x11ConfidenceCeiling\x121.zerone.ontology.v1.QueryConfidenceCeilingRequest\x1a2.zerone.ontology.v1.QueryConfidenceCeilingResponse\"<\x82\xd3\xe4\x93\x026\x124/zerone/ontology/v1/confidence_ceiling/{domain_name}\x12\x91\x01\n" +
	"\tLogicZone\x12).zerone.ontology.v1.QueryLogicZoneRequest\x1a*.zerone.ontology.v1.QueryLogicZoneResponse\"-\x82\xd3\xe4\x93\x02'\x12%/zerone/ontology/v1/logic_zone/{zone}\x12\x97\x01\n" +
	"\rAllLogicZones\x12-.zerone.ontology.v1.QueryAllLogicZonesRequest\x1a..zerone.ontology.v1.QueryAllLogicZonesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/zerone/ontology/v1/logic_zonesB1Z/github.com/zerone-chain/zerone/x/ontology/typesb\x06proto3"

var (
	file_zerone_ontology_v1_query_proto_rawDescOnce sync.Once
	file_zerone_ontology_v1_query_proto_rawDescData []byte
)

func file_zerone_ontology_v1_query_proto_rawDescGZIP() []byte {
	file_zerone_ontology_v1_query_proto_rawDescOnce.Do(func() {
		file_zerone_ontology_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_ontology_v1_query_proto_rawDesc), len(file_zerone_ontology_v1_query_proto_rawDesc)))
	})
	return file_zerone_ontology_v1_query_proto_rawDescData
}

var file_zerone_ontology_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_zerone_ontology_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),             // 0: zerone.ontology.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),            // 1: zerone.ontology.v1.QueryParamsResponse
	(*QueryStratumRequest)(nil),            // 2: zerone.ontology.v1.QueryStratumRequest
	(*QueryStratumResponse)(nil),           // 3: zerone.ontology.v1.QueryStratumResponse
	(*QueryAllStrataRequest)(nil),          // 4: zerone.ontology.v1.QueryAllStrataRequest
	(*QueryAllStrataResponse)(nil),         // 5: zerone.ontology.v1.QueryAllStrataResponse
	(*QueryDomainRequest)(nil),             // 6: zerone.ontology.v1.QueryDomainRequest
	(*QueryDomainResponse)(nil),            // 7: zerone.ontology.v1.QueryDomainResponse
	(*QueryDomainsByStratumRequest)(nil),   // 8: zerone.ontology.v1.QueryDomainsByStratumRequest
	(*QueryDomainsByStratumResponse)(nil),  // 9: zerone.ontology.v1.QueryDomainsByStratumResponse
	(*QueryAllDomainsRequest)(nil),         // 10: zerone.ontology.v1.QueryAllDomainsRequest
	(*QueryAllDomainsResponse)(nil),        // 11: zerone.ontology.v1.QueryAllDomainsResponse
	(*QueryProposalRequest)(nil),           // 12: zerone.ontology.v1.QueryProposalRequest
	(*QueryProposalResponse)(nil),          // 13: zerone.ontology.v1.QueryProposalResponse
	(*QueryConfidenceCeilingRequest)(nil),  // 14: zerone.ontology.v1.QueryConfidenceCeilingRequest
	(*QueryConfidenceCeilingResponse)(nil), // 15: zerone.ontology.v1.QueryConfidenceCeilingResponse
	(*QueryLogicZoneRequest)(nil),          // 16: zerone.ontology.v1.QueryLogicZoneRequest
	(*QueryLogicZoneResponse)(nil),         // 17: zerone.ontology.v1.QueryLogicZoneResponse
	(*QueryAllLogicZonesRequest)(nil),      // 18: zerone.ontology.v1.QueryAllLogicZonesRequest
	(*QueryAllLogicZonesResponse)(nil),     // 19: zerone.ontology.v1.QueryAllLogicZonesResponse
	(*Params)(nil),                         // 20: zerone.ontology.v1.Params
	(*StratumProperties)(nil),              // 21: zerone.ontology.v1.StratumProperties
	(*Domain)(nil),                         // 22: zerone.ontology.v1.Domain
	(*DomainProposal)(nil),                 // 23: zerone.ontology.v1.DomainProposal
	(*LogicZoneProperties)(nil),            // 24: zerone.ontology.v1.LogicZoneProperties
}
var file_zerone_ontology_v1_query_proto_depIdxs = []int32{
	20, // 0: zerone.ontology.v1.QueryParamsResponse.params:type_name -> zerone.ontology.v1.Params
	21, // 1: zerone.ontology.v1.QueryStratumResponse.properties:type_name -> zerone.ontology.v1.StratumProperties
	21, // 2: zerone.ontology.v1.QueryAllStrataResponse.strata:type_name -> zerone.ontology.v1.StratumProperties
	22, // 3: zerone.ontology.v1.QueryDomainResponse.domain:type_name -> zerone.ontology.v1.Domain
	22, // 4: zerone.ontology.v1.QueryDomainsByStratumResponse.domains:type_name -> zerone.ontology.v1.Domain
	22, // 5: zerone.ontology.v1.QueryAllDomainsResponse.domains:type_name -> zerone.ontology.v1.Domain
	23, // 6: zerone.ontology.v1.QueryProposalResponse.proposal:type_name -> zerone.ontology.v1.DomainProposal
	24, // 7: zerone.ontology.v1.QueryLogicZoneResponse.properties:type_name -> zerone.ontology.v1.LogicZoneProperties
	24, // 8: zerone.ontology.v1.QueryAllLogicZonesResponse.zones:type_name -> zerone.ontology.v1.LogicZoneProperties
	0,  // 9: zerone.ontology.v1.Query.Params:input_type -> zerone.ontology.v1.QueryParamsRequest
	2,  // 10: zerone.ontology.v1.Query.Stratum:input_type -> zerone.ontology.v1.QueryStratumRequest
	4,  // 11: zerone.ontology.v1.Query.AllStrata:input_type -> zerone.ontology.v1.QueryAllStrataRequest
	6,  // 12: zerone.ontology.v1.Query.Domain:input_type -> zerone.ontology.v1.QueryDomainRequest
	8,  // 13: zerone.ontology.v1.Query.DomainsByStratum:input_type -> zerone.ontology.v1.QueryDomainsByStratumRequest
	10, // 14: zerone.ontology.v1.Query.AllDomains:input_type -> zerone.ontology.v1.QueryAllDomainsRequest
	12, // 15: zerone.ontology.v1.Query.Proposal:input_type -> zerone.ontology.v1.QueryProposalRequest
	14, // 16: zerone.ontology.v1.Query.ConfidenceCeiling:input_type -> zerone.ontology.v1.QueryConfidenceCeilingRequest
	16, // 17: zerone.ontology.v1.Query.LogicZone:input_type -> zerone.ontology.v1.QueryLogicZoneRequest
	18, // 18: zerone.ontology.v1.Query.AllLogicZones:input_type -> zerone.ontology.v1.QueryAllLogicZonesRequest
	1,  // 19: zerone.ontology.v1.Query.Params:output_type -> zerone.ontology.v1.QueryParamsResponse
	3,  // 20: zerone.ontology.v1.Query.Stratum:output_type -> zerone.ontology.v1.QueryStratumResponse
	5,  // 21: zerone.ontology.v1.Query.AllStrata:output_type -> zerone.ontology.v1.QueryAllStrataResponse
	7,  // 22: zerone.ontology.v1.Query.Domain:output_type -> zerone.ontology.v1.QueryDomainResponse
	9,  // 23: zerone.ontology.v1.Query.DomainsByStratum:output_type -> zerone.ontology.v1.QueryDomainsByStratumResponse
	11, // 24: zerone.ontology.v1.Query.AllDomains:output_type -> zerone.ontology.v1.QueryAllDomainsResponse
	13, // 25: zerone.ontology.v1.Query.Proposal:output_type -> zerone.ontology.v1.QueryProposalResponse
	15, // 26: zerone.ontology.v1.Query.ConfidenceCeiling:output_type -> zerone.ontology.v1.QueryConfidenceCeilingResponse
	17, // 27: zerone.ontology.v1.Query.LogicZone:output_type -> zerone.ontology.v1.QueryLogicZoneResponse
	19, // 28: zerone.ontology.v1.Query.AllLogicZones:output_type -> zerone.ontology.v1.QueryAllLogicZonesResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_zerone_ontology_v1_query_proto_init() }
func file_zerone_ontology_v1_query_proto_init() {
	if File_zerone_ontology_v1_query_proto != nil {
		return
	}
	file_zerone_ontology_v1_state_proto_init()
	file_zerone_ontology_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_ontology_v1_query_proto_rawDesc), len(file_zerone_ontology_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_ontology_v1_query_proto_goTypes,
		DependencyIndexes: file_zerone_ontology_v1_query_proto_depIdxs,
		MessageInfos:      file_zerone_ontology_v1_query_proto_msgTypes,
	}.Build()
	File_zerone_ontology_v1_query_proto = out.File
	file_zerone_ontology_v1_query_proto_goTypes = nil
	file_zerone_ontology_v1_query_proto_depIdxs = nil
}
