// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/ontology/v1/state.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StratumProperties defines the logical properties of a knowledge stratum.
type StratumProperties struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Stratum          uint32                 `protobuf:"varint,1,opt,name=stratum,proto3" json:"stratum,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Complete         bool                   `protobuf:"varint,4,opt,name=complete,proto3" json:"complete,omitempty"`                                        // Goedel: is the system complete?
	Decidable        bool                   `protobuf:"varint,5,opt,name=decidable,proto3" json:"decidable,omitempty"`                                      // is there an algorithm to decide all statements?
	GoedelApplies    bool                   `protobuf:"varint,6,opt,name=goedel_applies,json=goedelApplies,proto3" json:"goedel_applies,omitempty"`         // does Goedel's incompleteness apply?
	ConsistencyProof string                 `protobuf:"bytes,7,opt,name=consistency_proof,json=consistencyProof,proto3" json:"consistency_proof,omitempty"` // "internal", "assumed", "external"
	MaxConfidence    uint64                 `protobuf:"varint,8,opt,name=max_confidence,json=maxConfidence,proto3" json:"max_confidence,omitempty"`         // basis points (1000000 = 1.0)
	DecayRate        uint64                 `protobuf:"varint,9,opt,name=decay_rate,json=decayRate,proto3" json:"decay_rate,omitempty"`                     // confidence decay rate per day (basis points)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StratumProperties) Reset() {
	*x = StratumProperties{}
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StratumProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StratumProperties) ProtoMessage() {}

func (x *StratumProperties) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StratumProperties.ProtoReflect.Descriptor instead.
func (*StratumProperties) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *StratumProperties) GetStratum() uint32 {
	if x != nil {
		return x.Stratum
	}
	return 0
}

func (x *StratumProperties) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StratumProperties) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StratumProperties) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *StratumProperties) GetDecidable() bool {
	if x != nil {
		return x.Decidable
	}
	return false
}

func (x *StratumProperties) GetGoedelApplies() bool {
	if x != nil {
		return x.GoedelApplies
	}
	return false
}

func (x *StratumProperties) GetConsistencyProof() string {
	if x != nil {
		return x.ConsistencyProof
	}
	return ""
}

func (x *StratumProperties) GetMaxConfidence() uint64 {
	if x != nil {
		return x.MaxConfidence
	}
	return 0
}

func (x *StratumProperties) GetDecayRate() uint64 {
	if x != nil {
		return x.DecayRate
	}
	return 0
}

// Domain represents a knowledge domain within a stratum.
type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Stratum       uint32                 `protobuf:"varint,4,opt,name=stratum,proto3" json:"stratum,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                         // "active", "proposed", "deprecated"
	CreatedAt     uint64                 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // block height
	UpdatedAt     uint64                 `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // block height
	ClaimCount    uint64                 `protobuf:"varint,8,opt,name=claim_count,json=claimCount,proto3" json:"claim_count,omitempty"`
	FactCount     uint64                 `protobuf:"varint,9,opt,name=fact_count,json=factCount,proto3" json:"fact_count,omitempty"`
	ProposedBy    string                 `protobuf:"bytes,10,opt,name=proposed_by,json=proposedBy,proto3" json:"proposed_by,omitempty"`       // bech32 address
	ParentDomain  string                 `protobuf:"bytes,11,opt,name=parent_domain,json=parentDomain,proto3" json:"parent_domain,omitempty"` // empty = root domain
	Depth         uint32                 `protobuf:"varint,12,opt,name=depth,proto3" json:"depth,omitempty"`                                  // tree depth: root=1, child=parent.depth+1, max=5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Domain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Domain) GetStratum() uint32 {
	if x != nil {
		return x.Stratum
	}
	return 0
}

func (x *Domain) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Domain) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Domain) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Domain) GetClaimCount() uint64 {
	if x != nil {
		return x.ClaimCount
	}
	return 0
}

func (x *Domain) GetFactCount() uint64 {
	if x != nil {
		return x.FactCount
	}
	return 0
}

func (x *Domain) GetProposedBy() string {
	if x != nil {
		return x.ProposedBy
	}
	return ""
}

func (x *Domain) GetParentDomain() string {
	if x != nil {
		return x.ParentDomain
	}
	return ""
}

func (x *Domain) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// DomainProposal represents a proposal for adding or modifying domains.
type DomainProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        *Domain                `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Proposer      string                 `protobuf:"bytes,3,opt,name=proposer,proto3" json:"proposer,omitempty"`                             // bech32 address
	ProposalType  string                 `protobuf:"bytes,4,opt,name=proposal_type,json=proposalType,proto3" json:"proposal_type,omitempty"` // "add", "deprecate", "modify"
	Stake         string                 `protobuf:"bytes,5,opt,name=stake,proto3" json:"stake,omitempty"`                                   // bigint as string (uzrn)
	VotesFor      uint32                 `protobuf:"varint,6,opt,name=votes_for,json=votesFor,proto3" json:"votes_for,omitempty"`
	VotesAgainst  uint32                 `protobuf:"varint,7,opt,name=votes_against,json=votesAgainst,proto3" json:"votes_against,omitempty"`
	Voters        []string               `protobuf:"bytes,8,rep,name=voters,proto3" json:"voters,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                          // "active", "passed", "rejected", "expired"
	CreatedAt     uint64                 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // block height
	ExpiresAt     uint64                 `protobuf:"varint,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // block height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainProposal) Reset() {
	*x = DomainProposal{}
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainProposal) ProtoMessage() {}

func (x *DomainProposal) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainProposal.ProtoReflect.Descriptor instead.
func (*DomainProposal) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *DomainProposal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DomainProposal) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *DomainProposal) GetProposer() string {
	if x != nil {
		return x.Proposer
	}
	return ""
}

func (x *DomainProposal) GetProposalType() string {
	if x != nil {
		return x.ProposalType
	}
	return ""
}

func (x *DomainProposal) GetStake() string {
	if x != nil {
		return x.Stake
	}
	return ""
}

func (x *DomainProposal) GetVotesFor() uint32 {
	if x != nil {
		return x.VotesFor
	}
	return 0
}

func (x *DomainProposal) GetVotesAgainst() uint32 {
	if x != nil {
		return x.VotesAgainst
	}
	return 0
}

func (x *DomainProposal) GetVoters() []string {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *DomainProposal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DomainProposal) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DomainProposal) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// LogicZoneProperties defines the properties of a Godelian logic zone.
type LogicZoneProperties struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Zone             string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Complete         bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Decidable        bool                   `protobuf:"varint,3,opt,name=decidable,proto3" json:"decidable,omitempty"`
	GoedelApplies    bool                   `protobuf:"varint,4,opt,name=goedel_applies,json=goedelApplies,proto3" json:"goedel_applies,omitempty"`
	MaxConfidenceBps uint64                 `protobuf:"varint,5,opt,name=max_confidence_bps,json=maxConfidenceBps,proto3" json:"max_confidence_bps,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogicZoneProperties) Reset() {
	*x = LogicZoneProperties{}
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicZoneProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicZoneProperties) ProtoMessage() {}

func (x *LogicZoneProperties) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicZoneProperties.ProtoReflect.Descriptor instead.
func (*LogicZoneProperties) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *LogicZoneProperties) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *LogicZoneProperties) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *LogicZoneProperties) GetDecidable() bool {
	if x != nil {
		return x.Decidable
	}
	return false
}

func (x *LogicZoneProperties) GetGoedelApplies() bool {
	if x != nil {
		return x.GoedelApplies
	}
	return false
}

func (x *LogicZoneProperties) GetMaxConfidenceBps() uint64 {
	if x != nil {
		return x.MaxConfidenceBps
	}
	return 0
}

func (x *LogicZoneProperties) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CrossStratumLink represents a relationship between domains in different strata.
type CrossStratumLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceDomain  string                 `protobuf:"bytes,1,opt,name=source_domain,json=sourceDomain,proto3" json:"source_domain,omitempty"`
	TargetDomain  string                 `protobuf:"bytes,2,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	LinkType      string                 `protobuf:"bytes,3,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"` // "depends_on", "generalizes", "restricts"
	Discount      uint64                 `protobuf:"varint,4,opt,name=discount,proto3" json:"discount,omitempty"`                // confidence discount for cross-stratum references (basis points)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossStratumLink) Reset() {
	*x = CrossStratumLink{}
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossStratumLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossStratumLink) ProtoMessage() {}

func (x *CrossStratumLink) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ontology_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossStratumLink.ProtoReflect.Descriptor instead.
func (*CrossStratumLink) Descriptor() ([]byte, []int) {
	return file_zerone_ontology_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *CrossStratumLink) GetSourceDomain() string {
	if x != nil {
		return x.SourceDomain
	}
	return ""
}

func (x *CrossStratumLink) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

func (x *CrossStratumLink) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *CrossStratumLink) GetDiscount() uint64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

var File_zerone_ontology_v1_state_proto protoreflect.FileDescriptor

const file_zerone_ontology_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1ezerone/ontology/v1/state.proto\x12\x12zerone.ontology.v1\"\xb7\x02\n" +
	"\x11StratumProperties\x12\x18\n" +
	"\astratum\x18\x01 \x01(\rR\astratum\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcomplete\x18\x04 \x01(\bR\bcomplete\x12\x1c\n" +
	"\tdecidable\x18\x05 \x01(\bR\tdecidable\x12%\n" +
	"\x0egoedel_applies\x18\x06 \x01(\bR\rgoedelApplies\x12+\n" +
	"\x11consistency_proof\x18\a \x01(\tR\x10consistencyProof\x12%\n" +
	"\x0emax_confidence\x18\b \x01(\x04R\rmaxConfidence\x12\x1d\n" +
	"\n" +
	"decay_rate\x18\t \x01(\x04R\tdecayRate\"\xed\x02\n" +
	"\x06Domain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\astratum\x18\x04 \x01(\rR\astratum\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x04R\tupdatedAt\x12\x1f\n" +
	"\vclaim_count\x18\b \x01(\x04R\n" +
	"claimCount\x12\x1d\n" +
	"\n" +
	"fact_count\x18\t \x01(\x04R\tfactCount\x12\x1f\n" +
	"\vproposed_by\x18\n" +
	" \x01(\tR\n" +
	"proposedBy\x12#\n" +
	"\rparent_domain\x18\v \x01(\tR\fparentDomain\x12\x14\n" +
	"\x05depth\x18\f \x01(\rR\x05depth\"\xdb\x02\n" +
	"\x0eDomainProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06domain\x18\x02 \x01(\v2\x1a.zerone.ontology.v1.DomainR\x06domain\x12\x1a\n" +
	"\bproposer\x18\x03 \x01(\tR\bproposer\x12#\n" +
	"\rproposal_type\x18\x04 \x01(\tR\fproposalType\x12\x14\n" +
	"\x05stake\x18\x05 \x01(\tR\x05stake\x12\x1b\n" +
	"\tvotes_for\x18\x06 \x01(\rR\bvotesFor\x12#\n" +
	"\rvotes_against\x18\a \x01(\rR\fvotesAgainst\x12\x16\n" +
	"\x06voters\x18\b \x03(\tR\x06voters\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\x04R\texpiresAt\"\xda\x01\n" +
	"\x13LogicZoneProperties\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12\x1c\n" +
	"\tdecidable\x18\x03 \x01(\bR\tdecidable\x12%\n" +
	"\x0egoedel_applies\x18\x04 \x01(\bR\rgoedelApplies\x12,\n" +
	"\x12max_confidence_bps\x18\x05 \x01(\x04R\x10maxConfidenceBps\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x95\x01\n" +
	"\x10CrossStratumLink\x12#\n" +
	"\rsource_domain\x18\x01 \x01(\tR\fsourceDomain\x12#\n" +
	"\rtarget_domain\x18\x02 \x01(\tR\ftargetDomain\x12\x1b\n" +
	"\tlink_type\x18\x03 \x01(\tR\blinkType\x12\x1a\n" +
	"\bdiscount\x18\x04 \x01(\x04R\bdiscountB1Z/github.com/zerone-chain/zerone/x/ontology/typesb\x06proto3"

var (
	file_zerone_ontology_v1_state_proto_rawDescOnce sync.Once
	file_zerone_ontology_v1_state_proto_rawDescData []byte
)

func file_zerone_ontology_v1_state_proto_rawDescGZIP() []byte {
	file_zerone_ontology_v1_state_proto_rawDescOnce.Do(func() {
		file_zerone_ontology_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_ontology_v1_state_proto_rawDesc), len(file_zerone_ontology_v1_state_proto_rawDesc)))
	})
	return file_zerone_ontology_v1_state_proto_rawDescData
}

var file_zerone_ontology_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zerone_ontology_v1_state_proto_goTypes = []any{
	(*StratumProperties)(nil),   // 0: zerone.ontology.v1.StratumProperties
	(*Domain)(nil),              // 1: zerone.ontology.v1.Domain
	(*DomainProposal)(nil),      // 2: zerone.ontology.v1.DomainProposal
	(*LogicZoneProperties)(nil), // 3: zerone.ontology.v1.LogicZoneProperties
	(*CrossStratumLink)(nil),    // 4: zerone.ontology.v1.CrossStratumLink
}
var file_zerone_ontology_v1_state_proto_depIdxs = []int32{
	1, // 0: zerone.ontology.v1.DomainProposal.domain:type_name -> zerone.ontology.v1.Domain
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zerone_ontology_v1_state_proto_init() }
func file_zerone_ontology_v1_state_proto_init() {
	if File_zerone_ontology_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_ontology_v1_state_proto_rawDesc), len(file_zerone_ontology_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_ontology_v1_state_proto_goTypes,
		DependencyIndexes: file_zerone_ontology_v1_state_proto_depIdxs,
		MessageInfos:      file_zerone_ontology_v1_state_proto_msgTypes,
	}.Build()
	File_zerone_ontology_v1_state_proto = out.File
	file_zerone_ontology_v1_state_proto_goTypes = nil
	file_zerone_ontology_v1_state_proto_depIdxs = nil
}
