// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/staking/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgRegisterValidator registers a new validator.
type MsgRegisterValidator struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Operator        string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	ConsensusPubkey string                 `protobuf:"bytes,2,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty"`
	Did             string                 `protobuf:"bytes,3,opt,name=did,proto3" json:"did,omitempty"`
	Moniker         string                 `protobuf:"bytes,4,opt,name=moniker,proto3" json:"moniker,omitempty"`
	SelfDelegation  string                 `protobuf:"bytes,5,opt,name=self_delegation,json=selfDelegation,proto3" json:"self_delegation,omitempty"` // uzrn
	CommissionBps   uint64                 `protobuf:"varint,6,opt,name=commission_bps,json=commissionBps,proto3" json:"commission_bps,omitempty"`
	Website         string                 `protobuf:"bytes,7,opt,name=website,proto3" json:"website,omitempty"`
	Details         string                 `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgRegisterValidator) Reset() {
	*x = MsgRegisterValidator{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterValidator) ProtoMessage() {}

func (x *MsgRegisterValidator) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterValidator.ProtoReflect.Descriptor instead.
func (*MsgRegisterValidator) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgRegisterValidator) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *MsgRegisterValidator) GetConsensusPubkey() string {
	if x != nil {
		return x.ConsensusPubkey
	}
	return ""
}

func (x *MsgRegisterValidator) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *MsgRegisterValidator) GetMoniker() string {
	if x != nil {
		return x.Moniker
	}
	return ""
}

func (x *MsgRegisterValidator) GetSelfDelegation() string {
	if x != nil {
		return x.SelfDelegation
	}
	return ""
}

func (x *MsgRegisterValidator) GetCommissionBps() uint64 {
	if x != nil {
		return x.CommissionBps
	}
	return 0
}

func (x *MsgRegisterValidator) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *MsgRegisterValidator) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type MsgRegisterValidatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialTier   uint32                 `protobuf:"varint,1,opt,name=initial_tier,json=initialTier,proto3" json:"initial_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterValidatorResponse) Reset() {
	*x = MsgRegisterValidatorResponse{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterValidatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterValidatorResponse) ProtoMessage() {}

func (x *MsgRegisterValidatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterValidatorResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterValidatorResponse) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgRegisterValidatorResponse) GetInitialTier() uint32 {
	if x != nil {
		return x.InitialTier
	}
	return 0
}

// MsgDelegate delegates tokens to a validator.
type MsgDelegate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegator     string                 `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	Validator     string                 `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // uzrn
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDelegate) Reset() {
	*x = MsgDelegate{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegate) ProtoMessage() {}

func (x *MsgDelegate) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegate.ProtoReflect.Descriptor instead.
func (*MsgDelegate) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgDelegate) GetDelegator() string {
	if x != nil {
		return x.Delegator
	}
	return ""
}

func (x *MsgDelegate) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgDelegate) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgDelegateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewDelegation string                 `protobuf:"bytes,1,opt,name=new_delegation,json=newDelegation,proto3" json:"new_delegation,omitempty"` // total delegation after operation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDelegateResponse) Reset() {
	*x = MsgDelegateResponse{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegateResponse) ProtoMessage() {}

func (x *MsgDelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegateResponse.ProtoReflect.Descriptor instead.
func (*MsgDelegateResponse) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgDelegateResponse) GetNewDelegation() string {
	if x != nil {
		return x.NewDelegation
	}
	return ""
}

// MsgUndelegate initiates unbonding from a validator.
type MsgUndelegate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegator     string                 `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	Validator     string                 `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // uzrn
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUndelegate) Reset() {
	*x = MsgUndelegate{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUndelegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUndelegate) ProtoMessage() {}

func (x *MsgUndelegate) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUndelegate.ProtoReflect.Descriptor instead.
func (*MsgUndelegate) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgUndelegate) GetDelegator() string {
	if x != nil {
		return x.Delegator
	}
	return ""
}

func (x *MsgUndelegate) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgUndelegate) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgUndelegateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UnbondingId       string                 `protobuf:"bytes,1,opt,name=unbonding_id,json=unbondingId,proto3" json:"unbonding_id,omitempty"`
	CompletesAtHeight uint64                 `protobuf:"varint,2,opt,name=completes_at_height,json=completesAtHeight,proto3" json:"completes_at_height,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgUndelegateResponse) Reset() {
	*x = MsgUndelegateResponse{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUndelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUndelegateResponse) ProtoMessage() {}

func (x *MsgUndelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUndelegateResponse.ProtoReflect.Descriptor instead.
func (*MsgUndelegateResponse) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgUndelegateResponse) GetUnbondingId() string {
	if x != nil {
		return x.UnbondingId
	}
	return ""
}

func (x *MsgUndelegateResponse) GetCompletesAtHeight() uint64 {
	if x != nil {
		return x.CompletesAtHeight
	}
	return 0
}

// MsgRedelegate moves delegation between validators.
type MsgRedelegate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegator     string                 `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	SrcValidator  string                 `protobuf:"bytes,2,opt,name=src_validator,json=srcValidator,proto3" json:"src_validator,omitempty"`
	DstValidator  string                 `protobuf:"bytes,3,opt,name=dst_validator,json=dstValidator,proto3" json:"dst_validator,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"` // uzrn
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRedelegate) Reset() {
	*x = MsgRedelegate{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRedelegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRedelegate) ProtoMessage() {}

func (x *MsgRedelegate) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRedelegate.ProtoReflect.Descriptor instead.
func (*MsgRedelegate) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgRedelegate) GetDelegator() string {
	if x != nil {
		return x.Delegator
	}
	return ""
}

func (x *MsgRedelegate) GetSrcValidator() string {
	if x != nil {
		return x.SrcValidator
	}
	return ""
}

func (x *MsgRedelegate) GetDstValidator() string {
	if x != nil {
		return x.DstValidator
	}
	return ""
}

func (x *MsgRedelegate) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgRedelegateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRedelegateResponse) Reset() {
	*x = MsgRedelegateResponse{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRedelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRedelegateResponse) ProtoMessage() {}

func (x *MsgRedelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRedelegateResponse.ProtoReflect.Descriptor instead.
func (*MsgRedelegateResponse) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{7}
}

// MsgUpdateValidatorStake increases or decreases self-delegation.
type MsgUpdateValidatorStake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // uzrn
	Increase      bool                   `protobuf:"varint,3,opt,name=increase,proto3" json:"increase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateValidatorStake) Reset() {
	*x = MsgUpdateValidatorStake{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateValidatorStake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateValidatorStake) ProtoMessage() {}

func (x *MsgUpdateValidatorStake) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateValidatorStake.ProtoReflect.Descriptor instead.
func (*MsgUpdateValidatorStake) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgUpdateValidatorStake) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *MsgUpdateValidatorStake) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgUpdateValidatorStake) GetIncrease() bool {
	if x != nil {
		return x.Increase
	}
	return false
}

type MsgUpdateValidatorStakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateValidatorStakeResponse) Reset() {
	*x = MsgUpdateValidatorStakeResponse{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateValidatorStakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateValidatorStakeResponse) ProtoMessage() {}

func (x *MsgUpdateValidatorStakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateValidatorStakeResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateValidatorStakeResponse) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{9}
}

// MsgUpdateParams updates module parameters (governance-gated).
type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_staking_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_staking_v1_tx_proto_rawDescGZIP(), []int{11}
}

var File_zerone_staking_v1_tx_proto protoreflect.FileDescriptor

const file_zerone_staking_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1azerone/staking/v1/tx.proto\x12\x11zerone.staking.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x1dzerone/staking/v1/types.proto\x1a\x1fzerone/staking/v1/genesis.proto\"\x9c\x02\n" +
	"\x14MsgRegisterValidator\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12)\n" +
	"\x10consensus_pubkey\x18\x02 \x01(\tR\x0fconsensusPubkey\x12\x10\n" +
	"\x03did\x18\x03 \x01(\tR\x03did\x12\x18\n" +
	"\amoniker\x18\x04 \x01(\tR\amoniker\x12'\n" +
	"\x0fself_delegation\x18\x05 \x01(\tR\x0eselfDelegation\x12%\n" +
	"\x0ecommission_bps\x18\x06 \x01(\x04R\rcommissionBps\x12\x18\n" +
	"\awebsite\x18\a \x01(\tR\awebsite\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails:\r\x82\xe7\xb0*\boperator\"A\n" +
	"\x1cMsgRegisterValidatorResponse\x12!\n" +
	"\finitial_tier\x18\x01 \x01(\rR\vinitialTier\"q\n" +
	"\vMsgDelegate\x12\x1c\n" +
	"\tdelegator\x18\x01 \x01(\tR\tdelegator\x12\x1c\n" +
	"\tvalidator\x18\x02 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount:\x0e\x82\xe7\xb0*\tdelegator\"<\n" +
	"\x13MsgDelegateResponse\x12%\n" +
	"\x0enew_delegation\x18\x01 \x01(\tR\rnewDelegation\"s\n" +
	"\rMsgUndelegate\x12\x1c\n" +
	"\tdelegator\x18\x01 \x01(\tR\tdelegator\x12\x1c\n" +
	"\tvalidator\x18\x02 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount:\x0e\x82\xe7\xb0*\tdelegator\"j\n" +
	"\x15MsgUndelegateResponse\x12!\n" +
	"\funbonding_id\x18\x01 \x01(\tR\vunbondingId\x12.\n" +
	"\x13completes_at_height\x18\x02 \x01(\x04R\x11completesAtHeight\"\x9f\x01\n" +
	"\rMsgRedelegate\x12\x1c\n" +
	"\tdelegator\x18\x01 \x01(\tR\tdelegator\x12#\n" +
	"\rsrc_validator\x18\x02 \x01(\tR\fsrcValidator\x12#\n" +
	"\rdst_validator\x18\x03 \x01(\tR\fdstValidator\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount:\x0e\x82\xe7\xb0*\tdelegator\"\x17\n" +
	"\x15MsgRedelegateResponse\"x\n" +
	"\x17MsgUpdateValidatorStake\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1a\n" +
	"\bincrease\x18\x03 \x01(\bR\bincrease:\r\x82\xe7\xb0*\boperator\"!\n" +
	"\x1fMsgUpdateValidatorStakeResponse\"r\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x121\n" +
	"\x06params\x18\x02 \x01(\v2\x19.zerone.staking.v1.ParamsR\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\xdb\x04\n" +
	"\x03Msg\x12m\n" +
	"\x11RegisterValidator\x12'.zerone.staking.v1.MsgRegisterValidator\x1a/.zerone.staking.v1.MsgRegisterValidatorResponse\x12R\n" +
	"\bDelegate\x12\x1e.zerone.staking.v1.MsgDelegate\x1a&.zerone.staking.v1.MsgDelegateResponse\x12X\n" +
	"\n" +
	"Undelegate\x12 .zerone.staking.v1.MsgUndelegate\x1a(.zerone.staking.v1.MsgUndelegateResponse\x12X\n" +
	"\n" +
	"Redelegate\x12 .zerone.staking.v1.MsgRedelegate\x1a(.zerone.staking.v1.MsgRedelegateResponse\x12v\n" +
	"\x14UpdateValidatorStake\x12*.zerone.staking.v1.MsgUpdateValidatorStake\x1a2.zerone.staking.v1.MsgUpdateValidatorStakeResponse\x12^\n" +
	"\fUpdateParams\x12\".zerone.staking.v1.MsgUpdateParams\x1a*.zerone.staking.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B0Z.github.com/zerone-chain/zerone/x/staking/typesb\x06proto3"

var (
	file_zerone_staking_v1_tx_proto_rawDescOnce sync.Once
	file_zerone_staking_v1_tx_proto_rawDescData []byte
)

func file_zerone_staking_v1_tx_proto_rawDescGZIP() []byte {
	file_zerone_staking_v1_tx_proto_rawDescOnce.Do(func() {
		file_zerone_staking_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_staking_v1_tx_proto_rawDesc), len(file_zerone_staking_v1_tx_proto_rawDesc)))
	})
	return file_zerone_staking_v1_tx_proto_rawDescData
}

var file_zerone_staking_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_zerone_staking_v1_tx_proto_goTypes = []any{
	(*MsgRegisterValidator)(nil),            // 0: zerone.staking.v1.MsgRegisterValidator
	(*MsgRegisterValidatorResponse)(nil),    // 1: zerone.staking.v1.MsgRegisterValidatorResponse
	(*MsgDelegate)(nil),                     // 2: zerone.staking.v1.MsgDelegate
	(*MsgDelegateResponse)(nil),             // 3: zerone.staking.v1.MsgDelegateResponse
	(*MsgUndelegate)(nil),                   // 4: zerone.staking.v1.MsgUndelegate
	(*MsgUndelegateResponse)(nil),           // 5: zerone.staking.v1.MsgUndelegateResponse
	(*MsgRedelegate)(nil),                   // 6: zerone.staking.v1.MsgRedelegate
	(*MsgRedelegateResponse)(nil),           // 7: zerone.staking.v1.MsgRedelegateResponse
	(*MsgUpdateValidatorStake)(nil),         // 8: zerone.staking.v1.MsgUpdateValidatorStake
	(*MsgUpdateValidatorStakeResponse)(nil), // 9: zerone.staking.v1.MsgUpdateValidatorStakeResponse
	(*MsgUpdateParams)(nil),                 // 10: zerone.staking.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),         // 11: zerone.staking.v1.MsgUpdateParamsResponse
	(*Params)(nil),                          // 12: zerone.staking.v1.Params
}
var file_zerone_staking_v1_tx_proto_depIdxs = []int32{
	12, // 0: zerone.staking.v1.MsgUpdateParams.params:type_name -> zerone.staking.v1.Params
	0,  // 1: zerone.staking.v1.Msg.RegisterValidator:input_type -> zerone.staking.v1.MsgRegisterValidator
	2,  // 2: zerone.staking.v1.Msg.Delegate:input_type -> zerone.staking.v1.MsgDelegate
	4,  // 3: zerone.staking.v1.Msg.Undelegate:input_type -> zerone.staking.v1.MsgUndelegate
	6,  // 4: zerone.staking.v1.Msg.Redelegate:input_type -> zerone.staking.v1.MsgRedelegate
	8,  // 5: zerone.staking.v1.Msg.UpdateValidatorStake:input_type -> zerone.staking.v1.MsgUpdateValidatorStake
	10, // 6: zerone.staking.v1.Msg.UpdateParams:input_type -> zerone.staking.v1.MsgUpdateParams
	1,  // 7: zerone.staking.v1.Msg.RegisterValidator:output_type -> zerone.staking.v1.MsgRegisterValidatorResponse
	3,  // 8: zerone.staking.v1.Msg.Delegate:output_type -> zerone.staking.v1.MsgDelegateResponse
	5,  // 9: zerone.staking.v1.Msg.Undelegate:output_type -> zerone.staking.v1.MsgUndelegateResponse
	7,  // 10: zerone.staking.v1.Msg.Redelegate:output_type -> zerone.staking.v1.MsgRedelegateResponse
	9,  // 11: zerone.staking.v1.Msg.UpdateValidatorStake:output_type -> zerone.staking.v1.MsgUpdateValidatorStakeResponse
	11, // 12: zerone.staking.v1.Msg.UpdateParams:output_type -> zerone.staking.v1.MsgUpdateParamsResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_zerone_staking_v1_tx_proto_init() }
func file_zerone_staking_v1_tx_proto_init() {
	if File_zerone_staking_v1_tx_proto != nil {
		return
	}
	file_zerone_staking_v1_types_proto_init()
	file_zerone_staking_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_staking_v1_tx_proto_rawDesc), len(file_zerone_staking_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_staking_v1_tx_proto_goTypes,
		DependencyIndexes: file_zerone_staking_v1_tx_proto_depIdxs,
		MessageInfos:      file_zerone_staking_v1_tx_proto_msgTypes,
	}.Build()
	File_zerone_staking_v1_tx_proto = out.File
	file_zerone_staking_v1_tx_proto_goTypes = nil
	file_zerone_staking_v1_tx_proto_depIdxs = nil
}
