// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/governance_synthesis/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuerySystemHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySystemHealthRequest) Reset() {
	*x = QuerySystemHealthRequest{}
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySystemHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySystemHealthRequest) ProtoMessage() {}

func (x *QuerySystemHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySystemHealthRequest.ProtoReflect.Descriptor instead.
func (*QuerySystemHealthRequest) Descriptor() ([]byte, []int) {
	return file_zerone_governance_synthesis_v1_query_proto_rawDescGZIP(), []int{0}
}

type QuerySystemHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *SystemHealth          `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySystemHealthResponse) Reset() {
	*x = QuerySystemHealthResponse{}
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySystemHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySystemHealthResponse) ProtoMessage() {}

func (x *QuerySystemHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySystemHealthResponse.ProtoReflect.Descriptor instead.
func (*QuerySystemHealthResponse) Descriptor() ([]byte, []int) {
	return file_zerone_governance_synthesis_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QuerySystemHealthResponse) GetHealth() *SystemHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type QueryFrontierRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum domains to return. 0 = all. Capped at synthesizer's
	// internal limit (default 100).
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFrontierRequest) Reset() {
	*x = QueryFrontierRequest{}
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFrontierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFrontierRequest) ProtoMessage() {}

func (x *QueryFrontierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFrontierRequest.ProtoReflect.Descriptor instead.
func (*QueryFrontierRequest) Descriptor() ([]byte, []int) {
	return file_zerone_governance_synthesis_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryFrontierRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryFrontierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontier      *Frontier              `protobuf:"bytes,1,opt,name=frontier,proto3" json:"frontier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFrontierResponse) Reset() {
	*x = QueryFrontierResponse{}
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFrontierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFrontierResponse) ProtoMessage() {}

func (x *QueryFrontierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFrontierResponse.ProtoReflect.Descriptor instead.
func (*QueryFrontierResponse) Descriptor() ([]byte, []int) {
	return file_zerone_governance_synthesis_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryFrontierResponse) GetFrontier() *Frontier {
	if x != nil {
		return x.Frontier
	}
	return nil
}

type QueryCreedDriftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCreedDriftRequest) Reset() {
	*x = QueryCreedDriftRequest{}
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCreedDriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCreedDriftRequest) ProtoMessage() {}

func (x *QueryCreedDriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCreedDriftRequest.ProtoReflect.Descriptor instead.
func (*QueryCreedDriftRequest) Descriptor() ([]byte, []int) {
	return file_zerone_governance_synthesis_v1_query_proto_rawDescGZIP(), []int{4}
}

type QueryCreedDriftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drift         *CreedDrift            `protobuf:"bytes,1,opt,name=drift,proto3" json:"drift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCreedDriftResponse) Reset() {
	*x = QueryCreedDriftResponse{}
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCreedDriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCreedDriftResponse) ProtoMessage() {}

func (x *QueryCreedDriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_governance_synthesis_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCreedDriftResponse.ProtoReflect.Descriptor instead.
func (*QueryCreedDriftResponse) Descriptor() ([]byte, []int) {
	return file_zerone_governance_synthesis_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryCreedDriftResponse) GetDrift() *CreedDrift {
	if x != nil {
		return x.Drift
	}
	return nil
}

var File_zerone_governance_synthesis_v1_query_proto protoreflect.FileDescriptor

const file_zerone_governance_synthesis_v1_query_proto_rawDesc = "" +
	"\n" +
	"*zerone/governance_synthesis/v1/query.proto\x12\x1ezerone.governance_synthesis.v1\x1a\x1cgoogle/api/annotations.proto\x1a*zerone/governance_synthesis/v1/types.proto\"\x1a\n" +
	"\x18QuerySystemHealthRequest\"a\n" +
	"\x19QuerySystemHealthResponse\x12D\n" +
	"\x06health\x18\x01 \x01(\v2,.zerone.governance_synthesis.v1.SystemHealthR\x06health\",\n" +
	"\x14QueryFrontierRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"]\n" +
	"\x15QueryFrontierResponse\x12D\n" +
	"\bfrontier\x18\x01 \x01(\v2(.zerone.governance_synthesis.v1.FrontierR\bfrontier\"\x18\n" +
	"\x16QueryCreedDriftRequest\"[\n" +
	"\x17QueryCreedDriftResponse\x12@\n" +
	"\x05drift\x18\x01 \x01(\v2*.zerone.governance_synthesis.v1.CreedDriftR\x05drift2\xa5\x04\n" +
	"\x05Query\x12\xba\x01\n" +
	"\fSystemHealth\x128.zerone.governance_synthesis.v1.QuerySystemHealthRequest\x1a9.zerone.governance_synthesis.v1.QuerySystemHealthResponse\"5\x82\xd3\xe4\x93\x02/\x12-/zerone/governance_synthesis/v1/system_health\x12\xa9\x01\n" +
	"\bFrontier\x124.zerone.governance_synthesis.v1.QueryFrontierRequest\x1a5.zerone.governance_synthesis.v1.QueryFrontierResponse\"0\x82\xd3\xe4\x93\x02*\x12(/zerone/governance_synthesis/v1/frontier\x12\xb2\x01\n" +
	"\n" +
	"CreedDrift\x126.zerone.governance_synthesis.v1.QueryCreedDriftRequest\x1a7.zerone.governance_synthesis.v1.QueryCreedDriftResponse\"3\x82\xd3\xe4\x93\x02-\x12+/zerone/governance_synthesis/v1/creed_driftB=Z;github.com/zerone-chain/zerone/x/governance_synthesis/typesb\x06proto3"

var (
	file_zerone_governance_synthesis_v1_query_proto_rawDescOnce sync.Once
	file_zerone_governance_synthesis_v1_query_proto_rawDescData []byte
)

func file_zerone_governance_synthesis_v1_query_proto_rawDescGZIP() []byte {
	file_zerone_governance_synthesis_v1_query_proto_rawDescOnce.Do(func() {
		file_zerone_governance_synthesis_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_governance_synthesis_v1_query_proto_rawDesc), len(file_zerone_governance_synthesis_v1_query_proto_rawDesc)))
	})
	return file_zerone_governance_synthesis_v1_query_proto_rawDescData
}

var file_zerone_governance_synthesis_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zerone_governance_synthesis_v1_query_proto_goTypes = []any{
	(*QuerySystemHealthRequest)(nil),  // 0: zerone.governance_synthesis.v1.QuerySystemHealthRequest
	(*QuerySystemHealthResponse)(nil), // 1: zerone.governance_synthesis.v1.QuerySystemHealthResponse
	(*QueryFrontierRequest)(nil),      // 2: zerone.governance_synthesis.v1.QueryFrontierRequest
	(*QueryFrontierResponse)(nil),     // 3: zerone.governance_synthesis.v1.QueryFrontierResponse
	(*QueryCreedDriftRequest)(nil),    // 4: zerone.governance_synthesis.v1.QueryCreedDriftRequest
	(*QueryCreedDriftResponse)(nil),   // 5: zerone.governance_synthesis.v1.QueryCreedDriftResponse
	(*SystemHealth)(nil),              // 6: zerone.governance_synthesis.v1.SystemHealth
	(*Frontier)(nil),                  // 7: zerone.governance_synthesis.v1.Frontier
	(*CreedDrift)(nil),                // 8: zerone.governance_synthesis.v1.CreedDrift
}
var file_zerone_governance_synthesis_v1_query_proto_depIdxs = []int32{
	6, // 0: zerone.governance_synthesis.v1.QuerySystemHealthResponse.health:type_name -> zerone.governance_synthesis.v1.SystemHealth
	7, // 1: zerone.governance_synthesis.v1.QueryFrontierResponse.frontier:type_name -> zerone.governance_synthesis.v1.Frontier
	8, // 2: zerone.governance_synthesis.v1.QueryCreedDriftResponse.drift:type_name -> zerone.governance_synthesis.v1.CreedDrift
	0, // 3: zerone.governance_synthesis.v1.Query.SystemHealth:input_type -> zerone.governance_synthesis.v1.QuerySystemHealthRequest
	2, // 4: zerone.governance_synthesis.v1.Query.Frontier:input_type -> zerone.governance_synthesis.v1.QueryFrontierRequest
	4, // 5: zerone.governance_synthesis.v1.Query.CreedDrift:input_type -> zerone.governance_synthesis.v1.QueryCreedDriftRequest
	1, // 6: zerone.governance_synthesis.v1.Query.SystemHealth:output_type -> zerone.governance_synthesis.v1.QuerySystemHealthResponse
	3, // 7: zerone.governance_synthesis.v1.Query.Frontier:output_type -> zerone.governance_synthesis.v1.QueryFrontierResponse
	5, // 8: zerone.governance_synthesis.v1.Query.CreedDrift:output_type -> zerone.governance_synthesis.v1.QueryCreedDriftResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zerone_governance_synthesis_v1_query_proto_init() }
func file_zerone_governance_synthesis_v1_query_proto_init() {
	if File_zerone_governance_synthesis_v1_query_proto != nil {
		return
	}
	file_zerone_governance_synthesis_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_governance_synthesis_v1_query_proto_rawDesc), len(file_zerone_governance_synthesis_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_governance_synthesis_v1_query_proto_goTypes,
		DependencyIndexes: file_zerone_governance_synthesis_v1_query_proto_depIdxs,
		MessageInfos:      file_zerone_governance_synthesis_v1_query_proto_msgTypes,
	}.Build()
	File_zerone_governance_synthesis_v1_query_proto = out.File
	file_zerone_governance_synthesis_v1_query_proto_goTypes = nil
	file_zerone_governance_synthesis_v1_query_proto_depIdxs = nil
}
