// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/tokens/v1/query.proto

package types

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryTokenConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTokenConfigRequest) Reset() {
	*x = QueryTokenConfigRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTokenConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTokenConfigRequest) ProtoMessage() {}

func (x *QueryTokenConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTokenConfigRequest.ProtoReflect.Descriptor instead.
func (*QueryTokenConfigRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryTokenConfigRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type QueryTokenConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *TokenDefinition       `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTokenConfigResponse) Reset() {
	*x = QueryTokenConfigResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTokenConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTokenConfigResponse) ProtoMessage() {}

func (x *QueryTokenConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTokenConfigResponse.ProtoReflect.Descriptor instead.
func (*QueryTokenConfigResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryTokenConfigResponse) GetToken() *TokenDefinition {
	if x != nil {
		return x.Token
	}
	return nil
}

type QueryTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTokensRequest) Reset() {
	*x = QueryTokensRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTokensRequest) ProtoMessage() {}

func (x *QueryTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTokensRequest.ProtoReflect.Descriptor instead.
func (*QueryTokensRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryTokensRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenDefinition     `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTokensResponse) Reset() {
	*x = QueryTokensResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTokensResponse) ProtoMessage() {}

func (x *QueryTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTokensResponse.ProtoReflect.Descriptor instead.
func (*QueryTokensResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryTokensResponse) GetTokens() []*TokenDefinition {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *QueryTokensResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryTokenBySymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTokenBySymbolRequest) Reset() {
	*x = QueryTokenBySymbolRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTokenBySymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTokenBySymbolRequest) ProtoMessage() {}

func (x *QueryTokenBySymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTokenBySymbolRequest.ProtoReflect.Descriptor instead.
func (*QueryTokenBySymbolRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryTokenBySymbolRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type QueryTokenBySymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *TokenDefinition       `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTokenBySymbolResponse) Reset() {
	*x = QueryTokenBySymbolResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTokenBySymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTokenBySymbolResponse) ProtoMessage() {}

func (x *QueryTokenBySymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTokenBySymbolResponse.ProtoReflect.Descriptor instead.
func (*QueryTokenBySymbolResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryTokenBySymbolResponse) GetToken() *TokenDefinition {
	if x != nil {
		return x.Token
	}
	return nil
}

type QueryBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBalanceRequest) Reset() {
	*x = QueryBalanceRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBalanceRequest) ProtoMessage() {}

func (x *QueryBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBalanceRequest.ProtoReflect.Descriptor instead.
func (*QueryBalanceRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryBalanceRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *QueryBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type QueryBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBalanceResponse) Reset() {
	*x = QueryBalanceResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBalanceResponse) ProtoMessage() {}

func (x *QueryBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBalanceResponse.ProtoReflect.Descriptor instead.
func (*QueryBalanceResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type QueryTotalSupplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalSupplyRequest) Reset() {
	*x = QueryTotalSupplyRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalSupplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalSupplyRequest) ProtoMessage() {}

func (x *QueryTotalSupplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalSupplyRequest.ProtoReflect.Descriptor instead.
func (*QueryTotalSupplyRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryTotalSupplyRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type QueryTotalSupplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSupply   string                 `protobuf:"bytes,1,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	MaxSupply     string                 `protobuf:"bytes,2,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	Minted        string                 `protobuf:"bytes,3,opt,name=minted,proto3" json:"minted,omitempty"`
	Burned        string                 `protobuf:"bytes,4,opt,name=burned,proto3" json:"burned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalSupplyResponse) Reset() {
	*x = QueryTotalSupplyResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalSupplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalSupplyResponse) ProtoMessage() {}

func (x *QueryTotalSupplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalSupplyResponse.ProtoReflect.Descriptor instead.
func (*QueryTotalSupplyResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryTotalSupplyResponse) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *QueryTotalSupplyResponse) GetMaxSupply() string {
	if x != nil {
		return x.MaxSupply
	}
	return ""
}

func (x *QueryTotalSupplyResponse) GetMinted() string {
	if x != nil {
		return x.Minted
	}
	return ""
}

func (x *QueryTotalSupplyResponse) GetBurned() string {
	if x != nil {
		return x.Burned
	}
	return ""
}

type QueryAllowanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender       string                 `protobuf:"bytes,3,opt,name=spender,proto3" json:"spender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllowanceRequest) Reset() {
	*x = QueryAllowanceRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllowanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllowanceRequest) ProtoMessage() {}

func (x *QueryAllowanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllowanceRequest.ProtoReflect.Descriptor instead.
func (*QueryAllowanceRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryAllowanceRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *QueryAllowanceRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *QueryAllowanceRequest) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

type QueryAllowanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowance     string                 `protobuf:"bytes,1,opt,name=allowance,proto3" json:"allowance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllowanceResponse) Reset() {
	*x = QueryAllowanceResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllowanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllowanceResponse) ProtoMessage() {}

func (x *QueryAllowanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllowanceResponse.ProtoReflect.Descriptor instead.
func (*QueryAllowanceResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryAllowanceResponse) GetAllowance() string {
	if x != nil {
		return x.Allowance
	}
	return ""
}

type QueryDelegatedPowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDelegatedPowerRequest) Reset() {
	*x = QueryDelegatedPowerRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDelegatedPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDelegatedPowerRequest) ProtoMessage() {}

func (x *QueryDelegatedPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDelegatedPowerRequest.ProtoReflect.Descriptor instead.
func (*QueryDelegatedPowerRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QueryDelegatedPowerRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *QueryDelegatedPowerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type QueryDelegatedPowerResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DelegatedTotal     string                 `protobuf:"bytes,1,opt,name=delegated_total,json=delegatedTotal,proto3" json:"delegated_total,omitempty"`             // total power this address has delegated away
	ReceivedTotal      string                 `protobuf:"bytes,2,opt,name=received_total,json=receivedTotal,proto3" json:"received_total,omitempty"`                // total power this address has received
	UndelegatedBalance string                 `protobuf:"bytes,3,opt,name=undelegated_balance,json=undelegatedBalance,proto3" json:"undelegated_balance,omitempty"` // balance - delegated_total
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryDelegatedPowerResponse) Reset() {
	*x = QueryDelegatedPowerResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDelegatedPowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDelegatedPowerResponse) ProtoMessage() {}

func (x *QueryDelegatedPowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDelegatedPowerResponse.ProtoReflect.Descriptor instead.
func (*QueryDelegatedPowerResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *QueryDelegatedPowerResponse) GetDelegatedTotal() string {
	if x != nil {
		return x.DelegatedTotal
	}
	return ""
}

func (x *QueryDelegatedPowerResponse) GetReceivedTotal() string {
	if x != nil {
		return x.ReceivedTotal
	}
	return ""
}

func (x *QueryDelegatedPowerResponse) GetUndelegatedBalance() string {
	if x != nil {
		return x.UndelegatedBalance
	}
	return ""
}

type QueryWrappedTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWrappedTokenRequest) Reset() {
	*x = QueryWrappedTokenRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWrappedTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWrappedTokenRequest) ProtoMessage() {}

func (x *QueryWrappedTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWrappedTokenRequest.ProtoReflect.Descriptor instead.
func (*QueryWrappedTokenRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryWrappedTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type QueryWrappedTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	WrappedDenom  string                 `protobuf:"bytes,2,opt,name=wrapped_denom,json=wrappedDenom,proto3" json:"wrapped_denom,omitempty"`
	TotalWrapped  string                 `protobuf:"bytes,3,opt,name=total_wrapped,json=totalWrapped,proto3" json:"total_wrapped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWrappedTokenResponse) Reset() {
	*x = QueryWrappedTokenResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWrappedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWrappedTokenResponse) ProtoMessage() {}

func (x *QueryWrappedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWrappedTokenResponse.ProtoReflect.Descriptor instead.
func (*QueryWrappedTokenResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryWrappedTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *QueryWrappedTokenResponse) GetWrappedDenom() string {
	if x != nil {
		return x.WrappedDenom
	}
	return ""
}

func (x *QueryWrappedTokenResponse) GetTotalWrapped() string {
	if x != nil {
		return x.TotalWrapped
	}
	return ""
}

type QueryWrappedTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWrappedTokensRequest) Reset() {
	*x = QueryWrappedTokensRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWrappedTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWrappedTokensRequest) ProtoMessage() {}

func (x *QueryWrappedTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWrappedTokensRequest.ProtoReflect.Descriptor instead.
func (*QueryWrappedTokensRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{18}
}

func (x *QueryWrappedTokensRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryWrappedTokensResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Records       []*QueryWrappedTokenResponse `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Pagination    *query.PageResponse          `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWrappedTokensResponse) Reset() {
	*x = QueryWrappedTokensResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWrappedTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWrappedTokensResponse) ProtoMessage() {}

func (x *QueryWrappedTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWrappedTokensResponse.ProtoReflect.Descriptor instead.
func (*QueryWrappedTokensResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{19}
}

func (x *QueryWrappedTokensResponse) GetRecords() []*QueryWrappedTokenResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryWrappedTokensResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryEmissionPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmissionId    string                 `protobuf:"bytes,1,opt,name=emission_id,json=emissionId,proto3" json:"emission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEmissionPeriodRequest) Reset() {
	*x = QueryEmissionPeriodRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEmissionPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEmissionPeriodRequest) ProtoMessage() {}

func (x *QueryEmissionPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEmissionPeriodRequest.ProtoReflect.Descriptor instead.
func (*QueryEmissionPeriodRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{20}
}

func (x *QueryEmissionPeriodRequest) GetEmissionId() string {
	if x != nil {
		return x.EmissionId
	}
	return ""
}

type QueryEmissionPeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emission      *EmissionPeriod        `protobuf:"bytes,1,opt,name=emission,proto3" json:"emission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEmissionPeriodResponse) Reset() {
	*x = QueryEmissionPeriodResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEmissionPeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEmissionPeriodResponse) ProtoMessage() {}

func (x *QueryEmissionPeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEmissionPeriodResponse.ProtoReflect.Descriptor instead.
func (*QueryEmissionPeriodResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{21}
}

func (x *QueryEmissionPeriodResponse) GetEmission() *EmissionPeriod {
	if x != nil {
		return x.Emission
	}
	return nil
}

type QueryEmissionPeriodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Pagination    *query.PageRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEmissionPeriodsRequest) Reset() {
	*x = QueryEmissionPeriodsRequest{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEmissionPeriodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEmissionPeriodsRequest) ProtoMessage() {}

func (x *QueryEmissionPeriodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEmissionPeriodsRequest.ProtoReflect.Descriptor instead.
func (*QueryEmissionPeriodsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{22}
}

func (x *QueryEmissionPeriodsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *QueryEmissionPeriodsRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryEmissionPeriodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emissions     []*EmissionPeriod      `protobuf:"bytes,1,rep,name=emissions,proto3" json:"emissions,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEmissionPeriodsResponse) Reset() {
	*x = QueryEmissionPeriodsResponse{}
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEmissionPeriodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEmissionPeriodsResponse) ProtoMessage() {}

func (x *QueryEmissionPeriodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_query_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEmissionPeriodsResponse.ProtoReflect.Descriptor instead.
func (*QueryEmissionPeriodsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_query_proto_rawDescGZIP(), []int{23}
}

func (x *QueryEmissionPeriodsResponse) GetEmissions() []*EmissionPeriod {
	if x != nil {
		return x.Emissions
	}
	return nil
}

func (x *QueryEmissionPeriodsResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_zerone_tokens_v1_query_proto protoreflect.FileDescriptor

const file_zerone_tokens_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1czerone/tokens/v1/query.proto\x12\x10zerone.tokens.v1\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1czerone/tokens/v1/types.proto\x1a\x1ezerone/tokens/v1/genesis.proto\"\x14\n" +
	"\x12QueryParamsRequest\"G\n" +
	"\x13QueryParamsResponse\x120\n" +
	"\x06params\x18\x01 \x01(\v2\x18.zerone.tokens.v1.ParamsR\x06params\"4\n" +
	"\x17QueryTokenConfigRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"S\n" +
	"\x18QueryTokenConfigResponse\x127\n" +
	"\x05token\x18\x01 \x01(\v2!.zerone.tokens.v1.TokenDefinitionR\x05token\"\\\n" +
	"\x12QueryTokensRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x99\x01\n" +
	"\x13QueryTokensResponse\x129\n" +
	"\x06tokens\x18\x01 \x03(\v2!.zerone.tokens.v1.TokenDefinitionR\x06tokens\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"3\n" +
	"\x19QueryTokenBySymbolRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"U\n" +
	"\x1aQueryTokenBySymbolResponse\x127\n" +
	"\x05token\x18\x01 \x01(\v2!.zerone.tokens.v1.TokenDefinitionR\x05token\"J\n" +
	"\x13QueryBalanceRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"0\n" +
	"\x14QueryBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\"4\n" +
	"\x17QueryTotalSupplyRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"\x8c\x01\n" +
	"\x18QueryTotalSupplyResponse\x12!\n" +
	"\ftotal_supply\x18\x01 \x01(\tR\vtotalSupply\x12\x1d\n" +
	"\n" +
	"max_supply\x18\x02 \x01(\tR\tmaxSupply\x12\x16\n" +
	"\x06minted\x18\x03 \x01(\tR\x06minted\x12\x16\n" +
	"\x06burned\x18\x04 \x01(\tR\x06burned\"b\n" +
	"\x15QueryAllowanceRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\aspender\x18\x03 \x01(\tR\aspender\"6\n" +
	"\x16QueryAllowanceResponse\x12\x1c\n" +
	"\tallowance\x18\x01 \x01(\tR\tallowance\"Q\n" +
	"\x1aQueryDelegatedPowerRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x9e\x01\n" +
	"\x1bQueryDelegatedPowerResponse\x12'\n" +
	"\x0fdelegated_total\x18\x01 \x01(\tR\x0edelegatedTotal\x12%\n" +
	"\x0ereceived_total\x18\x02 \x01(\tR\rreceivedTotal\x12/\n" +
	"\x13undelegated_balance\x18\x03 \x01(\tR\x12undelegatedBalance\"5\n" +
	"\x18QueryWrappedTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"\x80\x01\n" +
	"\x19QueryWrappedTokenResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12#\n" +
	"\rwrapped_denom\x18\x02 \x01(\tR\fwrappedDenom\x12#\n" +
	"\rtotal_wrapped\x18\x03 \x01(\tR\ftotalWrapped\"c\n" +
	"\x19QueryWrappedTokensRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xac\x01\n" +
	"\x1aQueryWrappedTokensResponse\x12E\n" +
	"\arecords\x18\x01 \x03(\v2+.zerone.tokens.v1.QueryWrappedTokenResponseR\arecords\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"=\n" +
	"\x1aQueryEmissionPeriodRequest\x12\x1f\n" +
	"\vemission_id\x18\x01 \x01(\tR\n" +
	"emissionId\"[\n" +
	"\x1bQueryEmissionPeriodResponse\x12<\n" +
	"\bemission\x18\x01 \x01(\v2 .zerone.tokens.v1.EmissionPeriodR\bemission\"\x86\x01\n" +
	"\x1bQueryEmissionPeriodsRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xa7\x01\n" +
	"\x1cQueryEmissionPeriodsResponse\x12>\n" +
	"\temissions\x18\x01 \x03(\v2 .zerone.tokens.v1.EmissionPeriodR\temissions\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination2\xa0\x0e\n" +
	"\x05Query\x12w\n" +
	"\x06Params\x12$.zerone.tokens.v1.QueryParamsRequest\x1a%.zerone.tokens.v1.QueryParamsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/zerone/tokens/v1/params\x12\x91\x01\n" +
	"\vTokenConfig\x12).zerone.tokens.v1.QueryTokenConfigRequest\x1a*.zerone.tokens.v1.QueryTokenConfigResponse\"+\x82\xd3\xe4\x93\x02%\x12#/zerone/tokens/v1/tokens/{token_id}\x12w\n" +
	"\x06Tokens\x12$.zerone.tokens.v1.QueryTokensRequest\x1a%.zerone.tokens.v1.QueryTokensResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/zerone/tokens/v1/tokens\x12\x9c\x01\n" +
	"\rTokenBySymbol\x12+.zerone.tokens.v1.QueryTokenBySymbolRequest\x1a,.zerone.tokens.v1.QueryTokenBySymbolResponse\"0\x82\xd3\xe4\x93\x02*\x12(/zerone/tokens/v1/tokens/symbol/{symbol}\x12\x97\x01\n" +
	"\aBalance\x12%.zerone.tokens.v1.QueryBalanceRequest\x1a&.zerone.tokens.v1.QueryBalanceResponse\"=\x82\xd3\xe4\x93\x027\x125/zerone/tokens/v1/tokens/{token_id}/balance/{address}\x12\x98\x01\n" +
	"\vTotalSupply\x12).zerone.tokens.v1.QueryTotalSupplyRequest\x1a*.zerone.tokens.v1.QueryTotalSupplyResponse\"2\x82\xd3\xe4\x93\x02,\x12*/zerone/tokens/v1/tokens/{token_id}/supply\x12\xa7\x01\n" +
	"\tAllowance\x12'.zerone.tokens.v1.QueryAllowanceRequest\x1a(.zerone.tokens.v1.QueryAllowanceResponse\"G\x82\xd3\xe4\x93\x02A\x12?/zerone/tokens/v1/tokens/{token_id}/allowance/{owner}/{spender}\x12\xaf\x01\n" +
	"\x0eDelegatedPower\x12,.zerone.tokens.v1.QueryDelegatedPowerRequest\x1a-.zerone.tokens.v1.QueryDelegatedPowerResponse\"@\x82\xd3\xe4\x93\x02:\x128/zerone/tokens/v1/tokens/{token_id}/delegation/{address}\x12\x95\x01\n" +
	"\fWrappedToken\x12*.zerone.tokens.v1.QueryWrappedTokenRequest\x1a+.zerone.tokens.v1.QueryWrappedTokenResponse\",\x82\xd3\xe4\x93\x02&\x12$/zerone/tokens/v1/wrapped/{token_id}\x12\x8d\x01\n" +
	"\rWrappedTokens\x12+.zerone.tokens.v1.QueryWrappedTokensRequest\x1a,.zerone.tokens.v1.QueryWrappedTokensResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/zerone/tokens/v1/wrapped\x12\xa0\x01\n" +
	"\x0eEmissionPeriod\x12,.zerone.tokens.v1.QueryEmissionPeriodRequest\x1a-.zerone.tokens.v1.QueryEmissionPeriodResponse\"1\x82\xd3\xe4\x93\x02+\x12)/zerone/tokens/v1/emissions/{emission_id}\x12\x95\x01\n" +
	"\x0fEmissionPeriods\x12-.zerone.tokens.v1.QueryEmissionPeriodsRequest\x1a..zerone.tokens.v1.QueryEmissionPeriodsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/zerone/tokens/v1/emissionsB/Z-github.com/zerone-chain/zerone/x/tokens/typesb\x06proto3"

var (
	file_zerone_tokens_v1_query_proto_rawDescOnce sync.Once
	file_zerone_tokens_v1_query_proto_rawDescData []byte
)

func file_zerone_tokens_v1_query_proto_rawDescGZIP() []byte {
	file_zerone_tokens_v1_query_proto_rawDescOnce.Do(func() {
		file_zerone_tokens_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_tokens_v1_query_proto_rawDesc), len(file_zerone_tokens_v1_query_proto_rawDesc)))
	})
	return file_zerone_tokens_v1_query_proto_rawDescData
}

var file_zerone_tokens_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_zerone_tokens_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),           // 0: zerone.tokens.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),          // 1: zerone.tokens.v1.QueryParamsResponse
	(*QueryTokenConfigRequest)(nil),      // 2: zerone.tokens.v1.QueryTokenConfigRequest
	(*QueryTokenConfigResponse)(nil),     // 3: zerone.tokens.v1.QueryTokenConfigResponse
	(*QueryTokensRequest)(nil),           // 4: zerone.tokens.v1.QueryTokensRequest
	(*QueryTokensResponse)(nil),          // 5: zerone.tokens.v1.QueryTokensResponse
	(*QueryTokenBySymbolRequest)(nil),    // 6: zerone.tokens.v1.QueryTokenBySymbolRequest
	(*QueryTokenBySymbolResponse)(nil),   // 7: zerone.tokens.v1.QueryTokenBySymbolResponse
	(*QueryBalanceRequest)(nil),          // 8: zerone.tokens.v1.QueryBalanceRequest
	(*QueryBalanceResponse)(nil),         // 9: zerone.tokens.v1.QueryBalanceResponse
	(*QueryTotalSupplyRequest)(nil),      // 10: zerone.tokens.v1.QueryTotalSupplyRequest
	(*QueryTotalSupplyResponse)(nil),     // 11: zerone.tokens.v1.QueryTotalSupplyResponse
	(*QueryAllowanceRequest)(nil),        // 12: zerone.tokens.v1.QueryAllowanceRequest
	(*QueryAllowanceResponse)(nil),       // 13: zerone.tokens.v1.QueryAllowanceResponse
	(*QueryDelegatedPowerRequest)(nil),   // 14: zerone.tokens.v1.QueryDelegatedPowerRequest
	(*QueryDelegatedPowerResponse)(nil),  // 15: zerone.tokens.v1.QueryDelegatedPowerResponse
	(*QueryWrappedTokenRequest)(nil),     // 16: zerone.tokens.v1.QueryWrappedTokenRequest
	(*QueryWrappedTokenResponse)(nil),    // 17: zerone.tokens.v1.QueryWrappedTokenResponse
	(*QueryWrappedTokensRequest)(nil),    // 18: zerone.tokens.v1.QueryWrappedTokensRequest
	(*QueryWrappedTokensResponse)(nil),   // 19: zerone.tokens.v1.QueryWrappedTokensResponse
	(*QueryEmissionPeriodRequest)(nil),   // 20: zerone.tokens.v1.QueryEmissionPeriodRequest
	(*QueryEmissionPeriodResponse)(nil),  // 21: zerone.tokens.v1.QueryEmissionPeriodResponse
	(*QueryEmissionPeriodsRequest)(nil),  // 22: zerone.tokens.v1.QueryEmissionPeriodsRequest
	(*QueryEmissionPeriodsResponse)(nil), // 23: zerone.tokens.v1.QueryEmissionPeriodsResponse
	(*Params)(nil),                       // 24: zerone.tokens.v1.Params
	(*TokenDefinition)(nil),              // 25: zerone.tokens.v1.TokenDefinition
	(*query.PageRequest)(nil),            // 26: cosmos.base.query.v1beta1.PageRequest
	(*query.PageResponse)(nil),           // 27: cosmos.base.query.v1beta1.PageResponse
	(*EmissionPeriod)(nil),               // 28: zerone.tokens.v1.EmissionPeriod
}
var file_zerone_tokens_v1_query_proto_depIdxs = []int32{
	24, // 0: zerone.tokens.v1.QueryParamsResponse.params:type_name -> zerone.tokens.v1.Params
	25, // 1: zerone.tokens.v1.QueryTokenConfigResponse.token:type_name -> zerone.tokens.v1.TokenDefinition
	26, // 2: zerone.tokens.v1.QueryTokensRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	25, // 3: zerone.tokens.v1.QueryTokensResponse.tokens:type_name -> zerone.tokens.v1.TokenDefinition
	27, // 4: zerone.tokens.v1.QueryTokensResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	25, // 5: zerone.tokens.v1.QueryTokenBySymbolResponse.token:type_name -> zerone.tokens.v1.TokenDefinition
	26, // 6: zerone.tokens.v1.QueryWrappedTokensRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	17, // 7: zerone.tokens.v1.QueryWrappedTokensResponse.records:type_name -> zerone.tokens.v1.QueryWrappedTokenResponse
	27, // 8: zerone.tokens.v1.QueryWrappedTokensResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	28, // 9: zerone.tokens.v1.QueryEmissionPeriodResponse.emission:type_name -> zerone.tokens.v1.EmissionPeriod
	26, // 10: zerone.tokens.v1.QueryEmissionPeriodsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	28, // 11: zerone.tokens.v1.QueryEmissionPeriodsResponse.emissions:type_name -> zerone.tokens.v1.EmissionPeriod
	27, // 12: zerone.tokens.v1.QueryEmissionPeriodsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	0,  // 13: zerone.tokens.v1.Query.Params:input_type -> zerone.tokens.v1.QueryParamsRequest
	2,  // 14: zerone.tokens.v1.Query.TokenConfig:input_type -> zerone.tokens.v1.QueryTokenConfigRequest
	4,  // 15: zerone.tokens.v1.Query.Tokens:input_type -> zerone.tokens.v1.QueryTokensRequest
	6,  // 16: zerone.tokens.v1.Query.TokenBySymbol:input_type -> zerone.tokens.v1.QueryTokenBySymbolRequest
	8,  // 17: zerone.tokens.v1.Query.Balance:input_type -> zerone.tokens.v1.QueryBalanceRequest
	10, // 18: zerone.tokens.v1.Query.TotalSupply:input_type -> zerone.tokens.v1.QueryTotalSupplyRequest
	12, // 19: zerone.tokens.v1.Query.Allowance:input_type -> zerone.tokens.v1.QueryAllowanceRequest
	14, // 20: zerone.tokens.v1.Query.DelegatedPower:input_type -> zerone.tokens.v1.QueryDelegatedPowerRequest
	16, // 21: zerone.tokens.v1.Query.WrappedToken:input_type -> zerone.tokens.v1.QueryWrappedTokenRequest
	18, // 22: zerone.tokens.v1.Query.WrappedTokens:input_type -> zerone.tokens.v1.QueryWrappedTokensRequest
	20, // 23: zerone.tokens.v1.Query.EmissionPeriod:input_type -> zerone.tokens.v1.QueryEmissionPeriodRequest
	22, // 24: zerone.tokens.v1.Query.EmissionPeriods:input_type -> zerone.tokens.v1.QueryEmissionPeriodsRequest
	1,  // 25: zerone.tokens.v1.Query.Params:output_type -> zerone.tokens.v1.QueryParamsResponse
	3,  // 26: zerone.tokens.v1.Query.TokenConfig:output_type -> zerone.tokens.v1.QueryTokenConfigResponse
	5,  // 27: zerone.tokens.v1.Query.Tokens:output_type -> zerone.tokens.v1.QueryTokensResponse
	7,  // 28: zerone.tokens.v1.Query.TokenBySymbol:output_type -> zerone.tokens.v1.QueryTokenBySymbolResponse
	9,  // 29: zerone.tokens.v1.Query.Balance:output_type -> zerone.tokens.v1.QueryBalanceResponse
	11, // 30: zerone.tokens.v1.Query.TotalSupply:output_type -> zerone.tokens.v1.QueryTotalSupplyResponse
	13, // 31: zerone.tokens.v1.Query.Allowance:output_type -> zerone.tokens.v1.QueryAllowanceResponse
	15, // 32: zerone.tokens.v1.Query.DelegatedPower:output_type -> zerone.tokens.v1.QueryDelegatedPowerResponse
	17, // 33: zerone.tokens.v1.Query.WrappedToken:output_type -> zerone.tokens.v1.QueryWrappedTokenResponse
	19, // 34: zerone.tokens.v1.Query.WrappedTokens:output_type -> zerone.tokens.v1.QueryWrappedTokensResponse
	21, // 35: zerone.tokens.v1.Query.EmissionPeriod:output_type -> zerone.tokens.v1.QueryEmissionPeriodResponse
	23, // 36: zerone.tokens.v1.Query.EmissionPeriods:output_type -> zerone.tokens.v1.QueryEmissionPeriodsResponse
	25, // [25:37] is the sub-list for method output_type
	13, // [13:25] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_zerone_tokens_v1_query_proto_init() }
func file_zerone_tokens_v1_query_proto_init() {
	if File_zerone_tokens_v1_query_proto != nil {
		return
	}
	file_zerone_tokens_v1_types_proto_init()
	file_zerone_tokens_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_tokens_v1_query_proto_rawDesc), len(file_zerone_tokens_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_tokens_v1_query_proto_goTypes,
		DependencyIndexes: file_zerone_tokens_v1_query_proto_depIdxs,
		MessageInfos:      file_zerone_tokens_v1_query_proto_msgTypes,
	}.Build()
	File_zerone_tokens_v1_query_proto = out.File
	file_zerone_tokens_v1_query_proto_goTypes = nil
	file_zerone_tokens_v1_query_proto_depIdxs = nil
}
