// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/tokens/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenFeatures controls which operations are enabled for a token.
type TokenFeatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mintable      bool                   `protobuf:"varint,1,opt,name=mintable,proto3" json:"mintable,omitempty"`
	Burnable      bool                   `protobuf:"varint,2,opt,name=burnable,proto3" json:"burnable,omitempty"`
	Pausable      bool                   `protobuf:"varint,3,opt,name=pausable,proto3" json:"pausable,omitempty"`
	Wrappable     bool                   `protobuf:"varint,4,opt,name=wrappable,proto3" json:"wrappable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenFeatures) Reset() {
	*x = TokenFeatures{}
	mi := &file_zerone_tokens_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenFeatures) ProtoMessage() {}

func (x *TokenFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenFeatures.ProtoReflect.Descriptor instead.
func (*TokenFeatures) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *TokenFeatures) GetMintable() bool {
	if x != nil {
		return x.Mintable
	}
	return false
}

func (x *TokenFeatures) GetBurnable() bool {
	if x != nil {
		return x.Burnable
	}
	return false
}

func (x *TokenFeatures) GetPausable() bool {
	if x != nil {
		return x.Pausable
	}
	return false
}

func (x *TokenFeatures) GetWrappable() bool {
	if x != nil {
		return x.Wrappable
	}
	return false
}

// TokenDefinition is a ZRN-20 secondary token's on-chain configuration.
type TokenDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator       string                 `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"` // address that created the token (= mint authority)
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"` // 1-16 uppercase alphanumeric
	Decimals      uint32                 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TotalSupply   string                 `protobuf:"bytes,6,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"` // bigint as string
	MaxSupply     string                 `protobuf:"bytes,7,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`       // "0" = unlimited
	Features      *TokenFeatures         `protobuf:"bytes,8,opt,name=features,proto3" json:"features,omitempty"`
	Paused        bool                   `protobuf:"varint,9,opt,name=paused,proto3" json:"paused,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // block height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDefinition) Reset() {
	*x = TokenDefinition{}
	mi := &file_zerone_tokens_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDefinition) ProtoMessage() {}

func (x *TokenDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDefinition.ProtoReflect.Descriptor instead.
func (*TokenDefinition) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *TokenDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenDefinition) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *TokenDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenDefinition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenDefinition) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenDefinition) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *TokenDefinition) GetMaxSupply() string {
	if x != nil {
		return x.MaxSupply
	}
	return ""
}

func (x *TokenDefinition) GetFeatures() *TokenFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *TokenDefinition) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *TokenDefinition) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// EmissionPeriod defines a scheduled token emission (replaces LP pools).
type EmissionPeriod struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartBlock     uint64                 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock       uint64                 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	AmountPerBlock string                 `protobuf:"bytes,4,opt,name=amount_per_block,json=amountPerBlock,proto3" json:"amount_per_block,omitempty"` // uzrn per block
	Recipient      string                 `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`                                   // module account or address
	Active         bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	TotalEmitted   string                 `protobuf:"bytes,7,opt,name=total_emitted,json=totalEmitted,proto3" json:"total_emitted,omitempty"` // running total emitted
	Creator        string                 `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`                               // governance authority that created it
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmissionPeriod) Reset() {
	*x = EmissionPeriod{}
	mi := &file_zerone_tokens_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmissionPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmissionPeriod) ProtoMessage() {}

func (x *EmissionPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tokens_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmissionPeriod.ProtoReflect.Descriptor instead.
func (*EmissionPeriod) Descriptor() ([]byte, []int) {
	return file_zerone_tokens_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *EmissionPeriod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmissionPeriod) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *EmissionPeriod) GetEndBlock() uint64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

func (x *EmissionPeriod) GetAmountPerBlock() string {
	if x != nil {
		return x.AmountPerBlock
	}
	return ""
}

func (x *EmissionPeriod) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *EmissionPeriod) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *EmissionPeriod) GetTotalEmitted() string {
	if x != nil {
		return x.TotalEmitted
	}
	return ""
}

func (x *EmissionPeriod) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_zerone_tokens_v1_types_proto protoreflect.FileDescriptor

const file_zerone_tokens_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1czerone/tokens/v1/types.proto\x12\x10zerone.tokens.v1\"\x81\x01\n" +
	"\rTokenFeatures\x12\x1a\n" +
	"\bmintable\x18\x01 \x01(\bR\bmintable\x12\x1a\n" +
	"\bburnable\x18\x02 \x01(\bR\bburnable\x12\x1a\n" +
	"\bpausable\x18\x03 \x01(\bR\bpausable\x12\x1c\n" +
	"\twrappable\x18\x04 \x01(\bR\twrappable\"\xb9\x02\n" +
	"\x0fTokenDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x06 \x01(\tR\vtotalSupply\x12\x1d\n" +
	"\n" +
	"max_supply\x18\a \x01(\tR\tmaxSupply\x12;\n" +
	"\bfeatures\x18\b \x01(\v2\x1f.zerone.tokens.v1.TokenFeaturesR\bfeatures\x12\x16\n" +
	"\x06paused\x18\t \x01(\bR\x06paused\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x04R\tcreatedAt\"\xfd\x01\n" +
	"\x0eEmissionPeriod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12\x1b\n" +
	"\tend_block\x18\x03 \x01(\x04R\bendBlock\x12(\n" +
	"\x10amount_per_block\x18\x04 \x01(\tR\x0eamountPerBlock\x12\x1c\n" +
	"\trecipient\x18\x05 \x01(\tR\trecipient\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12#\n" +
	"\rtotal_emitted\x18\a \x01(\tR\ftotalEmitted\x12\x18\n" +
	"\acreator\x18\b \x01(\tR\acreatorB/Z-github.com/zerone-chain/zerone/x/tokens/typesb\x06proto3"

var (
	file_zerone_tokens_v1_types_proto_rawDescOnce sync.Once
	file_zerone_tokens_v1_types_proto_rawDescData []byte
)

func file_zerone_tokens_v1_types_proto_rawDescGZIP() []byte {
	file_zerone_tokens_v1_types_proto_rawDescOnce.Do(func() {
		file_zerone_tokens_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_tokens_v1_types_proto_rawDesc), len(file_zerone_tokens_v1_types_proto_rawDesc)))
	})
	return file_zerone_tokens_v1_types_proto_rawDescData
}

var file_zerone_tokens_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zerone_tokens_v1_types_proto_goTypes = []any{
	(*TokenFeatures)(nil),   // 0: zerone.tokens.v1.TokenFeatures
	(*TokenDefinition)(nil), // 1: zerone.tokens.v1.TokenDefinition
	(*EmissionPeriod)(nil),  // 2: zerone.tokens.v1.EmissionPeriod
}
var file_zerone_tokens_v1_types_proto_depIdxs = []int32{
	0, // 0: zerone.tokens.v1.TokenDefinition.features:type_name -> zerone.tokens.v1.TokenFeatures
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zerone_tokens_v1_types_proto_init() }
func file_zerone_tokens_v1_types_proto_init() {
	if File_zerone_tokens_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_tokens_v1_types_proto_rawDesc), len(file_zerone_tokens_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_tokens_v1_types_proto_goTypes,
		DependencyIndexes: file_zerone_tokens_v1_types_proto_depIdxs,
		MessageInfos:      file_zerone_tokens_v1_types_proto_msgTypes,
	}.Build()
	File_zerone_tokens_v1_types_proto = out.File
	file_zerone_tokens_v1_types_proto_goTypes = nil
	file_zerone_tokens_v1_types_proto_depIdxs = nil
}
