#!/usr/bin/env bash
# agent-config-gen.sh — Generate agent.toml from role template + CLI args
#
# Usage:
#   ./scripts/agent-config-gen.sh \
#     --name SAGE \
#     --role scientist \
#     --domain "math,physics" \
#     --stake 10000000 \
#     --chain-id zerone-devnet-1 \
#     --node tcp://localhost:26657
#
# Outputs: agent.toml and SOUL.md in ~/.zerone/agents/<name>/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="${SCRIPT_DIR}/agent-soul-templates"

# ── Defaults ────────────────────────────────────────────────────────────────
NAME=""
ROLE="scientist"
DOMAINS=""
STAKE="10000000"
CHAIN_ID="zerone-devnet-1"
NODE="tcp://localhost:26657"
OUTPUT_DIR=""

# ── Role defaults ───────────────────────────────────────────────────────────
declare -A REVIEW_RATIO=(
  [scientist]="0.2"
  [creative]="0.1"
  [reviewer]="0.7"
  [explorer]="0.2"
  [coordinator]="0.3"
)
declare -A RISK_TOLERANCE=(
  [scientist]="0.5"
  [creative]="0.8"
  [reviewer]="0.3"
  [explorer]="0.9"
  [coordinator]="0.4"
)
declare -A SWARM_AFFINITY=(
  [scientist]="0.3"
  [creative]="0.6"
  [reviewer]="0.2"
  [explorer]="0.7"
  [coordinator]="0.9"
)
declare -A STRATEGY_DESC=(
  [scientist]="Deep domain expertise, novel TDUs"
  [creative]="Cross-domain connections, metaphor"
  [reviewer]="Quality gatekeeper, high accuracy"
  [explorer]="New domains, gap-filling, bounties"
  [coordinator]="Swarm formation, task delegation"
)

# ── Parse args ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)    NAME="$2";     shift 2;;
    --role)    ROLE="$2";     shift 2;;
    --domain)  DOMAINS="$2";  shift 2;;
    --stake)   STAKE="$2";    shift 2;;
    --chain-id) CHAIN_ID="$2"; shift 2;;
    --node)    NODE="$2";     shift 2;;
    --output)  OUTPUT_DIR="$2"; shift 2;;
    -h|--help)
      echo "Usage: $0 --name NAME --role ROLE --domain DOMAINS [--stake STAKE] [--chain-id ID] [--node URI] [--output DIR]"
      echo ""
      echo "Roles: scientist, creative, reviewer, explorer, coordinator"
      echo "Domains: comma-separated (e.g., 'math,physics')"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1;;
  esac
done

# ── Validate ────────────────────────────────────────────────────────────────
if [[ -z "$NAME" ]]; then
  echo "Error: --name is required" >&2
  exit 1
fi

if [[ -z "$DOMAINS" ]]; then
  echo "Error: --domain is required" >&2
  exit 1
fi

case "$ROLE" in
  scientist|creative|reviewer|explorer|coordinator) ;;
  *) echo "Error: invalid role '$ROLE'. Must be scientist, creative, reviewer, explorer, or coordinator" >&2; exit 1;;
esac

# ── Derive identity ────────────────────────────────────────────────────────
NAME_LOWER=$(echo "$NAME" | tr '[:upper:]' '[:lower:]')
AGENT_ID=$(echo -n "agent:${NAME_LOWER}" | shasum -a 256 | cut -d' ' -f1)
ADDRESS=$(echo -n "zerone-agent:${NAME_LOWER}" | shasum -a 256 | cut -c1-40)

# ── Output directory ────────────────────────────────────────────────────────
if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="${HOME}/.zerone/agents/${NAME_LOWER}"
fi
mkdir -p "$OUTPUT_DIR"

# ── Format domains for TOML ────────────────────────────────────────────────
IFS=',' read -ra DOMAIN_ARRAY <<< "$DOMAINS"
TOML_DOMAINS=""
for d in "${DOMAIN_ARRAY[@]}"; do
  d=$(echo "$d" | xargs) # trim whitespace
  if [[ -n "$TOML_DOMAINS" ]]; then
    TOML_DOMAINS="${TOML_DOMAINS}, "
  fi
  TOML_DOMAINS="${TOML_DOMAINS}\"${d}\""
done

# ── Generate agent.toml ────────────────────────────────────────────────────
cat > "${OUTPUT_DIR}/agent.toml" <<EOF
# Agent Configuration — generated by agent-config-gen.sh
# Role: ${ROLE} — ${STRATEGY_DESC[$ROLE]}

[identity]
name = "${NAME}"
agent_id = "${AGENT_ID}"
wallet = "${ADDRESS}"
role = "${ROLE}"

[chain]
node = "${NODE}"
chain_id = "${CHAIN_ID}"
denom = "uzrn"

[strategy]
domains = [${TOML_DOMAINS}]
risk_tolerance = ${RISK_TOLERANCE[$ROLE]}
min_bounty_reward = "1000000"
swarm_affinity = ${SWARM_AFFINITY[$ROLE]}
review_ratio = ${REVIEW_RATIO[$ROLE]}

[api]
model_preference = "best"
max_spend_per_epoch = "5000000"

[heartbeat]
interval = "7m"
hive_check = true
EOF

echo "Generated: ${OUTPUT_DIR}/agent.toml"

# ── Generate SOUL.md from template ─────────────────────────────────────────
TEMPLATE="${TEMPLATE_DIR}/${ROLE}.md"
if [[ -f "$TEMPLATE" ]]; then
  sed -e "s/{{NAME}}/${NAME}/g" -e "s/{{DOMAINS}}/${DOMAINS}/g" "$TEMPLATE" > "${OUTPUT_DIR}/SOUL.md"
  echo "Generated: ${OUTPUT_DIR}/SOUL.md"
else
  echo "Warning: template not found at ${TEMPLATE}, skipping SOUL.md" >&2
fi

# ── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "Agent created:"
echo "  Name:      ${NAME}"
echo "  Role:      ${ROLE}"
echo "  Agent ID:  ${AGENT_ID}"
echo "  Address:   ${ADDRESS}"
echo "  Domains:   ${DOMAINS}"
echo "  Stake:     ${STAKE} uzrn"
echo "  Config:    ${OUTPUT_DIR}/agent.toml"
echo "  SOUL:      ${OUTPUT_DIR}/SOUL.md"
echo ""
echo "Next steps:"
echo "  1. Fund the agent wallet: zeroned tx knowledge agent-fund ${ADDRESS} ${STAKE}uzrn --from <creator>"
echo "  2. Register on-chain when a model is available"
