// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/private_corpus/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVaultRequest) Reset() {
	*x = QueryVaultRequest{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVaultRequest) ProtoMessage() {}

func (x *QueryVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVaultRequest.ProtoReflect.Descriptor instead.
func (*QueryVaultRequest) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryVaultRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryVaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         *Vault                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVaultResponse) Reset() {
	*x = QueryVaultResponse{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVaultResponse) ProtoMessage() {}

func (x *QueryVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVaultResponse.ProtoReflect.Descriptor instead.
func (*QueryVaultResponse) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryVaultResponse) GetVault() *Vault {
	if x != nil {
		return x.Vault
	}
	return nil
}

type QueryVaultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	StartAfterId  string                 `protobuf:"bytes,2,opt,name=start_after_id,json=startAfterId,proto3" json:"start_after_id,omitempty"` // pagination cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVaultsRequest) Reset() {
	*x = QueryVaultsRequest{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVaultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVaultsRequest) ProtoMessage() {}

func (x *QueryVaultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVaultsRequest.ProtoReflect.Descriptor instead.
func (*QueryVaultsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryVaultsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryVaultsRequest) GetStartAfterId() string {
	if x != nil {
		return x.StartAfterId
	}
	return ""
}

type QueryVaultsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vaults           []*Vault               `protobuf:"bytes,1,rep,name=vaults,proto3" json:"vaults,omitempty"`
	NextStartAfterId string                 `protobuf:"bytes,2,opt,name=next_start_after_id,json=nextStartAfterId,proto3" json:"next_start_after_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryVaultsResponse) Reset() {
	*x = QueryVaultsResponse{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVaultsResponse) ProtoMessage() {}

func (x *QueryVaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVaultsResponse.ProtoReflect.Descriptor instead.
func (*QueryVaultsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryVaultsResponse) GetVaults() []*Vault {
	if x != nil {
		return x.Vaults
	}
	return nil
}

func (x *QueryVaultsResponse) GetNextStartAfterId() string {
	if x != nil {
		return x.NextStartAfterId
	}
	return ""
}

type QueryVaultsByOperatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVaultsByOperatorRequest) Reset() {
	*x = QueryVaultsByOperatorRequest{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVaultsByOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVaultsByOperatorRequest) ProtoMessage() {}

func (x *QueryVaultsByOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVaultsByOperatorRequest.ProtoReflect.Descriptor instead.
func (*QueryVaultsByOperatorRequest) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryVaultsByOperatorRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type QueryVaultsByOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vaults        []*Vault               `protobuf:"bytes,1,rep,name=vaults,proto3" json:"vaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVaultsByOperatorResponse) Reset() {
	*x = QueryVaultsByOperatorResponse{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVaultsByOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVaultsByOperatorResponse) ProtoMessage() {}

func (x *QueryVaultsByOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVaultsByOperatorResponse.ProtoReflect.Descriptor instead.
func (*QueryVaultsByOperatorResponse) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryVaultsByOperatorResponse) GetVaults() []*Vault {
	if x != nil {
		return x.Vaults
	}
	return nil
}

type QueryManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryManifestRequest) Reset() {
	*x = QueryManifestRequest{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryManifestRequest) ProtoMessage() {}

func (x *QueryManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryManifestRequest.ProtoReflect.Descriptor instead.
func (*QueryManifestRequest) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryManifestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *CorpusManifest        `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryManifestResponse) Reset() {
	*x = QueryManifestResponse{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryManifestResponse) ProtoMessage() {}

func (x *QueryManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryManifestResponse.ProtoReflect.Descriptor instead.
func (*QueryManifestResponse) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryManifestResponse) GetManifest() *CorpusManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type QueryManifestsByVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	StartAfterId  string                 `protobuf:"bytes,3,opt,name=start_after_id,json=startAfterId,proto3" json:"start_after_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryManifestsByVaultRequest) Reset() {
	*x = QueryManifestsByVaultRequest{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryManifestsByVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryManifestsByVaultRequest) ProtoMessage() {}

func (x *QueryManifestsByVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryManifestsByVaultRequest.ProtoReflect.Descriptor instead.
func (*QueryManifestsByVaultRequest) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryManifestsByVaultRequest) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *QueryManifestsByVaultRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryManifestsByVaultRequest) GetStartAfterId() string {
	if x != nil {
		return x.StartAfterId
	}
	return ""
}

type QueryManifestsByVaultResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Manifests        []*CorpusManifest      `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty"`
	NextStartAfterId string                 `protobuf:"bytes,2,opt,name=next_start_after_id,json=nextStartAfterId,proto3" json:"next_start_after_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryManifestsByVaultResponse) Reset() {
	*x = QueryManifestsByVaultResponse{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryManifestsByVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryManifestsByVaultResponse) ProtoMessage() {}

func (x *QueryManifestsByVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryManifestsByVaultResponse.ProtoReflect.Descriptor instead.
func (*QueryManifestsByVaultResponse) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryManifestsByVaultResponse) GetManifests() []*CorpusManifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *QueryManifestsByVaultResponse) GetNextStartAfterId() string {
	if x != nil {
		return x.NextStartAfterId
	}
	return ""
}

type QueryAccessRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	StartAfterSeq uint64                 `protobuf:"varint,3,opt,name=start_after_seq,json=startAfterSeq,proto3" json:"start_after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccessRecordsRequest) Reset() {
	*x = QueryAccessRecordsRequest{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccessRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccessRecordsRequest) ProtoMessage() {}

func (x *QueryAccessRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccessRecordsRequest.ProtoReflect.Descriptor instead.
func (*QueryAccessRecordsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryAccessRecordsRequest) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *QueryAccessRecordsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryAccessRecordsRequest) GetStartAfterSeq() uint64 {
	if x != nil {
		return x.StartAfterSeq
	}
	return 0
}

type QueryAccessRecordsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Records           []*AccessRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextStartAfterSeq uint64                 `protobuf:"varint,2,opt,name=next_start_after_seq,json=nextStartAfterSeq,proto3" json:"next_start_after_seq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryAccessRecordsResponse) Reset() {
	*x = QueryAccessRecordsResponse{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccessRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccessRecordsResponse) ProtoMessage() {}

func (x *QueryAccessRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccessRecordsResponse.ProtoReflect.Descriptor instead.
func (*QueryAccessRecordsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryAccessRecordsResponse) GetRecords() []*AccessRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryAccessRecordsResponse) GetNextStartAfterSeq() uint64 {
	if x != nil {
		return x.NextStartAfterSeq
	}
	return 0
}

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{12}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_private_corpus_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_private_corpus_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_zerone_private_corpus_v1_query_proto protoreflect.FileDescriptor

const file_zerone_private_corpus_v1_query_proto_rawDesc = "" +
	"\n" +
	"$zerone/private_corpus/v1/query.proto\x12\x18zerone.private_corpus.v1\x1a\x1cgoogle/api/annotations.proto\x1a$zerone/private_corpus/v1/types.proto\x1a&zerone/private_corpus/v1/genesis.proto\"#\n" +
	"\x11QueryVaultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x12QueryVaultResponse\x125\n" +
	"\x05vault\x18\x01 \x01(\v2\x1f.zerone.private_corpus.v1.VaultR\x05vault\"P\n" +
	"\x12QueryVaultsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12$\n" +
	"\x0estart_after_id\x18\x02 \x01(\tR\fstartAfterId\"}\n" +
	"\x13QueryVaultsResponse\x127\n" +
	"\x06vaults\x18\x01 \x03(\v2\x1f.zerone.private_corpus.v1.VaultR\x06vaults\x12-\n" +
	"\x13next_start_after_id\x18\x02 \x01(\tR\x10nextStartAfterId\":\n" +
	"\x1cQueryVaultsByOperatorRequest\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\"X\n" +
	"\x1dQueryVaultsByOperatorResponse\x127\n" +
	"\x06vaults\x18\x01 \x03(\v2\x1f.zerone.private_corpus.v1.VaultR\x06vaults\"&\n" +
	"\x14QueryManifestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x15QueryManifestResponse\x12D\n" +
	"\bmanifest\x18\x01 \x01(\v2(.zerone.private_corpus.v1.CorpusManifestR\bmanifest\"u\n" +
	"\x1cQueryManifestsByVaultRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12$\n" +
	"\x0estart_after_id\x18\x03 \x01(\tR\fstartAfterId\"\x96\x01\n" +
	"\x1dQueryManifestsByVaultResponse\x12F\n" +
	"\tmanifests\x18\x01 \x03(\v2(.zerone.private_corpus.v1.CorpusManifestR\tmanifests\x12-\n" +
	"\x13next_start_after_id\x18\x02 \x01(\tR\x10nextStartAfterId\"t\n" +
	"\x19QueryAccessRecordsRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12&\n" +
	"\x0fstart_after_seq\x18\x03 \x01(\x04R\rstartAfterSeq\"\x8f\x01\n" +
	"\x1aQueryAccessRecordsResponse\x12@\n" +
	"\arecords\x18\x01 \x03(\v2&.zerone.private_corpus.v1.AccessRecordR\arecords\x12/\n" +
	"\x14next_start_after_seq\x18\x02 \x01(\x04R\x11nextStartAfterSeq\"\x14\n" +
	"\x12QueryParamsRequest\"O\n" +
	"\x13QueryParamsResponse\x128\n" +
	"\x06params\x18\x01 \x01(\v2 .zerone.private_corpus.v1.ParamsR\x06params2\x9c\t\n" +
	"\x05Query\x12\x90\x01\n" +
	"\x05Vault\x12+.zerone.private_corpus.v1.QueryVaultRequest\x1a,.zerone.private_corpus.v1.QueryVaultResponse\",\x82\xd3\xe4\x93\x02&\x12$/zerone/private_corpus/v1/vault/{id}\x12\x8f\x01\n" +
	"\x06Vaults\x12,.zerone.private_corpus.v1.QueryVaultsRequest\x1a-.zerone.private_corpus.v1.QueryVaultsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /zerone/private_corpus/v1/vaults\x12\xc4\x01\n" +
	"\x10VaultsByOperator\x126.zerone.private_corpus.v1.QueryVaultsByOperatorRequest\x1a7.zerone.private_corpus.v1.QueryVaultsByOperatorResponse\"?\x82\xd3\xe4\x93\x029\x127/zerone/private_corpus/v1/vaults_by_operator/{operator}\x12\x9c\x01\n" +
	"\bManifest\x12..zerone.private_corpus.v1.QueryManifestRequest\x1a/.zerone.private_corpus.v1.QueryManifestResponse\"/\x82\xd3\xe4\x93\x02)\x12'/zerone/private_corpus/v1/manifest/{id}\x12\xbb\x01\n" +
	"\x10ManifestsByVault\x126.zerone.private_corpus.v1.QueryManifestsByVaultRequest\x1a7.zerone.private_corpus.v1.QueryManifestsByVaultResponse\"6\x82\xd3\xe4\x93\x020\x12./zerone/private_corpus/v1/manifests/{vault_id}\x12\xb7\x01\n" +
	"\rAccessRecords\x123.zerone.private_corpus.v1.QueryAccessRecordsRequest\x1a4.zerone.private_corpus.v1.QueryAccessRecordsResponse\";\x82\xd3\xe4\x93\x025\x123/zerone/private_corpus/v1/access_records/{vault_id}\x12\x8f\x01\n" +
	"\x06Params\x12,.zerone.private_corpus.v1.QueryParamsRequest\x1a-.zerone.private_corpus.v1.QueryParamsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /zerone/private_corpus/v1/paramsB7Z5github.com/zerone-chain/zerone/x/private_corpus/typesb\x06proto3"

var (
	file_zerone_private_corpus_v1_query_proto_rawDescOnce sync.Once
	file_zerone_private_corpus_v1_query_proto_rawDescData []byte
)

func file_zerone_private_corpus_v1_query_proto_rawDescGZIP() []byte {
	file_zerone_private_corpus_v1_query_proto_rawDescOnce.Do(func() {
		file_zerone_private_corpus_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_private_corpus_v1_query_proto_rawDesc), len(file_zerone_private_corpus_v1_query_proto_rawDesc)))
	})
	return file_zerone_private_corpus_v1_query_proto_rawDescData
}

var file_zerone_private_corpus_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_zerone_private_corpus_v1_query_proto_goTypes = []any{
	(*QueryVaultRequest)(nil),             // 0: zerone.private_corpus.v1.QueryVaultRequest
	(*QueryVaultResponse)(nil),            // 1: zerone.private_corpus.v1.QueryVaultResponse
	(*QueryVaultsRequest)(nil),            // 2: zerone.private_corpus.v1.QueryVaultsRequest
	(*QueryVaultsResponse)(nil),           // 3: zerone.private_corpus.v1.QueryVaultsResponse
	(*QueryVaultsByOperatorRequest)(nil),  // 4: zerone.private_corpus.v1.QueryVaultsByOperatorRequest
	(*QueryVaultsByOperatorResponse)(nil), // 5: zerone.private_corpus.v1.QueryVaultsByOperatorResponse
	(*QueryManifestRequest)(nil),          // 6: zerone.private_corpus.v1.QueryManifestRequest
	(*QueryManifestResponse)(nil),         // 7: zerone.private_corpus.v1.QueryManifestResponse
	(*QueryManifestsByVaultRequest)(nil),  // 8: zerone.private_corpus.v1.QueryManifestsByVaultRequest
	(*QueryManifestsByVaultResponse)(nil), // 9: zerone.private_corpus.v1.QueryManifestsByVaultResponse
	(*QueryAccessRecordsRequest)(nil),     // 10: zerone.private_corpus.v1.QueryAccessRecordsRequest
	(*QueryAccessRecordsResponse)(nil),    // 11: zerone.private_corpus.v1.QueryAccessRecordsResponse
	(*QueryParamsRequest)(nil),            // 12: zerone.private_corpus.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),           // 13: zerone.private_corpus.v1.QueryParamsResponse
	(*Vault)(nil),                         // 14: zerone.private_corpus.v1.Vault
	(*CorpusManifest)(nil),                // 15: zerone.private_corpus.v1.CorpusManifest
	(*AccessRecord)(nil),                  // 16: zerone.private_corpus.v1.AccessRecord
	(*Params)(nil),                        // 17: zerone.private_corpus.v1.Params
}
var file_zerone_private_corpus_v1_query_proto_depIdxs = []int32{
	14, // 0: zerone.private_corpus.v1.QueryVaultResponse.vault:type_name -> zerone.private_corpus.v1.Vault
	14, // 1: zerone.private_corpus.v1.QueryVaultsResponse.vaults:type_name -> zerone.private_corpus.v1.Vault
	14, // 2: zerone.private_corpus.v1.QueryVaultsByOperatorResponse.vaults:type_name -> zerone.private_corpus.v1.Vault
	15, // 3: zerone.private_corpus.v1.QueryManifestResponse.manifest:type_name -> zerone.private_corpus.v1.CorpusManifest
	15, // 4: zerone.private_corpus.v1.QueryManifestsByVaultResponse.manifests:type_name -> zerone.private_corpus.v1.CorpusManifest
	16, // 5: zerone.private_corpus.v1.QueryAccessRecordsResponse.records:type_name -> zerone.private_corpus.v1.AccessRecord
	17, // 6: zerone.private_corpus.v1.QueryParamsResponse.params:type_name -> zerone.private_corpus.v1.Params
	0,  // 7: zerone.private_corpus.v1.Query.Vault:input_type -> zerone.private_corpus.v1.QueryVaultRequest
	2,  // 8: zerone.private_corpus.v1.Query.Vaults:input_type -> zerone.private_corpus.v1.QueryVaultsRequest
	4,  // 9: zerone.private_corpus.v1.Query.VaultsByOperator:input_type -> zerone.private_corpus.v1.QueryVaultsByOperatorRequest
	6,  // 10: zerone.private_corpus.v1.Query.Manifest:input_type -> zerone.private_corpus.v1.QueryManifestRequest
	8,  // 11: zerone.private_corpus.v1.Query.ManifestsByVault:input_type -> zerone.private_corpus.v1.QueryManifestsByVaultRequest
	10, // 12: zerone.private_corpus.v1.Query.AccessRecords:input_type -> zerone.private_corpus.v1.QueryAccessRecordsRequest
	12, // 13: zerone.private_corpus.v1.Query.Params:input_type -> zerone.private_corpus.v1.QueryParamsRequest
	1,  // 14: zerone.private_corpus.v1.Query.Vault:output_type -> zerone.private_corpus.v1.QueryVaultResponse
	3,  // 15: zerone.private_corpus.v1.Query.Vaults:output_type -> zerone.private_corpus.v1.QueryVaultsResponse
	5,  // 16: zerone.private_corpus.v1.Query.VaultsByOperator:output_type -> zerone.private_corpus.v1.QueryVaultsByOperatorResponse
	7,  // 17: zerone.private_corpus.v1.Query.Manifest:output_type -> zerone.private_corpus.v1.QueryManifestResponse
	9,  // 18: zerone.private_corpus.v1.Query.ManifestsByVault:output_type -> zerone.private_corpus.v1.QueryManifestsByVaultResponse
	11, // 19: zerone.private_corpus.v1.Query.AccessRecords:output_type -> zerone.private_corpus.v1.QueryAccessRecordsResponse
	13, // 20: zerone.private_corpus.v1.Query.Params:output_type -> zerone.private_corpus.v1.QueryParamsResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_zerone_private_corpus_v1_query_proto_init() }
func file_zerone_private_corpus_v1_query_proto_init() {
	if File_zerone_private_corpus_v1_query_proto != nil {
		return
	}
	file_zerone_private_corpus_v1_types_proto_init()
	file_zerone_private_corpus_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_private_corpus_v1_query_proto_rawDesc), len(file_zerone_private_corpus_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_private_corpus_v1_query_proto_goTypes,
		DependencyIndexes: file_zerone_private_corpus_v1_query_proto_depIdxs,
		MessageInfos:      file_zerone_private_corpus_v1_query_proto_msgTypes,
	}.Build()
	File_zerone_private_corpus_v1_query_proto = out.File
	file_zerone_private_corpus_v1_query_proto_goTypes = nil
	file_zerone_private_corpus_v1_query_proto_depIdxs = nil
}
