// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zerone/private_corpus/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Vault_FullMethodName            = "/zerone.private_corpus.v1.Query/Vault"
	Query_Vaults_FullMethodName           = "/zerone.private_corpus.v1.Query/Vaults"
	Query_VaultsByOperator_FullMethodName = "/zerone.private_corpus.v1.Query/VaultsByOperator"
	Query_Manifest_FullMethodName         = "/zerone.private_corpus.v1.Query/Manifest"
	Query_ManifestsByVault_FullMethodName = "/zerone.private_corpus.v1.Query/ManifestsByVault"
	Query_AccessRecords_FullMethodName    = "/zerone.private_corpus.v1.Query/AccessRecords"
	Query_Params_FullMethodName           = "/zerone.private_corpus.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	Vault(ctx context.Context, in *QueryVaultRequest, opts ...grpc.CallOption) (*QueryVaultResponse, error)
	Vaults(ctx context.Context, in *QueryVaultsRequest, opts ...grpc.CallOption) (*QueryVaultsResponse, error)
	VaultsByOperator(ctx context.Context, in *QueryVaultsByOperatorRequest, opts ...grpc.CallOption) (*QueryVaultsByOperatorResponse, error)
	Manifest(ctx context.Context, in *QueryManifestRequest, opts ...grpc.CallOption) (*QueryManifestResponse, error)
	ManifestsByVault(ctx context.Context, in *QueryManifestsByVaultRequest, opts ...grpc.CallOption) (*QueryManifestsByVaultResponse, error)
	AccessRecords(ctx context.Context, in *QueryAccessRecordsRequest, opts ...grpc.CallOption) (*QueryAccessRecordsResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Vault(ctx context.Context, in *QueryVaultRequest, opts ...grpc.CallOption) (*QueryVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVaultResponse)
	err := c.cc.Invoke(ctx, Query_Vault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Vaults(ctx context.Context, in *QueryVaultsRequest, opts ...grpc.CallOption) (*QueryVaultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVaultsResponse)
	err := c.cc.Invoke(ctx, Query_Vaults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VaultsByOperator(ctx context.Context, in *QueryVaultsByOperatorRequest, opts ...grpc.CallOption) (*QueryVaultsByOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVaultsByOperatorResponse)
	err := c.cc.Invoke(ctx, Query_VaultsByOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Manifest(ctx context.Context, in *QueryManifestRequest, opts ...grpc.CallOption) (*QueryManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryManifestResponse)
	err := c.cc.Invoke(ctx, Query_Manifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ManifestsByVault(ctx context.Context, in *QueryManifestsByVaultRequest, opts ...grpc.CallOption) (*QueryManifestsByVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryManifestsByVaultResponse)
	err := c.cc.Invoke(ctx, Query_ManifestsByVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AccessRecords(ctx context.Context, in *QueryAccessRecordsRequest, opts ...grpc.CallOption) (*QueryAccessRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAccessRecordsResponse)
	err := c.cc.Invoke(ctx, Query_AccessRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	Vault(context.Context, *QueryVaultRequest) (*QueryVaultResponse, error)
	Vaults(context.Context, *QueryVaultsRequest) (*QueryVaultsResponse, error)
	VaultsByOperator(context.Context, *QueryVaultsByOperatorRequest) (*QueryVaultsByOperatorResponse, error)
	Manifest(context.Context, *QueryManifestRequest) (*QueryManifestResponse, error)
	ManifestsByVault(context.Context, *QueryManifestsByVaultRequest) (*QueryManifestsByVaultResponse, error)
	AccessRecords(context.Context, *QueryAccessRecordsRequest) (*QueryAccessRecordsResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Vault(context.Context, *QueryVaultRequest) (*QueryVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Vault not implemented")
}
func (UnimplementedQueryServer) Vaults(context.Context, *QueryVaultsRequest) (*QueryVaultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Vaults not implemented")
}
func (UnimplementedQueryServer) VaultsByOperator(context.Context, *QueryVaultsByOperatorRequest) (*QueryVaultsByOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VaultsByOperator not implemented")
}
func (UnimplementedQueryServer) Manifest(context.Context, *QueryManifestRequest) (*QueryManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Manifest not implemented")
}
func (UnimplementedQueryServer) ManifestsByVault(context.Context, *QueryManifestsByVaultRequest) (*QueryManifestsByVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ManifestsByVault not implemented")
}
func (UnimplementedQueryServer) AccessRecords(context.Context, *QueryAccessRecordsRequest) (*QueryAccessRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AccessRecords not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Vault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Vault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Vault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Vault(ctx, req.(*QueryVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Vaults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVaultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Vaults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Vaults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Vaults(ctx, req.(*QueryVaultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VaultsByOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVaultsByOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VaultsByOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VaultsByOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VaultsByOperator(ctx, req.(*QueryVaultsByOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Manifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Manifest(ctx, req.(*QueryManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ManifestsByVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryManifestsByVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ManifestsByVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ManifestsByVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ManifestsByVault(ctx, req.(*QueryManifestsByVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AccessRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccessRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AccessRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AccessRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AccessRecords(ctx, req.(*QueryAccessRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zerone.private_corpus.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vault",
			Handler:    _Query_Vault_Handler,
		},
		{
			MethodName: "Vaults",
			Handler:    _Query_Vaults_Handler,
		},
		{
			MethodName: "VaultsByOperator",
			Handler:    _Query_VaultsByOperator_Handler,
		},
		{
			MethodName: "Manifest",
			Handler:    _Query_Manifest_Handler,
		},
		{
			MethodName: "ManifestsByVault",
			Handler:    _Query_ManifestsByVault_Handler,
		},
		{
			MethodName: "AccessRecords",
			Handler:    _Query_AccessRecords_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zerone/private_corpus/v1/query.proto",
}
