// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/alignment/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateRequest) Reset() {
	*x = QueryStateRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateRequest) ProtoMessage() {}

func (x *QueryStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateRequest.ProtoReflect.Descriptor instead.
func (*QueryStateRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{2}
}

type QueryStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *AlignmentState        `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateResponse) Reset() {
	*x = QueryStateResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateResponse) ProtoMessage() {}

func (x *QueryStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateResponse.ProtoReflect.Descriptor instead.
func (*QueryStateResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryStateResponse) GetState() *AlignmentState {
	if x != nil {
		return x.State
	}
	return nil
}

type QueryObservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryObservationRequest) Reset() {
	*x = QueryObservationRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryObservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryObservationRequest) ProtoMessage() {}

func (x *QueryObservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryObservationRequest.ProtoReflect.Descriptor instead.
func (*QueryObservationRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryObservationRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QueryObservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *AlignmentObservation  `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryObservationResponse) Reset() {
	*x = QueryObservationResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryObservationResponse) ProtoMessage() {}

func (x *QueryObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryObservationResponse.ProtoReflect.Descriptor instead.
func (*QueryObservationResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryObservationResponse) GetObservation() *AlignmentObservation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *QueryObservationResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type QueryScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryScoresRequest) Reset() {
	*x = QueryScoresRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScoresRequest) ProtoMessage() {}

func (x *QueryScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScoresRequest.ProtoReflect.Descriptor instead.
func (*QueryScoresRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryScoresRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QueryScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        *DimensionScores       `protobuf:"bytes,1,opt,name=scores,proto3" json:"scores,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryScoresResponse) Reset() {
	*x = QueryScoresResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScoresResponse) ProtoMessage() {}

func (x *QueryScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScoresResponse.ProtoReflect.Descriptor instead.
func (*QueryScoresResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryScoresResponse) GetScores() *DimensionScores {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *QueryScoresResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type QueryHealthIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHealthIndexRequest) Reset() {
	*x = QueryHealthIndexRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHealthIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHealthIndexRequest) ProtoMessage() {}

func (x *QueryHealthIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHealthIndexRequest.ProtoReflect.Descriptor instead.
func (*QueryHealthIndexRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryHealthIndexRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QueryHealthIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HealthIndex   *AlignmentHealthIndex  `protobuf:"bytes,1,opt,name=health_index,json=healthIndex,proto3" json:"health_index,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHealthIndexResponse) Reset() {
	*x = QueryHealthIndexResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHealthIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHealthIndexResponse) ProtoMessage() {}

func (x *QueryHealthIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHealthIndexResponse.ProtoReflect.Descriptor instead.
func (*QueryHealthIndexResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryHealthIndexResponse) GetHealthIndex() *AlignmentHealthIndex {
	if x != nil {
		return x.HealthIndex
	}
	return nil
}

func (x *QueryHealthIndexResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type QueryCorrectionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCorrectionHistoryRequest) Reset() {
	*x = QueryCorrectionHistoryRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCorrectionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCorrectionHistoryRequest) ProtoMessage() {}

func (x *QueryCorrectionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCorrectionHistoryRequest.ProtoReflect.Descriptor instead.
func (*QueryCorrectionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryCorrectionHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryCorrectionHistoryRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryCorrectionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Corrections   []*CorrectionRecord    `protobuf:"bytes,1,rep,name=corrections,proto3" json:"corrections,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCorrectionHistoryResponse) Reset() {
	*x = QueryCorrectionHistoryResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCorrectionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCorrectionHistoryResponse) ProtoMessage() {}

func (x *QueryCorrectionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCorrectionHistoryResponse.ProtoReflect.Descriptor instead.
func (*QueryCorrectionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryCorrectionHistoryResponse) GetCorrections() []*CorrectionRecord {
	if x != nil {
		return x.Corrections
	}
	return nil
}

func (x *QueryCorrectionHistoryResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type QueryHealthHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHealthHistoryRequest) Reset() {
	*x = QueryHealthHistoryRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHealthHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHealthHistoryRequest) ProtoMessage() {}

func (x *QueryHealthHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHealthHistoryRequest.ProtoReflect.Descriptor instead.
func (*QueryHealthHistoryRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryHealthHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryHealthHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       []*AlignmentHealthIndex `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHealthHistoryResponse) Reset() {
	*x = QueryHealthHistoryResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHealthHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHealthHistoryResponse) ProtoMessage() {}

func (x *QueryHealthHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHealthHistoryResponse.ProtoReflect.Descriptor instead.
func (*QueryHealthHistoryResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryHealthHistoryResponse) GetEntries() []*AlignmentHealthIndex {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CorrectionOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Dimension     string                 `protobuf:"bytes,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Magnitude     uint64                 `protobuf:"varint,3,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	ScoreBefore   uint64                 `protobuf:"varint,5,opt,name=score_before,json=scoreBefore,proto3" json:"score_before,omitempty"`
	ScoreAfter    uint64                 `protobuf:"varint,6,opt,name=score_after,json=scoreAfter,proto3" json:"score_after,omitempty"`
	Successful    bool                   `protobuf:"varint,7,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrectionOutcome) Reset() {
	*x = CorrectionOutcome{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrectionOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrectionOutcome) ProtoMessage() {}

func (x *CorrectionOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrectionOutcome.ProtoReflect.Descriptor instead.
func (*CorrectionOutcome) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *CorrectionOutcome) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CorrectionOutcome) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *CorrectionOutcome) GetMagnitude() uint64 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

func (x *CorrectionOutcome) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CorrectionOutcome) GetScoreBefore() uint64 {
	if x != nil {
		return x.ScoreBefore
	}
	return 0
}

func (x *CorrectionOutcome) GetScoreAfter() uint64 {
	if x != nil {
		return x.ScoreAfter
	}
	return 0
}

func (x *CorrectionOutcome) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type QueryCorrectionConfidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCorrectionConfidenceRequest) Reset() {
	*x = QueryCorrectionConfidenceRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCorrectionConfidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCorrectionConfidenceRequest) ProtoMessage() {}

func (x *QueryCorrectionConfidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCorrectionConfidenceRequest.ProtoReflect.Descriptor instead.
func (*QueryCorrectionConfidenceRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{15}
}

type QueryCorrectionConfidenceResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ConfidenceBps                uint64                 `protobuf:"varint,1,opt,name=confidence_bps,json=confidenceBps,proto3" json:"confidence_bps,omitempty"`
	TotalCorrections             uint64                 `protobuf:"varint,2,opt,name=total_corrections,json=totalCorrections,proto3" json:"total_corrections,omitempty"`
	SuccessfulCorrections        uint64                 `protobuf:"varint,3,opt,name=successful_corrections,json=successfulCorrections,proto3" json:"successful_corrections,omitempty"`
	EffectiveMaxMagnitude        uint64                 `protobuf:"varint,4,opt,name=effective_max_magnitude,json=effectiveMaxMagnitude,proto3" json:"effective_max_magnitude,omitempty"`
	EffectiveObservationInterval uint64                 `protobuf:"varint,5,opt,name=effective_observation_interval,json=effectiveObservationInterval,proto3" json:"effective_observation_interval,omitempty"`
	RecentOutcomes               []*CorrectionOutcome   `protobuf:"bytes,6,rep,name=recent_outcomes,json=recentOutcomes,proto3" json:"recent_outcomes,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *QueryCorrectionConfidenceResponse) Reset() {
	*x = QueryCorrectionConfidenceResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCorrectionConfidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCorrectionConfidenceResponse) ProtoMessage() {}

func (x *QueryCorrectionConfidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCorrectionConfidenceResponse.ProtoReflect.Descriptor instead.
func (*QueryCorrectionConfidenceResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryCorrectionConfidenceResponse) GetConfidenceBps() uint64 {
	if x != nil {
		return x.ConfidenceBps
	}
	return 0
}

func (x *QueryCorrectionConfidenceResponse) GetTotalCorrections() uint64 {
	if x != nil {
		return x.TotalCorrections
	}
	return 0
}

func (x *QueryCorrectionConfidenceResponse) GetSuccessfulCorrections() uint64 {
	if x != nil {
		return x.SuccessfulCorrections
	}
	return 0
}

func (x *QueryCorrectionConfidenceResponse) GetEffectiveMaxMagnitude() uint64 {
	if x != nil {
		return x.EffectiveMaxMagnitude
	}
	return 0
}

func (x *QueryCorrectionConfidenceResponse) GetEffectiveObservationInterval() uint64 {
	if x != nil {
		return x.EffectiveObservationInterval
	}
	return 0
}

func (x *QueryCorrectionConfidenceResponse) GetRecentOutcomes() []*CorrectionOutcome {
	if x != nil {
		return x.RecentOutcomes
	}
	return nil
}

type ModulePacingEffect struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Module         string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Parameter      string                 `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	BaseValue      uint64                 `protobuf:"varint,3,opt,name=base_value,json=baseValue,proto3" json:"base_value,omitempty"`
	EffectiveValue uint64                 `protobuf:"varint,4,opt,name=effective_value,json=effectiveValue,proto3" json:"effective_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModulePacingEffect) Reset() {
	*x = ModulePacingEffect{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModulePacingEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulePacingEffect) ProtoMessage() {}

func (x *ModulePacingEffect) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulePacingEffect.ProtoReflect.Descriptor instead.
func (*ModulePacingEffect) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *ModulePacingEffect) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ModulePacingEffect) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *ModulePacingEffect) GetBaseValue() uint64 {
	if x != nil {
		return x.BaseValue
	}
	return 0
}

func (x *ModulePacingEffect) GetEffectiveValue() uint64 {
	if x != nil {
		return x.EffectiveValue
	}
	return 0
}

type QueryGlobalPacingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGlobalPacingRequest) Reset() {
	*x = QueryGlobalPacingRequest{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGlobalPacingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGlobalPacingRequest) ProtoMessage() {}

func (x *QueryGlobalPacingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGlobalPacingRequest.ProtoReflect.Descriptor instead.
func (*QueryGlobalPacingRequest) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{18}
}

type QueryGlobalPacingResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HealthCategory        string                 `protobuf:"bytes,1,opt,name=health_category,json=healthCategory,proto3" json:"health_category,omitempty"`
	CreationMultiplierBps uint64                 `protobuf:"varint,2,opt,name=creation_multiplier_bps,json=creationMultiplierBps,proto3" json:"creation_multiplier_bps,omitempty"`
	AnalysisMultiplierBps uint64                 `protobuf:"varint,3,opt,name=analysis_multiplier_bps,json=analysisMultiplierBps,proto3" json:"analysis_multiplier_bps,omitempty"`
	AffectedModules       []*ModulePacingEffect  `protobuf:"bytes,4,rep,name=affected_modules,json=affectedModules,proto3" json:"affected_modules,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueryGlobalPacingResponse) Reset() {
	*x = QueryGlobalPacingResponse{}
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGlobalPacingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGlobalPacingResponse) ProtoMessage() {}

func (x *QueryGlobalPacingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_alignment_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGlobalPacingResponse.ProtoReflect.Descriptor instead.
func (*QueryGlobalPacingResponse) Descriptor() ([]byte, []int) {
	return file_zerone_alignment_v1_query_proto_rawDescGZIP(), []int{19}
}

func (x *QueryGlobalPacingResponse) GetHealthCategory() string {
	if x != nil {
		return x.HealthCategory
	}
	return ""
}

func (x *QueryGlobalPacingResponse) GetCreationMultiplierBps() uint64 {
	if x != nil {
		return x.CreationMultiplierBps
	}
	return 0
}

func (x *QueryGlobalPacingResponse) GetAnalysisMultiplierBps() uint64 {
	if x != nil {
		return x.AnalysisMultiplierBps
	}
	return 0
}

func (x *QueryGlobalPacingResponse) GetAffectedModules() []*ModulePacingEffect {
	if x != nil {
		return x.AffectedModules
	}
	return nil
}

var File_zerone_alignment_v1_query_proto protoreflect.FileDescriptor

const file_zerone_alignment_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1fzerone/alignment/v1/query.proto\x12\x13zerone.alignment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fzerone/alignment/v1/types.proto\x1a!zerone/alignment/v1/genesis.proto\"\x14\n" +
	"\x12QueryParamsRequest\"J\n" +
	"\x13QueryParamsResponse\x123\n" +
	"\x06params\x18\x01 \x01(\v2\x1b.zerone.alignment.v1.ParamsR\x06params\"\x13\n" +
	"\x11QueryStateRequest\"O\n" +
	"\x12QueryStateResponse\x129\n" +
	"\x05state\x18\x01 \x01(\v2#.zerone.alignment.v1.AlignmentStateR\x05state\"1\n" +
	"\x17QueryObservationRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"}\n" +
	"\x18QueryObservationResponse\x12K\n" +
	"\vobservation\x18\x01 \x01(\v2).zerone.alignment.v1.AlignmentObservationR\vobservation\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\",\n" +
	"\x12QueryScoresRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"i\n" +
	"\x13QueryScoresResponse\x12<\n" +
	"\x06scores\x18\x01 \x01(\v2$.zerone.alignment.v1.DimensionScoresR\x06scores\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"1\n" +
	"\x17QueryHealthIndexRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"~\n" +
	"\x18QueryHealthIndexResponse\x12L\n" +
	"\fhealth_index\x18\x01 \x01(\v2).zerone.alignment.v1.AlignmentHealthIndexR\vhealthIndex\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"M\n" +
	"\x1dQueryCorrectionHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"\x7f\n" +
	"\x1eQueryCorrectionHistoryResponse\x12G\n" +
	"\vcorrections\x18\x01 \x03(\v2%.zerone.alignment.v1.CorrectionRecordR\vcorrections\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"1\n" +
	"\x19QueryHealthHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"a\n" +
	"\x1aQueryHealthHistoryResponse\x12C\n" +
	"\aentries\x18\x01 \x03(\v2).zerone.alignment.v1.AlignmentHealthIndexR\aentries\"\xe9\x01\n" +
	"\x11CorrectionOutcome\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\tR\tdimension\x12\x1c\n" +
	"\tmagnitude\x18\x03 \x01(\x04R\tmagnitude\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12!\n" +
	"\fscore_before\x18\x05 \x01(\x04R\vscoreBefore\x12\x1f\n" +
	"\vscore_after\x18\x06 \x01(\x04R\n" +
	"scoreAfter\x12\x1e\n" +
	"\n" +
	"successful\x18\a \x01(\bR\n" +
	"successful\"\"\n" +
	" QueryCorrectionConfidenceRequest\"\xfd\x02\n" +
	"!QueryCorrectionConfidenceResponse\x12%\n" +
	"\x0econfidence_bps\x18\x01 \x01(\x04R\rconfidenceBps\x12+\n" +
	"\x11total_corrections\x18\x02 \x01(\x04R\x10totalCorrections\x125\n" +
	"\x16successful_corrections\x18\x03 \x01(\x04R\x15successfulCorrections\x126\n" +
	"\x17effective_max_magnitude\x18\x04 \x01(\x04R\x15effectiveMaxMagnitude\x12D\n" +
	"\x1eeffective_observation_interval\x18\x05 \x01(\x04R\x1ceffectiveObservationInterval\x12O\n" +
	"\x0frecent_outcomes\x18\x06 \x03(\v2&.zerone.alignment.v1.CorrectionOutcomeR\x0erecentOutcomes\"\x92\x01\n" +
	"\x12ModulePacingEffect\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\tR\tparameter\x12\x1d\n" +
	"\n" +
	"base_value\x18\x03 \x01(\x04R\tbaseValue\x12'\n" +
	"\x0feffective_value\x18\x04 \x01(\x04R\x0eeffectiveValue\"\x1a\n" +
	"\x18QueryGlobalPacingRequest\"\x88\x02\n" +
	"\x19QueryGlobalPacingResponse\x12'\n" +
	"\x0fhealth_category\x18\x01 \x01(\tR\x0ehealthCategory\x126\n" +
	"\x17creation_multiplier_bps\x18\x02 \x01(\x04R\x15creationMultiplierBps\x126\n" +
	"\x17analysis_multiplier_bps\x18\x03 \x01(\x04R\x15analysisMultiplierBps\x12R\n" +
	"\x10affected_modules\x18\x04 \x03(\v2'.zerone.alignment.v1.ModulePacingEffectR\x0faffectedModules2\xf1\n" +
	"\n" +
	"\x05Query\x12\x80\x01\n" +
	"\x06Params\x12'.zerone.alignment.v1.QueryParamsRequest\x1a(.zerone.alignment.v1.QueryParamsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/zerone/alignment/v1/params\x12|\n" +
	"\x05State\x12&.zerone.alignment.v1.QueryStateRequest\x1a'.zerone.alignment.v1.QueryStateResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/zerone/alignment/v1/state\x12\x9e\x01\n" +
	"\vObservation\x12,.zerone.alignment.v1.QueryObservationRequest\x1a-.zerone.alignment.v1.QueryObservationResponse\"2\x82\xd3\xe4\x93\x02,\x12*/zerone/alignment/v1/observations/{height}\x12\x89\x01\n" +
	"\x06Scores\x12'.zerone.alignment.v1.QueryScoresRequest\x1a(.zerone.alignment.v1.QueryScoresResponse\",\x82\xd3\xe4\x93\x02&\x12$/zerone/alignment/v1/scores/{height}\x12\x98\x01\n" +
	"\vHealthIndex\x12,.zerone.alignment.v1.QueryHealthIndexRequest\x1a-.zerone.alignment.v1.QueryHealthIndexResponse\",\x82\xd3\xe4\x93\x02&\x12$/zerone/alignment/v1/health/{height}\x12\xa6\x01\n" +
	"\x11CorrectionHistory\x122.zerone.alignment.v1.QueryCorrectionHistoryRequest\x1a3.zerone.alignment.v1.QueryCorrectionHistoryResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /zerone/alignment/v1/corrections\x12\x9d\x01\n" +
	"\rHealthHistory\x12..zerone.alignment.v1.QueryHealthHistoryRequest\x1a/.zerone.alignment.v1.QueryHealthHistoryResponse\"+\x82\xd3\xe4\x93\x02%\x12#/zerone/alignment/v1/health-history\x12\xb9\x01\n" +
	"\x14CorrectionConfidence\x125.zerone.alignment.v1.QueryCorrectionConfidenceRequest\x1a6.zerone.alignment.v1.QueryCorrectionConfidenceResponse\"2\x82\xd3\xe4\x93\x02,\x12*/zerone/alignment/v1/correction-confidence\x12\x99\x01\n" +
	"\fGlobalPacing\x12-.zerone.alignment.v1.QueryGlobalPacingRequest\x1a..zerone.alignment.v1.QueryGlobalPacingResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/zerone/alignment/v1/global-pacingB2Z0github.com/zerone-chain/zerone/x/alignment/typesb\x06proto3"

var (
	file_zerone_alignment_v1_query_proto_rawDescOnce sync.Once
	file_zerone_alignment_v1_query_proto_rawDescData []byte
)

func file_zerone_alignment_v1_query_proto_rawDescGZIP() []byte {
	file_zerone_alignment_v1_query_proto_rawDescOnce.Do(func() {
		file_zerone_alignment_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_alignment_v1_query_proto_rawDesc), len(file_zerone_alignment_v1_query_proto_rawDesc)))
	})
	return file_zerone_alignment_v1_query_proto_rawDescData
}

var file_zerone_alignment_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_zerone_alignment_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),                // 0: zerone.alignment.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),               // 1: zerone.alignment.v1.QueryParamsResponse
	(*QueryStateRequest)(nil),                 // 2: zerone.alignment.v1.QueryStateRequest
	(*QueryStateResponse)(nil),                // 3: zerone.alignment.v1.QueryStateResponse
	(*QueryObservationRequest)(nil),           // 4: zerone.alignment.v1.QueryObservationRequest
	(*QueryObservationResponse)(nil),          // 5: zerone.alignment.v1.QueryObservationResponse
	(*QueryScoresRequest)(nil),                // 6: zerone.alignment.v1.QueryScoresRequest
	(*QueryScoresResponse)(nil),               // 7: zerone.alignment.v1.QueryScoresResponse
	(*QueryHealthIndexRequest)(nil),           // 8: zerone.alignment.v1.QueryHealthIndexRequest
	(*QueryHealthIndexResponse)(nil),          // 9: zerone.alignment.v1.QueryHealthIndexResponse
	(*QueryCorrectionHistoryRequest)(nil),     // 10: zerone.alignment.v1.QueryCorrectionHistoryRequest
	(*QueryCorrectionHistoryResponse)(nil),    // 11: zerone.alignment.v1.QueryCorrectionHistoryResponse
	(*QueryHealthHistoryRequest)(nil),         // 12: zerone.alignment.v1.QueryHealthHistoryRequest
	(*QueryHealthHistoryResponse)(nil),        // 13: zerone.alignment.v1.QueryHealthHistoryResponse
	(*CorrectionOutcome)(nil),                 // 14: zerone.alignment.v1.CorrectionOutcome
	(*QueryCorrectionConfidenceRequest)(nil),  // 15: zerone.alignment.v1.QueryCorrectionConfidenceRequest
	(*QueryCorrectionConfidenceResponse)(nil), // 16: zerone.alignment.v1.QueryCorrectionConfidenceResponse
	(*ModulePacingEffect)(nil),                // 17: zerone.alignment.v1.ModulePacingEffect
	(*QueryGlobalPacingRequest)(nil),          // 18: zerone.alignment.v1.QueryGlobalPacingRequest
	(*QueryGlobalPacingResponse)(nil),         // 19: zerone.alignment.v1.QueryGlobalPacingResponse
	(*Params)(nil),                            // 20: zerone.alignment.v1.Params
	(*AlignmentState)(nil),                    // 21: zerone.alignment.v1.AlignmentState
	(*AlignmentObservation)(nil),              // 22: zerone.alignment.v1.AlignmentObservation
	(*DimensionScores)(nil),                   // 23: zerone.alignment.v1.DimensionScores
	(*AlignmentHealthIndex)(nil),              // 24: zerone.alignment.v1.AlignmentHealthIndex
	(*CorrectionRecord)(nil),                  // 25: zerone.alignment.v1.CorrectionRecord
}
var file_zerone_alignment_v1_query_proto_depIdxs = []int32{
	20, // 0: zerone.alignment.v1.QueryParamsResponse.params:type_name -> zerone.alignment.v1.Params
	21, // 1: zerone.alignment.v1.QueryStateResponse.state:type_name -> zerone.alignment.v1.AlignmentState
	22, // 2: zerone.alignment.v1.QueryObservationResponse.observation:type_name -> zerone.alignment.v1.AlignmentObservation
	23, // 3: zerone.alignment.v1.QueryScoresResponse.scores:type_name -> zerone.alignment.v1.DimensionScores
	24, // 4: zerone.alignment.v1.QueryHealthIndexResponse.health_index:type_name -> zerone.alignment.v1.AlignmentHealthIndex
	25, // 5: zerone.alignment.v1.QueryCorrectionHistoryResponse.corrections:type_name -> zerone.alignment.v1.CorrectionRecord
	24, // 6: zerone.alignment.v1.QueryHealthHistoryResponse.entries:type_name -> zerone.alignment.v1.AlignmentHealthIndex
	14, // 7: zerone.alignment.v1.QueryCorrectionConfidenceResponse.recent_outcomes:type_name -> zerone.alignment.v1.CorrectionOutcome
	17, // 8: zerone.alignment.v1.QueryGlobalPacingResponse.affected_modules:type_name -> zerone.alignment.v1.ModulePacingEffect
	0,  // 9: zerone.alignment.v1.Query.Params:input_type -> zerone.alignment.v1.QueryParamsRequest
	2,  // 10: zerone.alignment.v1.Query.State:input_type -> zerone.alignment.v1.QueryStateRequest
	4,  // 11: zerone.alignment.v1.Query.Observation:input_type -> zerone.alignment.v1.QueryObservationRequest
	6,  // 12: zerone.alignment.v1.Query.Scores:input_type -> zerone.alignment.v1.QueryScoresRequest
	8,  // 13: zerone.alignment.v1.Query.HealthIndex:input_type -> zerone.alignment.v1.QueryHealthIndexRequest
	10, // 14: zerone.alignment.v1.Query.CorrectionHistory:input_type -> zerone.alignment.v1.QueryCorrectionHistoryRequest
	12, // 15: zerone.alignment.v1.Query.HealthHistory:input_type -> zerone.alignment.v1.QueryHealthHistoryRequest
	15, // 16: zerone.alignment.v1.Query.CorrectionConfidence:input_type -> zerone.alignment.v1.QueryCorrectionConfidenceRequest
	18, // 17: zerone.alignment.v1.Query.GlobalPacing:input_type -> zerone.alignment.v1.QueryGlobalPacingRequest
	1,  // 18: zerone.alignment.v1.Query.Params:output_type -> zerone.alignment.v1.QueryParamsResponse
	3,  // 19: zerone.alignment.v1.Query.State:output_type -> zerone.alignment.v1.QueryStateResponse
	5,  // 20: zerone.alignment.v1.Query.Observation:output_type -> zerone.alignment.v1.QueryObservationResponse
	7,  // 21: zerone.alignment.v1.Query.Scores:output_type -> zerone.alignment.v1.QueryScoresResponse
	9,  // 22: zerone.alignment.v1.Query.HealthIndex:output_type -> zerone.alignment.v1.QueryHealthIndexResponse
	11, // 23: zerone.alignment.v1.Query.CorrectionHistory:output_type -> zerone.alignment.v1.QueryCorrectionHistoryResponse
	13, // 24: zerone.alignment.v1.Query.HealthHistory:output_type -> zerone.alignment.v1.QueryHealthHistoryResponse
	16, // 25: zerone.alignment.v1.Query.CorrectionConfidence:output_type -> zerone.alignment.v1.QueryCorrectionConfidenceResponse
	19, // 26: zerone.alignment.v1.Query.GlobalPacing:output_type -> zerone.alignment.v1.QueryGlobalPacingResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_zerone_alignment_v1_query_proto_init() }
func file_zerone_alignment_v1_query_proto_init() {
	if File_zerone_alignment_v1_query_proto != nil {
		return
	}
	file_zerone_alignment_v1_types_proto_init()
	file_zerone_alignment_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_alignment_v1_query_proto_rawDesc), len(file_zerone_alignment_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_alignment_v1_query_proto_goTypes,
		DependencyIndexes: file_zerone_alignment_v1_query_proto_depIdxs,
		MessageInfos:      file_zerone_alignment_v1_query_proto_msgTypes,
	}.Build()
	File_zerone_alignment_v1_query_proto = out.File
	file_zerone_alignment_v1_query_proto_goTypes = nil
	file_zerone_alignment_v1_query_proto_depIdxs = nil
}
