package types

import (
	"github.com/cosmos/cosmos-sdk/codec"
	cdctypes "github.com/cosmos/cosmos-sdk/codec/types"
	sdk "github.com/cosmos/cosmos-sdk/types"
)

// RegisterLegacyAminoCodec registers concrete types on the LegacyAmino codec.
func RegisterLegacyAminoCodec(cdc *codec.LegacyAmino) {
	cdc.RegisterConcrete(&MsgSubmitContribution{}, "zerone/contribution/MsgSubmitContribution", nil)
}

// RegisterInterfaces registers the module's interface types.
//
// Note: msgservice.RegisterMsgServiceDesc is intentionally NOT called here
// because the contribution proto bindings are generated by the modern
// google.golang.org/protobuf runtime, while the SDK's RegisterMsgServiceDesc
// requires the legacy cosmos/gogoproto file-descriptor registry. The same
// pattern is used by the sibling x/creed module. Msg types are still
// resolvable via reg.RegisterImplementations below; baseapp only requires
// the file descriptor when RegisterMsgServiceDesc is invoked.
func RegisterInterfaces(reg cdctypes.InterfaceRegistry) {
	reg.RegisterImplementations(
		(*sdk.Msg)(nil),
		&MsgSubmitContribution{},
	)
}
