// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/contribution/v1/payloads.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContributionPayload wraps the per-class payload oneof. Phase 1
// fully defines KnowledgeClaim; the other 10 variants are minimal
// stubs that future phases will expand.
type ContributionPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ContributionPayload_Knowledge
	//	*ContributionPayload_Idea
	//	*ContributionPayload_Tool
	//	*ContributionPayload_Dataset
	//	*ContributionPayload_Eval
	//	*ContributionPayload_Model
	//	*ContributionPayload_Trace
	//	*ContributionPayload_Counterex
	//	*ContributionPayload_Orch
	//	*ContributionPayload_ModProposal
	//	*ContributionPayload_PipelineImprovement
	Payload       isContributionPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionPayload) Reset() {
	*x = ContributionPayload{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionPayload) ProtoMessage() {}

func (x *ContributionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionPayload.ProtoReflect.Descriptor instead.
func (*ContributionPayload) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *ContributionPayload) GetPayload() isContributionPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ContributionPayload) GetKnowledge() *KnowledgeClaim {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Knowledge); ok {
			return x.Knowledge
		}
	}
	return nil
}

func (x *ContributionPayload) GetIdea() *Idea {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Idea); ok {
			return x.Idea
		}
	}
	return nil
}

func (x *ContributionPayload) GetTool() *Tool {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *ContributionPayload) GetDataset() *Dataset {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Dataset); ok {
			return x.Dataset
		}
	}
	return nil
}

func (x *ContributionPayload) GetEval() *EvalSuite {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Eval); ok {
			return x.Eval
		}
	}
	return nil
}

func (x *ContributionPayload) GetModel() *ModelArtifact {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Model); ok {
			return x.Model
		}
	}
	return nil
}

func (x *ContributionPayload) GetTrace() *ReasoningTrace {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Trace); ok {
			return x.Trace
		}
	}
	return nil
}

func (x *ContributionPayload) GetCounterex() *Counterexample {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Counterex); ok {
			return x.Counterex
		}
	}
	return nil
}

func (x *ContributionPayload) GetOrch() *Orchestration {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_Orch); ok {
			return x.Orch
		}
	}
	return nil
}

func (x *ContributionPayload) GetModProposal() *ModuleProposal {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_ModProposal); ok {
			return x.ModProposal
		}
	}
	return nil
}

func (x *ContributionPayload) GetPipelineImprovement() *PipelineImprovement {
	if x != nil {
		if x, ok := x.Payload.(*ContributionPayload_PipelineImprovement); ok {
			return x.PipelineImprovement
		}
	}
	return nil
}

type isContributionPayload_Payload interface {
	isContributionPayload_Payload()
}

type ContributionPayload_Knowledge struct {
	Knowledge *KnowledgeClaim `protobuf:"bytes,1,opt,name=knowledge,proto3,oneof"`
}

type ContributionPayload_Idea struct {
	Idea *Idea `protobuf:"bytes,2,opt,name=idea,proto3,oneof"`
}

type ContributionPayload_Tool struct {
	Tool *Tool `protobuf:"bytes,3,opt,name=tool,proto3,oneof"`
}

type ContributionPayload_Dataset struct {
	Dataset *Dataset `protobuf:"bytes,4,opt,name=dataset,proto3,oneof"`
}

type ContributionPayload_Eval struct {
	Eval *EvalSuite `protobuf:"bytes,5,opt,name=eval,proto3,oneof"`
}

type ContributionPayload_Model struct {
	Model *ModelArtifact `protobuf:"bytes,6,opt,name=model,proto3,oneof"`
}

type ContributionPayload_Trace struct {
	Trace *ReasoningTrace `protobuf:"bytes,7,opt,name=trace,proto3,oneof"`
}

type ContributionPayload_Counterex struct {
	Counterex *Counterexample `protobuf:"bytes,8,opt,name=counterex,proto3,oneof"`
}

type ContributionPayload_Orch struct {
	Orch *Orchestration `protobuf:"bytes,9,opt,name=orch,proto3,oneof"`
}

type ContributionPayload_ModProposal struct {
	ModProposal *ModuleProposal `protobuf:"bytes,10,opt,name=mod_proposal,json=modProposal,proto3,oneof"`
}

type ContributionPayload_PipelineImprovement struct {
	PipelineImprovement *PipelineImprovement `protobuf:"bytes,11,opt,name=pipeline_improvement,json=pipelineImprovement,proto3,oneof"`
}

func (*ContributionPayload_Knowledge) isContributionPayload_Payload() {}

func (*ContributionPayload_Idea) isContributionPayload_Payload() {}

func (*ContributionPayload_Tool) isContributionPayload_Payload() {}

func (*ContributionPayload_Dataset) isContributionPayload_Payload() {}

func (*ContributionPayload_Eval) isContributionPayload_Payload() {}

func (*ContributionPayload_Model) isContributionPayload_Payload() {}

func (*ContributionPayload_Trace) isContributionPayload_Payload() {}

func (*ContributionPayload_Counterex) isContributionPayload_Payload() {}

func (*ContributionPayload_Orch) isContributionPayload_Payload() {}

func (*ContributionPayload_ModProposal) isContributionPayload_Payload() {}

func (*ContributionPayload_PipelineImprovement) isContributionPayload_Payload() {}

// KnowledgeClaim — fully defined at Phase 1 (the only adapter wired).
type KnowledgeClaim struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClaimId          string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`                            // back-reference to x/knowledge.Claim.id
	Domain           string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                                             // epistemic domain
	StatementHash    []byte                 `protobuf:"bytes,3,opt,name=statement_hash,json=statementHash,proto3" json:"statement_hash,omitempty"`          // sha256 of the claim statement
	MethodologyTrace []byte                 `protobuf:"bytes,4,opt,name=methodology_trace,json=methodologyTrace,proto3" json:"methodology_trace,omitempty"` // serialized reasoning path (commitment 14)
	AxiomRefs        []string               `protobuf:"bytes,5,rep,name=axiom_refs,json=axiomRefs,proto3" json:"axiom_refs,omitempty"`                      // foundational axiom IDs the claim derives from
	TokManifestCid   string                 `protobuf:"bytes,6,opt,name=tok_manifest_cid,json=tokManifestCid,proto3" json:"tok_manifest_cid,omitempty"`     // for M2 substrate-link
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KnowledgeClaim) Reset() {
	*x = KnowledgeClaim{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeClaim) ProtoMessage() {}

func (x *KnowledgeClaim) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeClaim.ProtoReflect.Descriptor instead.
func (*KnowledgeClaim) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{1}
}

func (x *KnowledgeClaim) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *KnowledgeClaim) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *KnowledgeClaim) GetStatementHash() []byte {
	if x != nil {
		return x.StatementHash
	}
	return nil
}

func (x *KnowledgeClaim) GetMethodologyTrace() []byte {
	if x != nil {
		return x.MethodologyTrace
	}
	return nil
}

func (x *KnowledgeClaim) GetAxiomRefs() []string {
	if x != nil {
		return x.AxiomRefs
	}
	return nil
}

func (x *KnowledgeClaim) GetTokManifestCid() string {
	if x != nil {
		return x.TokManifestCid
	}
	return ""
}

// Stubs — expanded by future phases as adapters land.
type Idea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idea) Reset() {
	*x = Idea{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idea) ProtoMessage() {}

func (x *Idea) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idea.ProtoReflect.Descriptor instead.
func (*Idea) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{2}
}

func (x *Idea) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{3}
}

func (x *Tool) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type Dataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{4}
}

func (x *Dataset) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type EvalSuite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalSuite) Reset() {
	*x = EvalSuite{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalSuite) ProtoMessage() {}

func (x *EvalSuite) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalSuite.ProtoReflect.Descriptor instead.
func (*EvalSuite) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{5}
}

func (x *EvalSuite) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type ModelArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelArtifact) Reset() {
	*x = ModelArtifact{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelArtifact) ProtoMessage() {}

func (x *ModelArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelArtifact.ProtoReflect.Descriptor instead.
func (*ModelArtifact) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{6}
}

func (x *ModelArtifact) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type ReasoningTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningTrace) Reset() {
	*x = ReasoningTrace{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningTrace) ProtoMessage() {}

func (x *ReasoningTrace) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningTrace.ProtoReflect.Descriptor instead.
func (*ReasoningTrace) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{7}
}

func (x *ReasoningTrace) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type Counterexample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counterexample) Reset() {
	*x = Counterexample{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counterexample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counterexample) ProtoMessage() {}

func (x *Counterexample) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counterexample.ProtoReflect.Descriptor instead.
func (*Counterexample) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{8}
}

func (x *Counterexample) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type Orchestration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orchestration) Reset() {
	*x = Orchestration{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orchestration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orchestration) ProtoMessage() {}

func (x *Orchestration) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orchestration.ProtoReflect.Descriptor instead.
func (*Orchestration) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{9}
}

func (x *Orchestration) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type ModuleProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleProposal) Reset() {
	*x = ModuleProposal{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleProposal) ProtoMessage() {}

func (x *ModuleProposal) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleProposal.ProtoReflect.Descriptor instead.
func (*ModuleProposal) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{10}
}

func (x *ModuleProposal) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

type PipelineImprovement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpaquePayload []byte                 `protobuf:"bytes,1,opt,name=opaque_payload,json=opaquePayload,proto3" json:"opaque_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineImprovement) Reset() {
	*x = PipelineImprovement{}
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineImprovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineImprovement) ProtoMessage() {}

func (x *PipelineImprovement) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_contribution_v1_payloads_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineImprovement.ProtoReflect.Descriptor instead.
func (*PipelineImprovement) Descriptor() ([]byte, []int) {
	return file_zerone_contribution_v1_payloads_proto_rawDescGZIP(), []int{11}
}

func (x *PipelineImprovement) GetOpaquePayload() []byte {
	if x != nil {
		return x.OpaquePayload
	}
	return nil
}

var File_zerone_contribution_v1_payloads_proto protoreflect.FileDescriptor

const file_zerone_contribution_v1_payloads_proto_rawDesc = "" +
	"\n" +
	"%zerone/contribution/v1/payloads.proto\x12\x16zerone.contribution.v1\"\xf9\x05\n" +
	"\x13ContributionPayload\x12F\n" +
	"\tknowledge\x18\x01 \x01(\v2&.zerone.contribution.v1.KnowledgeClaimH\x00R\tknowledge\x122\n" +
	"\x04idea\x18\x02 \x01(\v2\x1c.zerone.contribution.v1.IdeaH\x00R\x04idea\x122\n" +
	"\x04tool\x18\x03 \x01(\v2\x1c.zerone.contribution.v1.ToolH\x00R\x04tool\x12;\n" +
	"\adataset\x18\x04 \x01(\v2\x1f.zerone.contribution.v1.DatasetH\x00R\adataset\x127\n" +
	"\x04eval\x18\x05 \x01(\v2!.zerone.contribution.v1.EvalSuiteH\x00R\x04eval\x12=\n" +
	"\x05model\x18\x06 \x01(\v2%.zerone.contribution.v1.ModelArtifactH\x00R\x05model\x12>\n" +
	"\x05trace\x18\a \x01(\v2&.zerone.contribution.v1.ReasoningTraceH\x00R\x05trace\x12F\n" +
	"\tcounterex\x18\b \x01(\v2&.zerone.contribution.v1.CounterexampleH\x00R\tcounterex\x12;\n" +
	"\x04orch\x18\t \x01(\v2%.zerone.contribution.v1.OrchestrationH\x00R\x04orch\x12K\n" +
	"\fmod_proposal\x18\n" +
	" \x01(\v2&.zerone.contribution.v1.ModuleProposalH\x00R\vmodProposal\x12`\n" +
	"\x14pipeline_improvement\x18\v \x01(\v2+.zerone.contribution.v1.PipelineImprovementH\x00R\x13pipelineImprovementB\t\n" +
	"\apayload\"\xe0\x01\n" +
	"\x0eKnowledgeClaim\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12%\n" +
	"\x0estatement_hash\x18\x03 \x01(\fR\rstatementHash\x12+\n" +
	"\x11methodology_trace\x18\x04 \x01(\fR\x10methodologyTrace\x12\x1d\n" +
	"\n" +
	"axiom_refs\x18\x05 \x03(\tR\taxiomRefs\x12(\n" +
	"\x10tok_manifest_cid\x18\x06 \x01(\tR\x0etokManifestCid\"-\n" +
	"\x04Idea\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"-\n" +
	"\x04Tool\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"0\n" +
	"\aDataset\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"2\n" +
	"\tEvalSuite\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"6\n" +
	"\rModelArtifact\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"7\n" +
	"\x0eReasoningTrace\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"7\n" +
	"\x0eCounterexample\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"6\n" +
	"\rOrchestration\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"7\n" +
	"\x0eModuleProposal\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayload\"<\n" +
	"\x13PipelineImprovement\x12%\n" +
	"\x0eopaque_payload\x18\x01 \x01(\fR\ropaquePayloadB5Z3github.com/zerone-chain/zerone/x/contribution/typesb\x06proto3"

var (
	file_zerone_contribution_v1_payloads_proto_rawDescOnce sync.Once
	file_zerone_contribution_v1_payloads_proto_rawDescData []byte
)

func file_zerone_contribution_v1_payloads_proto_rawDescGZIP() []byte {
	file_zerone_contribution_v1_payloads_proto_rawDescOnce.Do(func() {
		file_zerone_contribution_v1_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_contribution_v1_payloads_proto_rawDesc), len(file_zerone_contribution_v1_payloads_proto_rawDesc)))
	})
	return file_zerone_contribution_v1_payloads_proto_rawDescData
}

var file_zerone_contribution_v1_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_zerone_contribution_v1_payloads_proto_goTypes = []any{
	(*ContributionPayload)(nil), // 0: zerone.contribution.v1.ContributionPayload
	(*KnowledgeClaim)(nil),      // 1: zerone.contribution.v1.KnowledgeClaim
	(*Idea)(nil),                // 2: zerone.contribution.v1.Idea
	(*Tool)(nil),                // 3: zerone.contribution.v1.Tool
	(*Dataset)(nil),             // 4: zerone.contribution.v1.Dataset
	(*EvalSuite)(nil),           // 5: zerone.contribution.v1.EvalSuite
	(*ModelArtifact)(nil),       // 6: zerone.contribution.v1.ModelArtifact
	(*ReasoningTrace)(nil),      // 7: zerone.contribution.v1.ReasoningTrace
	(*Counterexample)(nil),      // 8: zerone.contribution.v1.Counterexample
	(*Orchestration)(nil),       // 9: zerone.contribution.v1.Orchestration
	(*ModuleProposal)(nil),      // 10: zerone.contribution.v1.ModuleProposal
	(*PipelineImprovement)(nil), // 11: zerone.contribution.v1.PipelineImprovement
}
var file_zerone_contribution_v1_payloads_proto_depIdxs = []int32{
	1,  // 0: zerone.contribution.v1.ContributionPayload.knowledge:type_name -> zerone.contribution.v1.KnowledgeClaim
	2,  // 1: zerone.contribution.v1.ContributionPayload.idea:type_name -> zerone.contribution.v1.Idea
	3,  // 2: zerone.contribution.v1.ContributionPayload.tool:type_name -> zerone.contribution.v1.Tool
	4,  // 3: zerone.contribution.v1.ContributionPayload.dataset:type_name -> zerone.contribution.v1.Dataset
	5,  // 4: zerone.contribution.v1.ContributionPayload.eval:type_name -> zerone.contribution.v1.EvalSuite
	6,  // 5: zerone.contribution.v1.ContributionPayload.model:type_name -> zerone.contribution.v1.ModelArtifact
	7,  // 6: zerone.contribution.v1.ContributionPayload.trace:type_name -> zerone.contribution.v1.ReasoningTrace
	8,  // 7: zerone.contribution.v1.ContributionPayload.counterex:type_name -> zerone.contribution.v1.Counterexample
	9,  // 8: zerone.contribution.v1.ContributionPayload.orch:type_name -> zerone.contribution.v1.Orchestration
	10, // 9: zerone.contribution.v1.ContributionPayload.mod_proposal:type_name -> zerone.contribution.v1.ModuleProposal
	11, // 10: zerone.contribution.v1.ContributionPayload.pipeline_improvement:type_name -> zerone.contribution.v1.PipelineImprovement
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_zerone_contribution_v1_payloads_proto_init() }
func file_zerone_contribution_v1_payloads_proto_init() {
	if File_zerone_contribution_v1_payloads_proto != nil {
		return
	}
	file_zerone_contribution_v1_payloads_proto_msgTypes[0].OneofWrappers = []any{
		(*ContributionPayload_Knowledge)(nil),
		(*ContributionPayload_Idea)(nil),
		(*ContributionPayload_Tool)(nil),
		(*ContributionPayload_Dataset)(nil),
		(*ContributionPayload_Eval)(nil),
		(*ContributionPayload_Model)(nil),
		(*ContributionPayload_Trace)(nil),
		(*ContributionPayload_Counterex)(nil),
		(*ContributionPayload_Orch)(nil),
		(*ContributionPayload_ModProposal)(nil),
		(*ContributionPayload_PipelineImprovement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_contribution_v1_payloads_proto_rawDesc), len(file_zerone_contribution_v1_payloads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_contribution_v1_payloads_proto_goTypes,
		DependencyIndexes: file_zerone_contribution_v1_payloads_proto_depIdxs,
		MessageInfos:      file_zerone_contribution_v1_payloads_proto_msgTypes,
	}.Build()
	File_zerone_contribution_v1_payloads_proto = out.File
	file_zerone_contribution_v1_payloads_proto_goTypes = nil
	file_zerone_contribution_v1_payloads_proto_depIdxs = nil
}
