// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/auth/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccountRequest) Reset() {
	*x = QueryAccountRequest{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccountRequest) ProtoMessage() {}

func (x *QueryAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccountRequest.ProtoReflect.Descriptor instead.
func (*QueryAccountRequest) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryAccountRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type QueryAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccountResponse) Reset() {
	*x = QueryAccountResponse{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccountResponse) ProtoMessage() {}

func (x *QueryAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccountResponse.ProtoReflect.Descriptor instead.
func (*QueryAccountResponse) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type QueryAccountByDIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccountByDIDRequest) Reset() {
	*x = QueryAccountByDIDRequest{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccountByDIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccountByDIDRequest) ProtoMessage() {}

func (x *QueryAccountByDIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccountByDIDRequest.ProtoReflect.Descriptor instead.
func (*QueryAccountByDIDRequest) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryAccountByDIDRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type QueryAccountByDIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccountByDIDResponse) Reset() {
	*x = QueryAccountByDIDResponse{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccountByDIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccountByDIDResponse) ProtoMessage() {}

func (x *QueryAccountByDIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccountByDIDResponse.ProtoReflect.Descriptor instead.
func (*QueryAccountByDIDResponse) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAccountByDIDResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type QuerySessionKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionKeysRequest) Reset() {
	*x = QuerySessionKeysRequest{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionKeysRequest) ProtoMessage() {}

func (x *QuerySessionKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionKeysRequest.ProtoReflect.Descriptor instead.
func (*QuerySessionKeysRequest) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySessionKeysRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type QuerySessionKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKeys   []*SessionKey          `protobuf:"bytes,1,rep,name=session_keys,json=sessionKeys,proto3" json:"session_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionKeysResponse) Reset() {
	*x = QuerySessionKeysResponse{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionKeysResponse) ProtoMessage() {}

func (x *QuerySessionKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionKeysResponse.ProtoReflect.Descriptor instead.
func (*QuerySessionKeysResponse) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySessionKeysResponse) GetSessionKeys() []*SessionKey {
	if x != nil {
		return x.SessionKeys
	}
	return nil
}

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{6}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryFrozenAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFrozenAccountsRequest) Reset() {
	*x = QueryFrozenAccountsRequest{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFrozenAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFrozenAccountsRequest) ProtoMessage() {}

func (x *QueryFrozenAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFrozenAccountsRequest.ProtoReflect.Descriptor instead.
func (*QueryFrozenAccountsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{8}
}

type QueryFrozenAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFrozenAccountsResponse) Reset() {
	*x = QueryFrozenAccountsResponse{}
	mi := &file_zerone_auth_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFrozenAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFrozenAccountsResponse) ProtoMessage() {}

func (x *QueryFrozenAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_auth_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFrozenAccountsResponse.ProtoReflect.Descriptor instead.
func (*QueryFrozenAccountsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_auth_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryFrozenAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_zerone_auth_v1_query_proto protoreflect.FileDescriptor

const file_zerone_auth_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1azerone/auth/v1/query.proto\x12\x0ezerone.auth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1azerone/auth/v1/types.proto\x1a\x1czerone/auth/v1/genesis.proto\"/\n" +
	"\x13QueryAccountRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"I\n" +
	"\x14QueryAccountResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.zerone.auth.v1.AccountR\aaccount\",\n" +
	"\x18QueryAccountByDIDRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"N\n" +
	"\x19QueryAccountByDIDResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.zerone.auth.v1.AccountR\aaccount\"/\n" +
	"\x17QuerySessionKeysRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\"Y\n" +
	"\x18QuerySessionKeysResponse\x12=\n" +
	"\fsession_keys\x18\x01 \x03(\v2\x1a.zerone.auth.v1.SessionKeyR\vsessionKeys\"\x14\n" +
	"\x12QueryParamsRequest\"E\n" +
	"\x13QueryParamsResponse\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.zerone.auth.v1.ParamsR\x06params\"\x1c\n" +
	"\x1aQueryFrozenAccountsRequest\"R\n" +
	"\x1bQueryFrozenAccountsResponse\x123\n" +
	"\baccounts\x18\x01 \x03(\v2\x17.zerone.auth.v1.AccountR\baccounts2\xb5\x05\n" +
	"\x05Query\x12\x7f\n" +
	"\aAccount\x12#.zerone.auth.v1.QueryAccountRequest\x1a$.zerone.auth.v1.QueryAccountResponse\")\x82\xd3\xe4\x93\x02#\x12!/zerone/auth/v1/account/{address}\x12\x91\x01\n" +
	"\fAccountByDID\x12(.zerone.auth.v1.QueryAccountByDIDRequest\x1a).zerone.auth.v1.QueryAccountByDIDResponse\",\x82\xd3\xe4\x93\x02&\x12$/zerone/auth/v1/account_by_did/{did}\x12\x8e\x01\n" +
	"\vSessionKeys\x12'.zerone.auth.v1.QuerySessionKeysRequest\x1a(.zerone.auth.v1.QuerySessionKeysResponse\",\x82\xd3\xe4\x93\x02&\x12$/zerone/auth/v1/session_keys/{owner}\x12q\n" +
	"\x06Params\x12\".zerone.auth.v1.QueryParamsRequest\x1a#.zerone.auth.v1.QueryParamsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/zerone/auth/v1/params\x12\x92\x01\n" +
	"\x0eFrozenAccounts\x12*.zerone.auth.v1.QueryFrozenAccountsRequest\x1a+.zerone.auth.v1.QueryFrozenAccountsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/zerone/auth/v1/frozen_accountsB-Z+github.com/zerone-chain/zerone/x/auth/typesb\x06proto3"

var (
	file_zerone_auth_v1_query_proto_rawDescOnce sync.Once
	file_zerone_auth_v1_query_proto_rawDescData []byte
)

func file_zerone_auth_v1_query_proto_rawDescGZIP() []byte {
	file_zerone_auth_v1_query_proto_rawDescOnce.Do(func() {
		file_zerone_auth_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_auth_v1_query_proto_rawDesc), len(file_zerone_auth_v1_query_proto_rawDesc)))
	})
	return file_zerone_auth_v1_query_proto_rawDescData
}

var file_zerone_auth_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_zerone_auth_v1_query_proto_goTypes = []any{
	(*QueryAccountRequest)(nil),         // 0: zerone.auth.v1.QueryAccountRequest
	(*QueryAccountResponse)(nil),        // 1: zerone.auth.v1.QueryAccountResponse
	(*QueryAccountByDIDRequest)(nil),    // 2: zerone.auth.v1.QueryAccountByDIDRequest
	(*QueryAccountByDIDResponse)(nil),   // 3: zerone.auth.v1.QueryAccountByDIDResponse
	(*QuerySessionKeysRequest)(nil),     // 4: zerone.auth.v1.QuerySessionKeysRequest
	(*QuerySessionKeysResponse)(nil),    // 5: zerone.auth.v1.QuerySessionKeysResponse
	(*QueryParamsRequest)(nil),          // 6: zerone.auth.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),         // 7: zerone.auth.v1.QueryParamsResponse
	(*QueryFrozenAccountsRequest)(nil),  // 8: zerone.auth.v1.QueryFrozenAccountsRequest
	(*QueryFrozenAccountsResponse)(nil), // 9: zerone.auth.v1.QueryFrozenAccountsResponse
	(*Account)(nil),                     // 10: zerone.auth.v1.Account
	(*SessionKey)(nil),                  // 11: zerone.auth.v1.SessionKey
	(*Params)(nil),                      // 12: zerone.auth.v1.Params
}
var file_zerone_auth_v1_query_proto_depIdxs = []int32{
	10, // 0: zerone.auth.v1.QueryAccountResponse.account:type_name -> zerone.auth.v1.Account
	10, // 1: zerone.auth.v1.QueryAccountByDIDResponse.account:type_name -> zerone.auth.v1.Account
	11, // 2: zerone.auth.v1.QuerySessionKeysResponse.session_keys:type_name -> zerone.auth.v1.SessionKey
	12, // 3: zerone.auth.v1.QueryParamsResponse.params:type_name -> zerone.auth.v1.Params
	10, // 4: zerone.auth.v1.QueryFrozenAccountsResponse.accounts:type_name -> zerone.auth.v1.Account
	0,  // 5: zerone.auth.v1.Query.Account:input_type -> zerone.auth.v1.QueryAccountRequest
	2,  // 6: zerone.auth.v1.Query.AccountByDID:input_type -> zerone.auth.v1.QueryAccountByDIDRequest
	4,  // 7: zerone.auth.v1.Query.SessionKeys:input_type -> zerone.auth.v1.QuerySessionKeysRequest
	6,  // 8: zerone.auth.v1.Query.Params:input_type -> zerone.auth.v1.QueryParamsRequest
	8,  // 9: zerone.auth.v1.Query.FrozenAccounts:input_type -> zerone.auth.v1.QueryFrozenAccountsRequest
	1,  // 10: zerone.auth.v1.Query.Account:output_type -> zerone.auth.v1.QueryAccountResponse
	3,  // 11: zerone.auth.v1.Query.AccountByDID:output_type -> zerone.auth.v1.QueryAccountByDIDResponse
	5,  // 12: zerone.auth.v1.Query.SessionKeys:output_type -> zerone.auth.v1.QuerySessionKeysResponse
	7,  // 13: zerone.auth.v1.Query.Params:output_type -> zerone.auth.v1.QueryParamsResponse
	9,  // 14: zerone.auth.v1.Query.FrozenAccounts:output_type -> zerone.auth.v1.QueryFrozenAccountsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_zerone_auth_v1_query_proto_init() }
func file_zerone_auth_v1_query_proto_init() {
	if File_zerone_auth_v1_query_proto != nil {
		return
	}
	file_zerone_auth_v1_types_proto_init()
	file_zerone_auth_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_auth_v1_query_proto_rawDesc), len(file_zerone_auth_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_auth_v1_query_proto_goTypes,
		DependencyIndexes: file_zerone_auth_v1_query_proto_depIdxs,
		MessageInfos:      file_zerone_auth_v1_query_proto_msgTypes,
	}.Build()
	File_zerone_auth_v1_query_proto = out.File
	file_zerone_auth_v1_query_proto_goTypes = nil
	file_zerone_auth_v1_query_proto_depIdxs = nil
}
