// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zerone/knowledge/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Sample_FullMethodName             = "/zerone.knowledge.v1.Query/Sample"
	Query_Samples_FullMethodName            = "/zerone.knowledge.v1.Query/Samples"
	Query_SamplesByDomain_FullMethodName    = "/zerone.knowledge.v1.Query/SamplesByDomain"
	Query_SamplesByThread_FullMethodName    = "/zerone.knowledge.v1.Query/SamplesByThread"
	Query_SamplesBySubmitter_FullMethodName = "/zerone.knowledge.v1.Query/SamplesBySubmitter"
	Query_Submission_FullMethodName         = "/zerone.knowledge.v1.Query/Submission"
	Query_PendingSubmissions_FullMethodName = "/zerone.knowledge.v1.Query/PendingSubmissions"
	Query_QualityRound_FullMethodName       = "/zerone.knowledge.v1.Query/QualityRound"
	Query_Dataset_FullMethodName            = "/zerone.knowledge.v1.Query/Dataset"
	Query_Datasets_FullMethodName           = "/zerone.knowledge.v1.Query/Datasets"
	Query_TrainingDemand_FullMethodName     = "/zerone.knowledge.v1.Query/TrainingDemand"
	Query_DataBounties_FullMethodName       = "/zerone.knowledge.v1.Query/DataBounties"
	Query_Domain_FullMethodName             = "/zerone.knowledge.v1.Query/Domain"
	Query_Domains_FullMethodName            = "/zerone.knowledge.v1.Query/Domains"
	Query_DomainStats_FullMethodName        = "/zerone.knowledge.v1.Query/DomainStats"
	Query_ProtocolStats_FullMethodName      = "/zerone.knowledge.v1.Query/ProtocolStats"
	Query_Params_FullMethodName             = "/zerone.knowledge.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC query service for the knowledge module.
type QueryClient interface {
	// Sample queries a single sample by ID.
	Sample(ctx context.Context, in *QuerySampleRequest, opts ...grpc.CallOption) (*QuerySampleResponse, error)
	// Samples queries samples with optional filters.
	Samples(ctx context.Context, in *QuerySamplesRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error)
	// SamplesByDomain queries all samples in a domain.
	SamplesByDomain(ctx context.Context, in *QuerySamplesByDomainRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error)
	// SamplesByThread queries all samples in a conversation thread.
	SamplesByThread(ctx context.Context, in *QuerySamplesByThreadRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error)
	// SamplesBySubmitter queries all samples submitted by an address.
	SamplesBySubmitter(ctx context.Context, in *QuerySamplesBySubmitterRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error)
	// Submission queries a single submission by ID.
	Submission(ctx context.Context, in *QuerySubmissionRequest, opts ...grpc.CallOption) (*QuerySubmissionResponse, error)
	// PendingSubmissions queries all pending submissions.
	PendingSubmissions(ctx context.Context, in *QueryPendingSubmissionsRequest, opts ...grpc.CallOption) (*QuerySubmissionsResponse, error)
	// QualityRound queries a quality round by ID.
	QualityRound(ctx context.Context, in *QueryQualityRoundRequest, opts ...grpc.CallOption) (*QueryQualityRoundResponse, error)
	// Dataset queries a dataset by ID.
	Dataset(ctx context.Context, in *QueryDatasetRequest, opts ...grpc.CallOption) (*QueryDatasetResponse, error)
	// Datasets queries all datasets with optional filters.
	Datasets(ctx context.Context, in *QueryDatasetsRequest, opts ...grpc.CallOption) (*QueryDatasetsResponse, error)
	// TrainingDemand queries training demand data.
	TrainingDemand(ctx context.Context, in *QueryTrainingDemandRequest, opts ...grpc.CallOption) (*QueryTrainingDemandResponse, error)
	// DataBounties queries active data bounties.
	DataBounties(ctx context.Context, in *QueryDataBountiesRequest, opts ...grpc.CallOption) (*QueryDataBountiesResponse, error)
	// Domain queries a domain by name.
	Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error)
	// Domains queries all domains with optional pagination.
	Domains(ctx context.Context, in *QueryDomainsRequest, opts ...grpc.CallOption) (*QueryDomainsResponse, error)
	// DomainStats queries statistics for a specific domain.
	DomainStats(ctx context.Context, in *QueryDomainStatsRequest, opts ...grpc.CallOption) (*QueryDomainStatsResponse, error)
	// ProtocolStats queries aggregate protocol statistics.
	ProtocolStats(ctx context.Context, in *QueryProtocolStatsRequest, opts ...grpc.CallOption) (*QueryProtocolStatsResponse, error)
	// Params queries module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Sample(ctx context.Context, in *QuerySampleRequest, opts ...grpc.CallOption) (*QuerySampleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySampleResponse)
	err := c.cc.Invoke(ctx, Query_Sample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Samples(ctx context.Context, in *QuerySamplesRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySamplesResponse)
	err := c.cc.Invoke(ctx, Query_Samples_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SamplesByDomain(ctx context.Context, in *QuerySamplesByDomainRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySamplesResponse)
	err := c.cc.Invoke(ctx, Query_SamplesByDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SamplesByThread(ctx context.Context, in *QuerySamplesByThreadRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySamplesResponse)
	err := c.cc.Invoke(ctx, Query_SamplesByThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SamplesBySubmitter(ctx context.Context, in *QuerySamplesBySubmitterRequest, opts ...grpc.CallOption) (*QuerySamplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySamplesResponse)
	err := c.cc.Invoke(ctx, Query_SamplesBySubmitter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Submission(ctx context.Context, in *QuerySubmissionRequest, opts ...grpc.CallOption) (*QuerySubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySubmissionResponse)
	err := c.cc.Invoke(ctx, Query_Submission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingSubmissions(ctx context.Context, in *QueryPendingSubmissionsRequest, opts ...grpc.CallOption) (*QuerySubmissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySubmissionsResponse)
	err := c.cc.Invoke(ctx, Query_PendingSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QualityRound(ctx context.Context, in *QueryQualityRoundRequest, opts ...grpc.CallOption) (*QueryQualityRoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryQualityRoundResponse)
	err := c.cc.Invoke(ctx, Query_QualityRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Dataset(ctx context.Context, in *QueryDatasetRequest, opts ...grpc.CallOption) (*QueryDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDatasetResponse)
	err := c.cc.Invoke(ctx, Query_Dataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Datasets(ctx context.Context, in *QueryDatasetsRequest, opts ...grpc.CallOption) (*QueryDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDatasetsResponse)
	err := c.cc.Invoke(ctx, Query_Datasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TrainingDemand(ctx context.Context, in *QueryTrainingDemandRequest, opts ...grpc.CallOption) (*QueryTrainingDemandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTrainingDemandResponse)
	err := c.cc.Invoke(ctx, Query_TrainingDemand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DataBounties(ctx context.Context, in *QueryDataBountiesRequest, opts ...grpc.CallOption) (*QueryDataBountiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDataBountiesResponse)
	err := c.cc.Invoke(ctx, Query_DataBounties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDomainResponse)
	err := c.cc.Invoke(ctx, Query_Domain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Domains(ctx context.Context, in *QueryDomainsRequest, opts ...grpc.CallOption) (*QueryDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDomainsResponse)
	err := c.cc.Invoke(ctx, Query_Domains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DomainStats(ctx context.Context, in *QueryDomainStatsRequest, opts ...grpc.CallOption) (*QueryDomainStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDomainStatsResponse)
	err := c.cc.Invoke(ctx, Query_DomainStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProtocolStats(ctx context.Context, in *QueryProtocolStatsRequest, opts ...grpc.CallOption) (*QueryProtocolStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryProtocolStatsResponse)
	err := c.cc.Invoke(ctx, Query_ProtocolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC query service for the knowledge module.
type QueryServer interface {
	// Sample queries a single sample by ID.
	Sample(context.Context, *QuerySampleRequest) (*QuerySampleResponse, error)
	// Samples queries samples with optional filters.
	Samples(context.Context, *QuerySamplesRequest) (*QuerySamplesResponse, error)
	// SamplesByDomain queries all samples in a domain.
	SamplesByDomain(context.Context, *QuerySamplesByDomainRequest) (*QuerySamplesResponse, error)
	// SamplesByThread queries all samples in a conversation thread.
	SamplesByThread(context.Context, *QuerySamplesByThreadRequest) (*QuerySamplesResponse, error)
	// SamplesBySubmitter queries all samples submitted by an address.
	SamplesBySubmitter(context.Context, *QuerySamplesBySubmitterRequest) (*QuerySamplesResponse, error)
	// Submission queries a single submission by ID.
	Submission(context.Context, *QuerySubmissionRequest) (*QuerySubmissionResponse, error)
	// PendingSubmissions queries all pending submissions.
	PendingSubmissions(context.Context, *QueryPendingSubmissionsRequest) (*QuerySubmissionsResponse, error)
	// QualityRound queries a quality round by ID.
	QualityRound(context.Context, *QueryQualityRoundRequest) (*QueryQualityRoundResponse, error)
	// Dataset queries a dataset by ID.
	Dataset(context.Context, *QueryDatasetRequest) (*QueryDatasetResponse, error)
	// Datasets queries all datasets with optional filters.
	Datasets(context.Context, *QueryDatasetsRequest) (*QueryDatasetsResponse, error)
	// TrainingDemand queries training demand data.
	TrainingDemand(context.Context, *QueryTrainingDemandRequest) (*QueryTrainingDemandResponse, error)
	// DataBounties queries active data bounties.
	DataBounties(context.Context, *QueryDataBountiesRequest) (*QueryDataBountiesResponse, error)
	// Domain queries a domain by name.
	Domain(context.Context, *QueryDomainRequest) (*QueryDomainResponse, error)
	// Domains queries all domains with optional pagination.
	Domains(context.Context, *QueryDomainsRequest) (*QueryDomainsResponse, error)
	// DomainStats queries statistics for a specific domain.
	DomainStats(context.Context, *QueryDomainStatsRequest) (*QueryDomainStatsResponse, error)
	// ProtocolStats queries aggregate protocol statistics.
	ProtocolStats(context.Context, *QueryProtocolStatsRequest) (*QueryProtocolStatsResponse, error)
	// Params queries module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Sample(context.Context, *QuerySampleRequest) (*QuerySampleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sample not implemented")
}
func (UnimplementedQueryServer) Samples(context.Context, *QuerySamplesRequest) (*QuerySamplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Samples not implemented")
}
func (UnimplementedQueryServer) SamplesByDomain(context.Context, *QuerySamplesByDomainRequest) (*QuerySamplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SamplesByDomain not implemented")
}
func (UnimplementedQueryServer) SamplesByThread(context.Context, *QuerySamplesByThreadRequest) (*QuerySamplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SamplesByThread not implemented")
}
func (UnimplementedQueryServer) SamplesBySubmitter(context.Context, *QuerySamplesBySubmitterRequest) (*QuerySamplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SamplesBySubmitter not implemented")
}
func (UnimplementedQueryServer) Submission(context.Context, *QuerySubmissionRequest) (*QuerySubmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submission not implemented")
}
func (UnimplementedQueryServer) PendingSubmissions(context.Context, *QueryPendingSubmissionsRequest) (*QuerySubmissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PendingSubmissions not implemented")
}
func (UnimplementedQueryServer) QualityRound(context.Context, *QueryQualityRoundRequest) (*QueryQualityRoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QualityRound not implemented")
}
func (UnimplementedQueryServer) Dataset(context.Context, *QueryDatasetRequest) (*QueryDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dataset not implemented")
}
func (UnimplementedQueryServer) Datasets(context.Context, *QueryDatasetsRequest) (*QueryDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Datasets not implemented")
}
func (UnimplementedQueryServer) TrainingDemand(context.Context, *QueryTrainingDemandRequest) (*QueryTrainingDemandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainingDemand not implemented")
}
func (UnimplementedQueryServer) DataBounties(context.Context, *QueryDataBountiesRequest) (*QueryDataBountiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataBounties not implemented")
}
func (UnimplementedQueryServer) Domain(context.Context, *QueryDomainRequest) (*QueryDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Domain not implemented")
}
func (UnimplementedQueryServer) Domains(context.Context, *QueryDomainsRequest) (*QueryDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Domains not implemented")
}
func (UnimplementedQueryServer) DomainStats(context.Context, *QueryDomainStatsRequest) (*QueryDomainStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DomainStats not implemented")
}
func (UnimplementedQueryServer) ProtocolStats(context.Context, *QueryProtocolStatsRequest) (*QueryProtocolStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProtocolStats not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Sample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Sample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Sample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Sample(ctx, req.(*QuerySampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Samples_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySamplesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Samples(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Samples_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Samples(ctx, req.(*QuerySamplesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SamplesByDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySamplesByDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SamplesByDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SamplesByDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SamplesByDomain(ctx, req.(*QuerySamplesByDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SamplesByThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySamplesByThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SamplesByThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SamplesByThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SamplesByThread(ctx, req.(*QuerySamplesByThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SamplesBySubmitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySamplesBySubmitterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SamplesBySubmitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SamplesBySubmitter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SamplesBySubmitter(ctx, req.(*QuerySamplesBySubmitterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Submission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Submission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Submission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Submission(ctx, req.(*QuerySubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingSubmissions(ctx, req.(*QueryPendingSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QualityRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryQualityRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QualityRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QualityRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QualityRound(ctx, req.(*QueryQualityRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Dataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Dataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Dataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Dataset(ctx, req.(*QueryDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Datasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Datasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Datasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Datasets(ctx, req.(*QueryDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TrainingDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrainingDemandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TrainingDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TrainingDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TrainingDemand(ctx, req.(*QueryTrainingDemandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DataBounties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDataBountiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DataBounties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DataBounties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DataBounties(ctx, req.(*QueryDataBountiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Domain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Domain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Domain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Domain(ctx, req.(*QueryDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Domains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Domains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Domains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Domains(ctx, req.(*QueryDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DomainStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DomainStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DomainStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DomainStats(ctx, req.(*QueryDomainStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProtocolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProtocolStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProtocolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ProtocolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProtocolStats(ctx, req.(*QueryProtocolStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zerone.knowledge.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sample",
			Handler:    _Query_Sample_Handler,
		},
		{
			MethodName: "Samples",
			Handler:    _Query_Samples_Handler,
		},
		{
			MethodName: "SamplesByDomain",
			Handler:    _Query_SamplesByDomain_Handler,
		},
		{
			MethodName: "SamplesByThread",
			Handler:    _Query_SamplesByThread_Handler,
		},
		{
			MethodName: "SamplesBySubmitter",
			Handler:    _Query_SamplesBySubmitter_Handler,
		},
		{
			MethodName: "Submission",
			Handler:    _Query_Submission_Handler,
		},
		{
			MethodName: "PendingSubmissions",
			Handler:    _Query_PendingSubmissions_Handler,
		},
		{
			MethodName: "QualityRound",
			Handler:    _Query_QualityRound_Handler,
		},
		{
			MethodName: "Dataset",
			Handler:    _Query_Dataset_Handler,
		},
		{
			MethodName: "Datasets",
			Handler:    _Query_Datasets_Handler,
		},
		{
			MethodName: "TrainingDemand",
			Handler:    _Query_TrainingDemand_Handler,
		},
		{
			MethodName: "DataBounties",
			Handler:    _Query_DataBounties_Handler,
		},
		{
			MethodName: "Domain",
			Handler:    _Query_Domain_Handler,
		},
		{
			MethodName: "Domains",
			Handler:    _Query_Domains_Handler,
		},
		{
			MethodName: "DomainStats",
			Handler:    _Query_DomainStats_Handler,
		},
		{
			MethodName: "ProtocolStats",
			Handler:    _Query_ProtocolStats_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zerone/knowledge/v1/query.proto",
}
